import type { ContentBatch } from "@/domains/trainingprogram/content-spec";

/**
 * Full-coverage replacement for powerlifter's 3 deactivated programs (see
 * migration 0053) -- those were genuinely authored with 1-3 exercises per
 * session throughout. This follows the same "full major-movement-pattern
 * coverage per strength session" fix 0049 already applied to hybrid_athlete,
 * grounded in Westside Barbell's actual published Conjugate Method
 * structure: Max Effort (1 near-max lift + repeated-effort accessories)
 * and Dynamic Effort (submaximal speed work + accessories) days, with the
 * source's own stated split -- main lifts ~20% of volume, repeated-effort
 * accessories ~80% -- directly motivating 4-5 exercises per session
 * instead of 1-2.
 */
export const batch: ContentBatch = {
  newExercises: [],
  programs: [
    {
      archetype: "powerlifter",
      slug: "powerlifter-conjugate-full-coverage",
      name: "Conjugate Method: Full Coverage",
      description:
        "Westside Barbell's Conjugate Method: Max Effort days build near-max strength on a rotating main lift, Dynamic Effort days build speed-strength with submaximal, explosive reps -- both paired with real repeated-effort accessory volume (not just the one main lift), per Westside's own emphasis that accessories, not the main lift, drive most of a lifter's progress.",
      methodologyNote:
        "Westside Barbell / Louie Simmons' Conjugate Method: Max Effort (near-maximal loads) and Dynamic Effort (submaximal loads at maximal speed) days, each built around one primary lift plus repeated-effort accessory work -- the source states main lifts are roughly 20% of total training volume, with repeated-effort accessories comprising the remaining 80%, which is why every session here includes real accessory coverage rather than just the main lift.",
      experienceLevel: "intermediate",
      sessionsPerWeekMin: 4,
      sessionsPerWeekMax: 4,
      equipmentRequired: ["Barbell", "Dumbbells", "Full gym access"],
      displayOrder: 1,
      phases: [
        {
          name: "Foundation",
          focus: "Learn the Max Effort / Dynamic Effort rhythm and build accessory work capacity at moderate intensity.",
          lengthWeeks: 4,
          intensityStyle: "RPE 6-8",
          isFinal: false,
          sessions: [
            {
              name: "Max Effort Lower",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell back squat",
                  sets: 1,
                  repsMin: 1,
                  repsMax: 3,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Work up to a heavy but clean triple for the week -- this is the Max Effort lift.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Front squat",
                  sets: 3,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Quad-biased repeated-effort accessory -- upright torso position also carries over to the ME lift.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Good morning",
                  sets: 3,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Posterior-chain repeated-effort work -- keep the back flat, hinge from the hips.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Reverse hyper",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Low back / glute recovery work Westside uses heavily between max-effort sessions.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Plank",
                  sets: 3,
                  repsMin: 1,
                  repsMax: 1,
                  intensityType: "none",
                  coachingNotes: "30-45 second holds -- core bracing carries directly into squat/deadlift stability.",
                },
              ],
            },
            {
              name: "Max Effort Upper",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell bench press",
                  sets: 1,
                  repsMin: 1,
                  repsMax: 3,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Work up to a heavy but clean triple -- the Max Effort lift for upper body.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Close-grip bench press",
                  sets: 3,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Triceps/lockout-biased repeated-effort accessory.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell row",
                  sets: 4,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Back volume to balance pressing -- Westside trains pulling at least as hard as pressing.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Dumbbell lateral raise",
                  sets: 3,
                  repsMin: 12,
                  repsMax: 15,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Shoulder health/accessory volume.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Triceps pushdown",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "6-7",
                  coachingNotes: "Extra triceps volume for lockout strength.",
                },
              ],
            },
            {
              name: "Dynamic Effort Lower",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell back squat",
                  sets: 8,
                  repsMin: 2,
                  repsMax: 2,
                  intensityType: "percent_1rm",
                  intensityValue: "50-60",
                  coachingNotes: "Speed work -- move the bar as explosively as possible, rest ~60s between sets.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell deadlift",
                  sets: 6,
                  repsMin: 1,
                  repsMax: 1,
                  intensityType: "percent_1rm",
                  intensityValue: "60",
                  coachingNotes: "Speed pulls off the floor -- Dynamic Effort for the hinge pattern.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Bulgarian split squat",
                  sets: 3,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Per leg -- unilateral repeated-effort accessory.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Back extension",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Posterior-chain accessory volume.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Hanging leg raise",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Core work to close the session.",
                },
              ],
            },
            {
              name: "Dynamic Effort Upper",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell bench press",
                  sets: 9,
                  repsMin: 3,
                  repsMax: 3,
                  intensityType: "percent_1rm",
                  intensityValue: "50-60",
                  coachingNotes: "Speed bench -- explosive reps off the chest, rest ~45-60s between sets.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell overhead press",
                  sets: 3,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Secondary press accessory.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Pull-up",
                  sets: 4,
                  repsMin: 6,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Back/grip volume -- use an assisted variation if a clean set of 6 isn't there yet.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Face pull",
                  sets: 3,
                  repsMin: 12,
                  repsMax: 15,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Rear delt/shoulder health -- Westside's accessory work leans heavily on shoulder health for pressing longevity.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Dumbbell curl",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "6",
                  coachingNotes: "Arm accessory volume.",
                },
              ],
            },
          ],
        },
        {
          name: "Intensification",
          focus: "Rotate the Max Effort lifts, push Dynamic Effort loading percentages up, and raise accessory intensity.",
          lengthWeeks: 5,
          intensityStyle: "RPE 7-9",
          isFinal: true,
          sessions: [
            {
              name: "Max Effort Lower",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell deadlift",
                  sets: 1,
                  repsMin: 1,
                  repsMax: 2,
                  intensityType: "rpe",
                  intensityValue: "9",
                  coachingNotes: "Rotated ME lift from the Foundation phase's squat -- Westside rotates the ME movement roughly every 1-3 weeks; simplified here to a phase-level rotation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Front squat",
                  sets: 3,
                  repsMin: 5,
                  repsMax: 6,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Heavier than the Foundation phase.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Good morning",
                  sets: 3,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Heavier posterior-chain loading than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Reverse hyper",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Kept in the same rep range -- this is recovery/health work, not a max-effort movement.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Plank",
                  sets: 3,
                  repsMin: 1,
                  repsMax: 1,
                  intensityType: "none",
                  coachingNotes: "45-60 second holds.",
                },
              ],
            },
            {
              name: "Max Effort Upper",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell bench press",
                  sets: 1,
                  repsMin: 1,
                  repsMax: 2,
                  intensityType: "rpe",
                  intensityValue: "9",
                  coachingNotes: "Heavier top double than the Foundation phase's triple.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Close-grip bench press",
                  sets: 3,
                  repsMin: 5,
                  repsMax: 6,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Heavier than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell row",
                  sets: 4,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Heavier pulling volume than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Dumbbell lateral raise",
                  sets: 3,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Slightly heavier than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Triceps pushdown",
                  sets: 3,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7-8",
                  coachingNotes: "Heavier lockout accessory work.",
                },
              ],
            },
            {
              name: "Dynamic Effort Lower",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell back squat",
                  sets: 10,
                  repsMin: 2,
                  repsMax: 2,
                  intensityType: "percent_1rm",
                  intensityValue: "60-70",
                  coachingNotes: "Higher percentage and two more sets than Foundation -- the DE wave rolls upward.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell deadlift",
                  sets: 8,
                  repsMin: 1,
                  repsMax: 1,
                  intensityType: "percent_1rm",
                  intensityValue: "70",
                  coachingNotes: "Heavier speed pulls than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Bulgarian split squat",
                  sets: 3,
                  repsMin: 6,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Heavier per-leg loading than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Back extension",
                  sets: 3,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Slightly heavier than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Hanging leg raise",
                  sets: 4,
                  repsMin: 10,
                  repsMax: 12,
                  intensityType: "rpe",
                  intensityValue: "7-8",
                  coachingNotes: "Added a set from Foundation.",
                },
              ],
            },
            {
              name: "Dynamic Effort Upper",
              sessionType: "strength",
              exercises: [
                {
                  kind: "strength",
                  exerciseRef: "Barbell bench press",
                  sets: 9,
                  repsMin: 3,
                  repsMax: 3,
                  intensityType: "percent_1rm",
                  intensityValue: "60-70",
                  coachingNotes: "Higher percentage than Foundation -- same wave logic as the lower-body DE day.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Barbell overhead press",
                  sets: 3,
                  repsMin: 5,
                  repsMax: 6,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Heavier than Foundation.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Pull-up",
                  sets: 4,
                  repsMin: 5,
                  repsMax: 8,
                  intensityType: "rpe",
                  intensityValue: "8",
                  coachingNotes: "Add weight if bodyweight reps are no longer challenging in this range.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Face pull",
                  sets: 3,
                  repsMin: 12,
                  repsMax: 15,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Kept high-rep even as other lifts intensify -- shoulder health work stays submaximal by design.",
                },
                {
                  kind: "strength",
                  exerciseRef: "Dumbbell curl",
                  sets: 3,
                  repsMin: 8,
                  repsMax: 10,
                  intensityType: "rpe",
                  intensityValue: "7",
                  coachingNotes: "Heavier than Foundation.",
                },
              ],
            },
          ],
        },
      ],
      sources: [
        {
          organization: "Louie Simmons / Westside Barbell",
          title: "The Conjugate Method: Westside Barbell Conjugate Training",
          url: "https://www.westside-barbell.com/pages/conjugate-method",
          retrievedAt: "2026-08-05",
        },
      ],
    },
  ],
};
