import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Plant-forward batch (content-expansion 4e, 2026-08-14) — targeted at
 * the pools the new hard dietary filters left thin, measured live before
 * drafting: vegan dinner 6, vegan breakfast 9, vegetarian dinner 9 (out
 * of ~64 per meal type). 13 vegan + 3 vegetarian recipes, weighted
 * toward dinner/lunch. Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------- Vegan dinners ----------------
    {
      name: "Tofu Green Curry with Brown Rice",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "curry",
      calories: 518,
      proteinG: 28,
      carbsG: 52,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "high-protein", "gluten-free"],
      allergens: ["soybeans"],
      ingredients: [
        { name: "Extra-firm tofu", quantity: 7, unit: "oz", section: "protein" },
        { name: "Green curry paste", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Light coconut milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Cooked brown rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Broccoli florets", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper", quantity: 1, unit: "each", section: "produce" },
        { name: "Tamari", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Press the tofu, cut into cubes, and sear in a hot nonstick pan until golden on two sides.",
        "Add curry paste and a splash of coconut milk, stirring until fragrant.",
        "Add the remaining coconut milk, broccoli, and bell pepper; simmer 8-10 minutes until tender.",
        "Season with tamari and lime juice, and serve over the brown rice.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; store rice separately if possible.",
    },
    {
      name: "Lentil Bolognese with Spaghetti",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 524,
      proteinG: 26,
      carbsG: 78,
      fatG: 12,
      fiberG: 14,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Cooked brown or green lentils", quantity: 1, unit: "cup", section: "protein" },
        { name: "Crushed tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Yellow onion", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Carrot", quantity: 1, unit: "each", section: "produce" },
        { name: "Garlic", quantity: 2, unit: "cloves", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Italian herbs", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the spaghetti in salted water per the package.",
        "Soften diced onion, carrot, and garlic in olive oil, 5-6 minutes.",
        "Add lentils, crushed tomatoes, and herbs; simmer 15 minutes until thick.",
        "Toss with the drained pasta and a splash of pasta water.",
      ],
      storageInstructions: "Sauce keeps 4 days refrigerated and freezes well.",
    },
    {
      name: "Chickpea Coconut Curry",
      mealType: "dinner",
      cuisine: "indian",
      dishType: "curry",
      calories: 524,
      proteinG: 19,
      carbsG: 58,
      fatG: 24,
      fiberG: 13,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free"],
      allergens: [],
      ingredients: [
        { name: "Canned chickpeas", quantity: 1, unit: "cup", section: "protein" },
        { name: "Light coconut milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Diced tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Cooked basmati rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Baby spinach", quantity: 2, unit: "cups", section: "produce" },
        { name: "Curry powder", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Soften the diced onion, then bloom the curry powder for 30 seconds.",
        "Add chickpeas, tomatoes, and coconut milk; simmer 15 minutes.",
        "Wilt in the spinach at the end and serve over rice.",
      ],
      storageInstructions: "Keeps 4 days refrigerated; flavor improves overnight.",
    },
    {
      name: "Black Bean Sweet Potato Bowl",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "bowl",
      calories: 504,
      proteinG: 18,
      carbsG: 72,
      fatG: 16,
      fiberG: 16,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free"],
      allergens: [],
      ingredients: [
        { name: "Sweet potato", quantity: 1, unit: "large", section: "produce" },
        { name: "Canned black beans", quantity: 0.75, unit: "cup", section: "protein" },
        { name: "Cooked rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Salsa", quantity: 0.25, unit: "cup", section: "pantry" },
        { name: "Cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Roast cubed sweet potato with cumin at 425°F for 25-30 minutes.",
        "Warm the black beans with a pinch of salt.",
        "Assemble over rice with avocado, salsa, and a squeeze of lime.",
      ],
      storageInstructions: "Components keep 4 days refrigerated; add avocado fresh.",
    },
    {
      name: "Teriyaki Tempeh Stir-fry",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "stir_fry",
      calories: 474,
      proteinG: 30,
      carbsG: 48,
      fatG: 18,
      fiberG: 9,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "high-protein", "quick"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Tempeh", quantity: 4, unit: "oz", section: "protein" },
        { name: "Teriyaki sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Snap peas", quantity: 1, unit: "cup", section: "produce" },
        { name: "Carrot", quantity: 1, unit: "each", section: "produce" },
        { name: "Sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Scallions", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Sear sliced tempeh in sesame oil until browned on both sides.",
        "Add snap peas and carrot; stir-fry 3-4 minutes.",
        "Glaze with teriyaki and soy sauce, and serve over rice with scallions.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
    {
      name: "White Bean Mushroom Ragout with Polenta",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "stew",
      calories: 454,
      proteinG: 20,
      carbsG: 62,
      fatG: 14,
      fiberG: 12,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free"],
      allergens: [],
      ingredients: [
        { name: "Cannellini beans", quantity: 0.75, unit: "cup", section: "protein" },
        { name: "Cremini mushrooms", quantity: 1.5, unit: "cups", section: "produce" },
        { name: "Instant polenta", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Crushed tomatoes", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Garlic", quantity: 2, unit: "cloves", section: "produce" },
        { name: "Olive oil", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Brown the mushrooms hard in olive oil before salting.",
        "Add garlic, beans, tomatoes, and thyme; simmer 10 minutes.",
        "Cook the polenta per the package and spoon the ragout over it.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; loosen polenta with water when reheating.",
    },

    // ---------------- Vegan lunches ----------------
    {
      name: "Peanut Noodle Bowl with Edamame",
      mealType: "lunch",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 508,
      proteinG: 24,
      carbsG: 58,
      fatG: 20,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "high-protein", "make-ahead"],
      allergens: ["peanuts", "wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Lo mein noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Shelled edamame", quantity: 0.75, unit: "cup", section: "protein" },
        { name: "Peanut butter", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sesame oil", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Shredded cabbage", quantity: 1, unit: "cup", section: "produce" },
        { name: "Cucumber", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cook the noodles and edamame; rinse under cold water.",
        "Whisk peanut butter, soy sauce, vinegar, and sesame oil with a splash of warm water.",
        "Toss everything with the cabbage and cucumber.",
      ],
      storageInstructions: "Keeps 3 days refrigerated — an ideal make-ahead lunch.",
    },
    {
      name: "Mediterranean Quinoa Salad",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "salad",
      calories: 446,
      proteinG: 16,
      carbsG: 55,
      fatG: 18,
      fiberG: 10,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free", "make-ahead"],
      allergens: [],
      ingredients: [
        { name: "Dry quinoa", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Canned chickpeas", quantity: 0.5, unit: "cup", section: "protein" },
        { name: "Cherry tomatoes", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Cucumber", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Kalamata olives", quantity: 8, unit: "each", section: "pantry" },
        { name: "Olive oil", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh parsley", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Cook the quinoa and let it cool slightly.",
        "Toss with chickpeas, chopped vegetables, olives, and parsley.",
        "Dress with olive oil, lemon juice, salt, and pepper.",
      ],
      storageInstructions: "Keeps 4 days refrigerated; dress just before eating if making ahead.",
    },
    {
      name: "Smoky Tofu Burrito Bowl",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "bowl",
      calories: 488,
      proteinG: 26,
      carbsG: 60,
      fatG: 16,
      fiberG: 12,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free", "high-protein"],
      allergens: ["soybeans"],
      ingredients: [
        { name: "Extra-firm tofu", quantity: 6, unit: "oz", section: "protein" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cooked rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Canned black beans", quantity: 0.5, unit: "cup", section: "protein" },
        { name: "Corn kernels", quantity: 0.5, unit: "cup", section: "frozen" },
        { name: "Salsa", quantity: 0.25, unit: "cup", section: "pantry" },
        { name: "Romaine lettuce", quantity: 1, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Crumble the tofu and pan-fry with smoked paprika, cumin, and salt until browned.",
        "Warm the beans and corn.",
        "Assemble over rice and lettuce, topped with salsa.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
    {
      name: "Miso Ginger Soba with Roasted Vegetables",
      mealType: "lunch",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 446,
      proteinG: 18,
      carbsG: 62,
      fatG: 14,
      fiberG: 8,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Soba noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "White miso paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh ginger", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Broccoli florets", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper", quantity: 1, unit: "each", section: "produce" },
        { name: "Sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Roast the broccoli and pepper at 425°F for 15-18 minutes.",
        "Cook the soba and rinse under cold water.",
        "Whisk miso, grated ginger, vinegar, and sesame oil; toss everything together.",
      ],
      storageInstructions: "Keeps 3 days refrigerated, eaten cold or reheated.",
    },

    // ---------------- Vegan breakfasts ----------------
    {
      name: "Tofu Veggie Scramble",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 306,
      proteinG: 22,
      carbsG: 14,
      fatG: 18,
      fiberG: 5,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free", "high-protein", "quick"],
      allergens: ["soybeans"],
      ingredients: [
        { name: "Extra-firm tofu", quantity: 6, unit: "oz", section: "protein" },
        { name: "Baby spinach", quantity: 1.5, unit: "cups", section: "produce" },
        { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Turmeric", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Nutritional yeast", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Crumble the tofu into a hot oiled pan with turmeric and salt.",
        "Cook 5-6 minutes until it starts to color, then fold in tomatoes and spinach.",
        "Finish with nutritional yeast and black pepper.",
      ],
      storageInstructions: "Best fresh; keeps 2 days refrigerated.",
    },
    {
      name: "Peanut Butter Banana Overnight Oats",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 412,
      proteinG: 15,
      carbsG: 52,
      fatG: 16,
      fiberG: 9,
      prepMinutes: 5,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "make-ahead", "quick"],
      allergens: ["peanuts"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Unsweetened oat milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Peanut butter", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Banana", quantity: 1, unit: "each", section: "produce" },
        { name: "Chia seeds", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cinnamon", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Stir everything except the banana together in a jar.",
        "Refrigerate overnight.",
        "Top with sliced banana in the morning.",
      ],
      storageInstructions: "Keeps 3 days refrigerated (add banana fresh).",
    },
    {
      name: "Chia Berry Coconut Bowl",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "bowl",
      calories: 372,
      proteinG: 10,
      carbsG: 38,
      fatG: 20,
      fiberG: 15,
      prepMinutes: 5,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegan", "vegetarian", "gluten-free", "make-ahead"],
      allergens: [],
      ingredients: [
        { name: "Chia seeds", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Light coconut milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Mixed berries", quantity: 1, unit: "cup", section: "frozen" },
        { name: "Maple syrup", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Shredded coconut", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Whisk chia seeds into the coconut milk with maple syrup; refrigerate at least 2 hours or overnight.",
        "Top with berries and shredded coconut.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },

    // ---------------- Vegetarian dinners ----------------
    {
      name: "Paneer Tikka Bowl",
      mealType: "dinner",
      cuisine: "indian",
      dishType: "bowl",
      calories: 536,
      proteinG: 28,
      carbsG: 52,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "gluten-free", "high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Paneer", quantity: 4, unit: "oz", section: "dairy" },
        { name: "Plain yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Tikka spice blend", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cooked basmati rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Red bell pepper", quantity: 1, unit: "each", section: "produce" },
        { name: "Red onion", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Cilantro", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Toss paneer cubes, pepper, and onion in yogurt and tikka spices; marinate 10 minutes.",
        "Roast at 450°F (or broil) for 12-15 minutes until charred at the edges.",
        "Serve over rice with cilantro.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
    {
      name: "Caprese Baked Gnocchi",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 522,
      proteinG: 22,
      carbsG: 68,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Potato gnocchi", quantity: 6, unit: "oz", section: "grains" },
        { name: "Marinara sauce", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Fresh mozzarella", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Fresh basil", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toss gnocchi with marinara and tomatoes in a small baking dish.",
        "Top with torn mozzarella and bake at 425°F for 20-25 minutes until bubbling.",
        "Finish with basil and a drizzle of olive oil.",
      ],
      storageInstructions: "Keeps 2 days refrigerated.",
    },
    {
      name: "Veggie Egg Fried Rice",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "rice",
      calories: 494,
      proteinG: 21,
      carbsG: 62,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "quick"],
      allergens: ["eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Cooked day-old rice", quantity: 1.25, unit: "cups", section: "grains" },
        { name: "Eggs", quantity: 2, unit: "each", section: "dairy" },
        { name: "Frozen peas and carrots", quantity: 0.75, unit: "cup", section: "frozen" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Scallions", quantity: 2, unit: "each", section: "produce" },
        { name: "Neutral oil", quantity: 2, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Scramble the eggs in a hot wok and set aside.",
        "Stir-fry the vegetables, then the rice, pressing it against the wok to crisp.",
        "Return the eggs, season with soy sauce and sesame oil, and finish with scallions.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
  ],
};
