import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 3a of 4 (2026-08-16) — pasta and seafood.
 *
 * `pasta` held only 6 recipes before this despite being one of the most
 * cooked categories in the country; the balanced-by-cuisine seeding had
 * spent its Italian slots on other forms. `seafood` held 11, almost all
 * of them some variation on baked salmon or cod.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Pasta
    // ---------------------------------------------------------------
    {
      name: "Spaghetti Carbonara",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 574,
      proteinG: 32,
      carbsG: 62,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "eggs", "milk"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 3, unit: "oz", section: "grains" },
        { name: "Guanciale or pancetta, diced", quantity: 2, unit: "oz", section: "protein" },
        { name: "Egg yolks", quantity: 2, unit: "each", section: "protein" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Pecorino Romano, grated", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Coarse black pepper", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Render the guanciale slowly until crisp and reserve the fat in the pan.",
        "Whisk the yolks, whole egg, pecorino, and a great deal of black pepper into a paste.",
        "Cook the spaghetti and reserve a cup of the starchy water before draining.",
        "Take the pan OFF the heat entirely. Add the pasta, then the egg mixture, tossing constantly and loosening with pasta water until it turns glossy.",
        "There is no cream in carbonara — the sauce is emulsified egg. Any direct heat at this stage scrambles it, and it cannot be fixed.",
      ],
      storageInstructions: "Eat immediately. Carbonara does not reheat — the egg sauce breaks.",
    },
    {
      name: "Fettuccine Alfredo with Chicken",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 642,
      proteinG: 42,
      carbsG: 60,
      fatG: 26,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry fettuccine", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Grated Parmesan", quantity: 1.25, unit: "oz", section: "dairy" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Heavy cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Season and sear the chicken, rest, and slice.",
        "Melt the butter with garlic and cream over low heat.",
        "Add the drained fettuccine with a good splash of pasta water, then the Parmesan off the heat, tossing hard until it emulsifies.",
        "The sauce should coat the noodles, not sit under them. If it looks thin, keep tossing — it thickens from agitation, not from more cheese.",
      ],
      storageInstructions: "Best fresh; reheat with a splash of milk over low heat.",
    },
    {
      name: "Penne alla Vodka",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 524,
      proteinG: 18,
      carbsG: 68,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry penne", quantity: 3, unit: "oz", section: "grains" },
        { name: "Tomato paste", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Heavy cream", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Vodka", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Yellow onion, minced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the onion in oil, then fry the tomato paste for 3-4 minutes until it darkens to brick red and smells sweet rather than tinny.",
        "Add the vodka and cook it off for 2 minutes; it dissolves aroma compounds the tomato alone won't release.",
        "Stir in the cream and a ladle of pasta water to make a smooth sauce.",
        "Toss with the drained penne and Parmesan.",
      ],
      storageInstructions: "Keeps 3 days; loosen with water when reheating.",
    },
    {
      name: "Spaghetti and Meatballs",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 588,
      proteinG: 38,
      carbsG: 64,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 3, unit: "oz", section: "grains" },
        { name: "Lean ground beef (90/10)", quantity: 4, unit: "oz", section: "protein" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole milk", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Egg", quantity: 0.5, unit: "each", section: "protein" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Marinara sauce", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Soak the breadcrumbs in milk for 5 minutes — this panade is what makes meatballs tender rather than bouncy.",
        "Mix gently with beef, egg, Parmesan, garlic, salt, and pepper, handling as little as possible.",
        "Brown the meatballs on all sides, then finish them in the simmering marinara for 20 minutes.",
        "Toss the drained spaghetti in the sauce itself rather than plating sauce on top — the pasta should be dressed, not garnished.",
      ],
      storageInstructions: "Meatballs in sauce keep 4 days and freeze 3 months.",
    },
    {
      name: "Cacio e Pepe",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 514,
      proteinG: 22,
      carbsG: 66,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 3, unit: "oz", section: "grains" },
        { name: "Pecorino Romano, finely grated", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Coarse black pepper", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Toast the cracked pepper in a dry pan 30 seconds until fragrant.",
        "Cook the pasta in less water than usual so what's left is extra starchy — that starch is the entire emulsifier here.",
        "Grate the pecorino to a powder and mix it with a little cool pasta water into a paste off the heat.",
        "Toss the drained pasta with the pepper and butter, then work in the cheese paste away from the burner.",
        "Cheese added to a hot pan seizes into stringy clumps. Low and slow, off the heat, is the whole technique.",
      ],
      storageInstructions: "Eat immediately; this does not hold or reheat.",
    },
    {
      name: "Stovetop Mac and Cheese",
      mealType: "dinner",
      cuisine: "american",
      dishType: "pasta",
      calories: 558,
      proteinG: 26,
      carbsG: 64,
      fatG: 22,
      fiberG: 3,
      prepMinutes: 5,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry elbow pasta", quantity: 3, unit: "oz", section: "grains" },
        { name: "Sharp cheddar cheese, grated", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Ground nutmeg", quantity: 0.125, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Make a roux with butter and flour and cook it 2 minutes before adding milk.",
        "Whisk in the milk gradually and simmer until it thickens enough to coat a spoon.",
        "Off the heat, add the grated cheddar in handfuls with the Dijon and nutmeg.",
        "Grate your own cheese — the anti-caking starch on pre-shredded cheese makes the sauce grainy every time.",
      ],
      storageInstructions: "Keeps 3 days; reheat with extra milk over low heat.",
    },
    {
      name: "Pasta Primavera",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 480,
      proteinG: 18,
      carbsG: 66,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry penne", quantity: 3, unit: "oz", section: "grains" },
        { name: "Asparagus, cut into pieces", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Zucchini, sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Cook the vegetables in stages by density — zucchini and asparagus first, tomatoes and peas at the end — rather than all at once.",
        "Keep them at the crisp end of tender; the point of primavera is contrast against the soft pasta.",
        "Toss with the drained penne, a ladle of pasta water, olive oil, and Parmesan.",
        "Finish with lemon zest and juice off the heat.",
      ],
      storageInstructions: "Keeps 3 days; best at room temperature rather than reheated.",
    },
    {
      name: "Pesto Chicken Pasta",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 608,
      proteinG: 40,
      carbsG: 58,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "tree_nuts"],
      ingredients: [
        { name: "Dry fusilli", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Fresh basil leaves", quantity: 2, unit: "cup", section: "produce" },
        { name: "Pine nuts", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic", quantity: 1, unit: "clove", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Toast the pine nuts in a dry pan until just golden, watching constantly — they burn in seconds.",
        "Blend basil, pine nuts, garlic, Parmesan, and olive oil, pulsing rather than running the motor. Overprocessing heats and blackens the basil.",
        "Sear and slice the chicken.",
        "Toss the pesto with the drained pasta OFF the heat with a splash of pasta water; cooking pesto turns it army green and bitter.",
      ],
      storageInstructions: "Pesto keeps a week with oil on top; assembled pasta keeps 3 days.",
    },
    {
      name: "Linguine with Clam Sauce",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 528,
      proteinG: 34,
      carbsG: 62,
      fatG: 16,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "shellfish"],
      ingredients: [
        { name: "Dry linguine", quantity: 3, unit: "oz", section: "grains" },
        { name: "Canned chopped clams with juice", quantity: 6, unit: "oz", section: "protein" },
        { name: "Dry white wine", quantity: 0.25, unit: "cup", section: "pantry" },
        { name: "Garlic, sliced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Soften the sliced garlic in olive oil over low heat until barely blond — browned garlic turns the whole dish acrid.",
        "Add wine and the clam juice and reduce by a third.",
        "Toss in the drained linguine and let it finish cooking in the sauce for a minute so it absorbs the liquid.",
        "Add the clams at the very end, just to warm through. Simmered clams turn to rubber.",
        "Finish with parsley and lemon.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Rigatoni Bolognese",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 596,
      proteinG: 38,
      carbsG: 66,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 150,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry rigatoni", quantity: 3, unit: "oz", section: "grains" },
        { name: "Lean ground beef (90/10)", quantity: 4, unit: "oz", section: "protein" },
        { name: "Whole milk", quantity: 0.25, unit: "cup", section: "dairy" },
        { name: "Canned crushed tomatoes", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Carrot, finely diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Celery, finely diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Yellow onion, finely diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dry white wine", quantity: 0.25, unit: "cup", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
      ],
      instructions: [
        "Cook the soffritto — carrot, celery, onion — slowly for 15 minutes before the meat goes anywhere near the pot.",
        "Brown the beef, then add the milk and let it cook away completely. Milk before tomato is the traditional order and it genuinely tenderizes the meat.",
        "Add wine, reduce, then the tomatoes, and simmer at the barest bubble for 2 hours.",
        "Bolognese is a meat sauce loosened with tomato, not a tomato sauce with meat — it should look brown-orange, not red.",
      ],
      storageInstructions: "Keeps 4 days, freezes 3 months, and improves overnight.",
    },
    {
      name: "Pasta e Fagioli",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "pasta",
      calories: 444,
      proteinG: 22,
      carbsG: 62,
      fatG: 12,
      fiberG: 14,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Small pasta shapes", quantity: 2, unit: "oz", section: "grains" },
        { name: "Canned cannellini beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Canned diced tomatoes", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Carrot, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Vegetable broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Rosemary", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Build a soffritto with carrot, celery, and onion in olive oil.",
        "Mash half the beans before adding them — this is what gives the dish its characteristic creamy body without any dairy.",
        "Add tomatoes, broth, and rosemary and simmer 15 minutes.",
        "Cook the pasta directly in the pot for the last 10 minutes so it releases starch into the soup.",
      ],
      storageInstructions: "Keeps 3 days and thickens considerably — thin with broth.",
    },
    {
      name: "Garlic Butter Shrimp Pasta",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 572,
      proteinG: 38,
      carbsG: 60,
      fatG: 20,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "shellfish", "milk"],
      ingredients: [
        { name: "Dry linguine", quantity: 3, unit: "oz", section: "grains" },
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Sear the shrimp 90 seconds per side in a hot pan and remove them immediately — they'll finish in the residual heat later.",
        "Lower the heat, melt the butter, and cook the garlic gently until fragrant.",
        "Add the drained pasta with a ladle of pasta water and toss until the butter emulsifies into a sauce.",
        "Return the shrimp off the heat with lemon and parsley.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Chicken Piccata with Angel Hair",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 572,
      proteinG: 42,
      carbsG: 56,
      fatG: 20,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry angel hair pasta", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Capers, drained", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Chicken broth", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Butterfly and pound the chicken thin, then dredge lightly in seasoned flour, shaking off the excess.",
        "Sear 3 minutes per side and remove.",
        "Deglaze with broth and lemon juice, scraping the browned flour off the pan — that fond is the sauce.",
        "Swirl in cold butter off the heat to thicken, then add capers and parsley.",
        "Angel hair cooks in 3 minutes and overcooks in 4, so start it after the chicken is done.",
      ],
      storageInstructions: "Keeps 3 days; sauce separately from the pasta.",
    },
    {
      name: "Sausage and Peppers Rigatoni",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 608,
      proteinG: 34,
      carbsG: 64,
      fatG: 24,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Dry rigatoni", quantity: 3, unit: "oz", section: "grains" },
        { name: "Italian sausage", quantity: 4, unit: "oz", section: "protein" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Canned crushed tomatoes", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Garlic, sliced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brown the sausage in chunks and remove, leaving the rendered fat.",
        "Cook the peppers and onion in that fat until soft and caramelized at the edges, 12 minutes.",
        "Add garlic, oregano, and tomatoes and simmer 10 minutes.",
        "Return the sausage and toss with the drained rigatoni and a little pasta water.",
      ],
      storageInstructions: "Keeps 4 days and reheats well.",
    },
    {
      name: "Creamy Tomato Tortellini",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 550,
      proteinG: 26,
      carbsG: 62,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 5,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Cheese tortellini", quantity: 4, unit: "oz", section: "grains" },
        { name: "Canned crushed tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Heavy cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh basil leaves", quantity: 6, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Simmer garlic, tomatoes, and a pinch of sugar for 10 minutes to take the raw edge off.",
        "Stir in the cream and wilt the spinach.",
        "Cook the tortellini and add them straight from the water — fresh tortellini are done in 3 minutes and split if boiled hard.",
        "Finish with Parmesan and torn basil.",
      ],
      storageInstructions: "Keeps 2 days; the tortellini soften noticeably.",
    },
    {
      name: "Pesto Genovese with Green Beans and Potato",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 550,
      proteinG: 20,
      carbsG: 68,
      fatG: 22,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk", "tree_nuts"],
      ingredients: [
        { name: "Dry trofie or fusilli", quantity: 3, unit: "oz", section: "grains" },
        { name: "Green beans, trimmed", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Baby potatoes, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Fresh basil leaves", quantity: 2, unit: "cup", section: "produce" },
        { name: "Pine nuts", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic", quantity: 1, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Cook the potatoes in the pasta water first, then add the pasta, then the green beans for the last 4 minutes — one pot, staggered.",
        "Blend the pesto cold, pulsing to avoid heating the basil.",
        "Drain, reserving water, and toss everything with the pesto off the heat.",
        "The potato is not filler: its starch is what makes the pesto cling in the Ligurian version.",
      ],
      storageInstructions: "Keeps 3 days; good cold as a pasta salad.",
    },
    {
      name: "Spaghetti Puttanesca",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 488,
      proteinG: 20,
      carbsG: 66,
      fatG: 16,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-fiber"],
      allergens: ["wheat", "fish"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 3, unit: "oz", section: "grains" },
        { name: "Anchovy fillets", quantity: 4, unit: "each", section: "protein" },
        { name: "Kalamata olives, halved", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Capers, drained", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Canned crushed tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Garlic, sliced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Melt the anchovies into warm olive oil with the garlic — stir until they dissolve completely and stop looking like fish.",
        "Add pepper flakes, olives, capers, and tomatoes and simmer 15 minutes.",
        "Do not salt until the very end. Anchovies, olives, and capers are all salty, and this sauce is easy to ruin.",
        "Toss with the drained spaghetti.",
      ],
      storageInstructions: "Sauce keeps 5 days and freezes well.",
    },
    {
      name: "Spaghetti Aglio e Olio with Broccolini",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 490,
      proteinG: 18,
      carbsG: 64,
      fatG: 18,
      fiberG: 8,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Dry spaghetti", quantity: 3, unit: "oz", section: "grains" },
        { name: "Broccolini, chopped", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Garlic, thinly sliced", quantity: 5, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Start the garlic in COLD oil and bring the heat up slowly. Garlic dropped into hot oil browns unevenly and burns before it flavours the oil.",
        "Pull it the moment it turns pale gold.",
        "Blanch the broccolini in the pasta water for the last 3 minutes.",
        "Toss everything with a generous ladle of pasta water and beat hard — the starch and oil emulsify into a sauce with no dairy at all.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Baked Feta Pasta with Cherry Tomatoes",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "pasta",
      calories: 542,
      proteinG: 22,
      carbsG: 64,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 5,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry penne", quantity: 3, unit: "oz", section: "grains" },
        { name: "Feta cheese, block", quantity: 2.5, unit: "oz", section: "dairy" },
        { name: "Cherry tomatoes", quantity: 2, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic, whole cloves", quantity: 4, unit: "clove", section: "produce" },
        { name: "Fresh basil leaves", quantity: 8, unit: "leaf", section: "produce" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Use a block of feta, not crumbles — crumbles are drier and won't melt into a sauce.",
        "Put the feta in the middle of a small dish, surround with tomatoes and garlic, and drench in olive oil.",
        "Bake at 400F for 35 minutes until the tomatoes burst and the feta slumps.",
        "Mash everything together with a fork, then fold through the drained pasta with a splash of pasta water and torn basil.",
      ],
      storageInstructions: "Keeps 3 days; loosen with oil or water when reheating.",
    },
    {
      name: "Chicken Parm Skillet Pasta",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pasta",
      calories: 624,
      proteinG: 42,
      carbsG: 60,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Dry penne", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Panko breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 0.5, unit: "each", section: "protein" },
        { name: "Marinara sauce", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Toast the panko separately in a dry pan until golden and keep it aside.",
        "Sear the cubed chicken until browned and cooked through.",
        "Add marinara and the drained pasta, then top with mozzarella and broil 3 minutes.",
        "Scatter the toasted panko over the top at the very end. Breading the chicken and then drowning it in sauce is what makes most skillet versions soggy — keeping the crunch separate solves it.",
      ],
      storageInstructions: "Keeps 3 days; store panko separately.",
    },
    {
      name: "Lemon Orzo with Asparagus",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "pasta",
      calories: 430,
      proteinG: 16,
      carbsG: 60,
      fatG: 14,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry orzo", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Asparagus, cut into pieces", quantity: 1, unit: "cup", section: "produce" },
        { name: "Feta cheese, crumbled", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh dill", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Toast the dry orzo in a little oil until it smells nutty before adding water — it keeps the grains separate rather than gluey.",
        "Cook until just tender, adding asparagus and peas for the final 3 minutes.",
        "Drain and dress immediately with lemon juice, zest, and olive oil while warm.",
        "Fold in feta and dill once it has cooled slightly.",
      ],
      storageInstructions: "Keeps 4 days and is good cold; refresh with lemon.",
    },
    {
      name: "Beef Stroganoff over Egg Noodles",
      mealType: "dinner",
      cuisine: "american",
      dishType: "pasta",
      calories: 600,
      proteinG: 40,
      carbsG: 56,
      fatG: 24,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Egg noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cremini mushrooms, sliced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Sour cream", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Beef broth", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Sear the sliced beef fast over high heat and remove within 90 seconds; it finishes in the sauce and toughens if cooked through now.",
        "Brown the mushrooms and onion properly, then dust with flour and add broth.",
        "Simmer to thicken, then stir in the sour cream OFF the heat with the Dijon. Boiled sour cream curdles.",
        "Return the beef and any resting juices and serve over the noodles.",
      ],
      storageInstructions: "Keeps 3 days; reheat gently below a simmer.",
    },

    // ---------------------------------------------------------------
    // Seafood
    // ---------------------------------------------------------------
    {
      name: "Pan-Seared Scallops with Lemon Butter",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "seafood",
      calories: 396,
      proteinG: 32,
      carbsG: 22,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk"],
      ingredients: [
        { name: "Sea scallops", quantity: 6, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Asparagus, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Pull off the small tough side muscle if it's still attached, then dry the scallops obsessively with paper towel.",
        "Get the pan properly hot before they go in, and do not move them for 2 minutes — a wet scallop or a crowded pan gives you steamed, grey scallops with no crust.",
        "Flip for 60-90 seconds more; the center should stay barely translucent.",
        "Remove, then make a pan sauce with butter, garlic, and lemon and pour it over.",
      ],
      storageInstructions: "Eat immediately. Scallops do not reheat.",
    },
    {
      name: "Fish and Chips",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 634,
      proteinG: 38,
      carbsG: 62,
      fatG: 26,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "wheat", "eggs"],
      ingredients: [
        { name: "Cod fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "All-purpose flour", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Yukon gold potato, cut into chips", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Sparkling water", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Malt vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Vegetable oil", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Capers, drained", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Parboil the chips 5 minutes, dry them completely, then roast at 425F for 25 minutes — the double cook is what makes them fluffy inside and crisp outside.",
        "Make the batter with flour and ice-cold sparkling water, mixed only until just combined. Lumps are fine; a smooth batter means overworked gluten and a heavy coating.",
        "Dredge the dried cod in dry flour first, then the batter, so it actually adheres.",
        "Fry at 350F for 6-7 minutes until deep gold, and drain on a rack, never paper.",
        "Serve with a caper mayonnaise and malt vinegar.",
      ],
      storageInstructions: "Eat immediately; battered fish never re-crisps properly.",
    },
    {
      name: "Blackened Salmon with Rice",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 542,
      proteinG: 42,
      carbsG: 44,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish"],
      ingredients: [
        { name: "Salmon fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "Smoked paprika", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Dried thyme", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cayenne pepper", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Mix the spices and coat the salmon heavily on all sides — 'blackened' refers to the toasted spice crust, not burnt fish.",
        "Heat a cast-iron pan until it's genuinely smoking and open a window; this will set off a smoke alarm otherwise.",
        "Cook 3-4 minutes per side, skin-side down first.",
        "Serve over rice with lemon.",
      ],
      storageInstructions: "Keeps 3 days; excellent cold flaked over salad.",
    },
    {
      name: "Shrimp Boil",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 488,
      proteinG: 38,
      carbsG: 48,
      fatG: 16,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish"],
      ingredients: [
        { name: "Shrimp, shell-on", quantity: 7, unit: "oz", section: "protein" },
        { name: "Baby potatoes", quantity: 1, unit: "cup", section: "produce" },
        { name: "Corn on the cob, halved", quantity: 1, unit: "each", section: "produce" },
        { name: "Smoked sausage, sliced", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Old Bay seasoning", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Garlic", quantity: 4, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Stagger by cooking time: potatoes 15 minutes, then sausage and corn 5 minutes, then shrimp.",
        "The shrimp need 2-3 minutes and go in LAST, with the pot then turned off. Everything in at once gives you rubber shrimp and hard potatoes.",
        "Cook shell-on — the shells season the water and protect the shrimp from overcooking.",
        "Drain, dump on a tray, and hit with more Old Bay and lemon.",
      ],
      storageInstructions: "Best immediately; keeps 2 days.",
    },
    {
      name: "Crab Cakes with Remoulade",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 470,
      proteinG: 34,
      carbsG: 34,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "wheat", "eggs", "milk"],
      ingredients: [
        { name: "Lump crab meat", quantity: 6, unit: "oz", section: "protein" },
        { name: "Panko breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Mayonnaise", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 0.5, unit: "each", section: "protein" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Old Bay seasoning", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Scallion, sliced", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Fold, don't stir. The whole point of a good crab cake is intact lumps, and mixing shreds them.",
        "Use the absolute minimum binder that holds a cake together — most bad crab cakes are breadcrumb patties with crab in them.",
        "Chill the formed cakes 30 minutes so they don't collapse in the pan.",
        "Pan-fry in butter 4-5 minutes per side, flipping once only.",
        "Stir remaining mayonnaise with Dijon, lemon, and scallion for the remoulade.",
      ],
      storageInstructions: "Keeps 2 days; re-crisp in a pan rather than a microwave.",
    },
    {
      name: "Garlic Butter Baked Tilapia",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 442,
      proteinG: 40,
      carbsG: 30,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "milk"],
      ingredients: [
        { name: "Tilapia fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Green beans, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Start the potatoes at 425F for 15 minutes before the fish goes in — tilapia needs 12 minutes and potatoes need 30.",
        "Add the fish and green beans to the same tray, top with garlic butter, and bake 12 more minutes.",
        "Tilapia is done when it flakes with gentle pressure and turns opaque. It is a thin fillet and goes from done to dry in about 2 minutes.",
        "Finish with lemon and parsley.",
      ],
      storageInstructions: "Keeps 2 days; lean white fish reheats poorly.",
    },
    {
      name: "Cedar Plank Salmon",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 520,
      proteinG: 42,
      carbsG: 34,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 60,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish"],
      ingredients: [
        { name: "Salmon fillet, skin on", quantity: 6, unit: "oz", section: "protein" },
        { name: "Dijon mustard", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Asparagus, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Soak the cedar plank in water at least an hour — an unsoaked plank catches fire rather than smouldering.",
        "Whisk Dijon and maple syrup and brush over the salmon.",
        "Set the plank over medium grill heat, close the lid, and cook 15-20 minutes. Do not flip the fish; the plank does the work.",
        "The fish is done at 125-130F for medium; carryover heat takes it the rest of the way while it rests.",
      ],
      storageInstructions: "Keeps 3 days and is excellent cold.",
    },
    {
      name: "Shrimp and Grits",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 534,
      proteinG: 36,
      carbsG: 48,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Stone-ground grits", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Sharp cheddar cheese, grated", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Bacon", quantity: 1, unit: "slice", section: "protein" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Cook the grits in broth rather than water, whisking often, for a full 25 minutes. Instant grits are the difference between this dish being worth making and not.",
        "Stir in cheddar and butter at the end.",
        "Render the bacon, sear the shrimp in the fat 90 seconds per side, and deglaze with lemon juice.",
        "Spoon the shrimp and pan juices over the grits with scallion and crumbled bacon.",
      ],
      storageInstructions: "Grits set solid when chilled; reheat with extra broth, whisking.",
    },
    {
      name: "Seared Ahi Tuna with Sesame",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "seafood",
      calories: 458,
      proteinG: 44,
      carbsG: 30,
      fatG: 18,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 5,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "sesame", "soybeans", "wheat"],
      ingredients: [
        { name: "Ahi tuna steak", quantity: 6, unit: "oz", section: "protein" },
        { name: "Sesame seeds", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Cucumber, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Buy tuna sold for raw consumption; the center of this stays raw by design.",
        "Press sesame seeds onto all sides of the dry tuna steak.",
        "Sear in a screaming hot pan 45-60 seconds per side. Any longer and you've made an expensive piece of cooked tuna, which is a different and worse dish.",
        "Rest 2 minutes, then slice thin against the grain with a very sharp knife.",
        "Serve over rice with soy, ginger, sesame oil, and cucumber.",
      ],
      storageInstructions: "Eat the day it's made.",
    },
    {
      name: "Baked Halibut with Herb Crust",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "seafood",
      calories: 460,
      proteinG: 42,
      carbsG: 28,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 18,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "wheat", "milk"],
      ingredients: [
        { name: "Halibut fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "Panko breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Cherry tomatoes", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Mix panko, Parmesan, parsley, lemon zest, garlic, and olive oil into a damp crumb.",
        "Press onto the top of the halibut only — crusting all sides means the bottom steams and falls off.",
        "Bake at 400F for 15-18 minutes with the tomatoes alongside.",
        "Halibut is lean and expensive and unforgiving: pull it at 130F internal. Overcooked halibut is chalky and there's no saving it.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Mussels in White Wine Broth",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "seafood",
      calories: 400,
      proteinG: 34,
      carbsG: 30,
      fatG: 16,
      fiberG: 3,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "wheat", "milk"],
      ingredients: [
        { name: "Mussels, cleaned", quantity: 12, unit: "oz", section: "protein" },
        { name: "Dry white wine", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Shallot, minced", quantity: 1, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Crusty bread", quantity: 1.5, unit: "oz", section: "bakery" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Scrub the mussels and pull off any beards. Discard any that are cracked, or that stay open when tapped — those are dead.",
        "Soften shallot and garlic in butter, add wine, and bring to a hard boil.",
        "Add mussels, cover, and steam 5-6 minutes, shaking the pot once.",
        "They're done the moment they open. Discard any that stay shut, and don't keep cooking to force them.",
        "Serve with bread for the broth, which is the best part.",
      ],
      storageInstructions: "Eat immediately; do not store cooked mussels.",
    },
    {
      name: "Grilled Swordfish with Salsa Verde",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "seafood",
      calories: 462,
      proteinG: 44,
      carbsG: 22,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish"],
      ingredients: [
        { name: "Swordfish steak", quantity: 6, unit: "oz", section: "protein" },
        { name: "Fresh parsley", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Capers, drained", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic", quantity: 1, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Zucchini, sliced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red wine vinegar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Chop the parsley, capers, and garlic by hand and stir with oil, lemon, and vinegar — a blender turns salsa verde into a dull green sludge.",
        "Oil the swordfish and grill over high heat 4-5 minutes per side.",
        "Swordfish is meaty and holds up to a grill, but it's lean: pull it while the center is barely opaque.",
        "Spoon the salsa verde over the rested fish and grilled zucchini.",
      ],
      storageInstructions: "Salsa verde keeps 4 days; fish is best fresh.",
    },
    {
      name: "Coconut Shrimp with Mango Salsa",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "seafood",
      calories: 516,
      proteinG: 34,
      carbsG: 50,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "wheat", "eggs"],
      ingredients: [
        { name: "Shrimp, peeled, tails on", quantity: 6, unit: "oz", section: "protein" },
        { name: "Shredded unsweetened coconut", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Panko breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "All-purpose flour", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Mango, diced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Red onion, minced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Set up three bowls: flour, beaten egg, then coconut mixed with panko.",
        "Keep one hand for dry and one for wet, or you'll build breading on your fingers instead of the shrimp.",
        "Bake at 425F on a rack for 12 minutes, or shallow fry 2 minutes per side. Coconut burns fast — watch it closely.",
        "Toss mango, red onion, lime, and cilantro for the salsa.",
      ],
      storageInstructions: "Best fresh; salsa keeps 2 days.",
    },
    {
      name: "Salmon Cakes with Dill Sauce",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 460,
      proteinG: 38,
      carbsG: 32,
      fatG: 20,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "wheat", "eggs", "milk"],
      ingredients: [
        { name: "Canned salmon, drained", quantity: 6, unit: "oz", section: "protein" },
        { name: "Panko breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Fresh dill", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Drain the salmon hard and flake it, removing any large bones (the soft small ones are edible and worth keeping).",
        "Mix with panko, egg, scallion, Dijon, and half the dill.",
        "Chill the formed cakes 20 minutes so they hold in the pan.",
        "Pan-fry 4-5 minutes per side without moving them until a crust forms.",
        "Stir the yogurt with remaining dill and lemon for the sauce.",
      ],
      storageInstructions: "Keeps 3 days; sauce keeps 5.",
    },
    {
      name: "Sheet Pan Lemon Garlic Shrimp and Asparagus",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "seafood",
      calories: 418,
      proteinG: 38,
      carbsG: 26,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 7, unit: "oz", section: "protein" },
        { name: "Asparagus, trimmed", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Roast the asparagus and tomatoes at 425F for 10 minutes first.",
        "Add the shrimp with garlic butter and roast 5 minutes more — no longer.",
        "Everything on the pan from the start would mean either raw asparagus or rubber shrimp; the staggered timing is the whole trick to sheet-pan seafood.",
        "Finish with lemon juice and zest.",
      ],
      storageInstructions: "Keeps 2 days; good cold.",
    },
    {
      name: "Broiled Lobster Tail with Garlic Butter",
      mealType: "dinner",
      cuisine: "american",
      dishType: "seafood",
      calories: 430,
      proteinG: 40,
      carbsG: 18,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk"],
      ingredients: [
        { name: "Lobster tails", quantity: 8, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Asparagus, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Smoked paprika", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cut down the top of the shell with kitchen shears, stopping at the tail fan, then lift the meat out and rest it on top of the shell — this is 'piggybacking' and it's how you get an even broil.",
        "Brush generously with garlic butter and paprika.",
        "Broil 6 inches from the element for 8-10 minutes depending on size.",
        "Lobster is done at 140F and turns to rubber within a minute past that. Watch it, don't time it blindly.",
      ],
      storageInstructions: "Eat immediately.",
    },
  ],
};
