import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 1 of 4 (2026-08-16) — handhelds.
 *
 * Unlike every prior batch, this one is NOT cuisine-balanced. The library
 * had ~34 recipes in each of 8 cuisines, which reads as even coverage but
 * left the forms Americans actually eat most nearly empty: 0 burgers, 1
 * sandwich, 2 pizzas, 2 burritos across 270 recipes. This batch fills
 * those four buckets specifically, which is why it skews American — the
 * goal is "the dishes people search for," not parity between cuisines.
 *
 * Macros are the source of truth and satisfy calories = 4p + 4c + 9f
 * exactly; validate-spec.ts allows ±max(50, 15%) but there's no reason to
 * spend that budget on arithmetic drift.
 *
 * Allergen tagging is deliberately generous rather than minimal — mayo is
 * tagged `eggs` and brioche `wheat` even where validate-spec's keyword
 * list wouldn't catch them, since a missed allergen is a safety problem
 * and an extra one only costs a filter hit.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Burgers (bucket was empty)
    // ---------------------------------------------------------------
    {
      name: "Classic Cheeseburger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 530,
      proteinG: 38,
      carbsG: 36,
      fatG: 26,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cheddar cheese", quantity: 1, unit: "slice", section: "dairy" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Tomato", quantity: 2, unit: "slice", section: "produce" },
        { name: "Red onion", quantity: 2, unit: "slice", section: "produce" },
        { name: "Ketchup", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yellow mustard", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Form the beef into a patty slightly wider than the bun and press a shallow dimple into the center so it stays flat as it cooks.",
        "Season both sides generously with salt and pepper right before cooking, not earlier.",
        "Sear in a hot cast-iron skillet 3-4 minutes per side for medium, adding the cheese in the last minute and covering to melt.",
        "Toast the cut sides of the bun in the same pan.",
        "Build with lettuce, tomato, onion, and condiments, and let the patty rest 2 minutes before assembling so it doesn't soak the bun.",
      ],
      storageInstructions: "Best eaten immediately; cooked patties keep 3 days refrigerated, reheated in a dry pan.",
    },
    {
      name: "Turkey Burger with Avocado",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 494,
      proteinG: 40,
      carbsG: 34,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Ground turkey (93% lean)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Tomato", quantity: 2, unit: "slice", section: "produce" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Garlic powder", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Mix the turkey with smoked paprika, garlic powder, salt, and pepper, handling it as little as possible.",
        "Form into a patty and chill 10 minutes — lean turkey holds together far better cold.",
        "Cook 5-6 minutes per side over medium heat until cooked through to 165F.",
        "Toast the bun, mash the avocado onto the bottom half, and build with lettuce and tomato.",
      ],
      storageInstructions: "Cooked patties keep 3 days refrigerated; slice avocado fresh each time.",
    },
    {
      name: "Black Bean Burger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 446,
      proteinG: 22,
      carbsG: 58,
      fatG: 14,
      fiberG: 16,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Canned black beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Cooked brown rice", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Oat flour", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Salsa", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Pat the beans very dry, then mash about two-thirds of them, leaving the rest whole for texture.",
        "Fold in the rice, oat flour, cumin, and paprika, and season well.",
        "Form a patty and refrigerate at least 15 minutes so it holds together in the pan.",
        "Pan-fry in olive oil 5-6 minutes per side until a firm crust forms — resist flipping early.",
        "Serve on the toasted bun with salsa and lettuce.",
      ],
      storageInstructions: "Uncooked patties freeze well for 2 months, separated by parchment.",
    },
    {
      name: "Bacon Cheeseburger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 614,
      proteinG: 42,
      carbsG: 35,
      fatG: 34,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cheddar cheese", quantity: 1, unit: "slice", section: "dairy" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Tomato", quantity: 2, unit: "slice", section: "produce" },
      ],
      instructions: [
        "Cook the bacon in a cold skillet brought slowly to medium — it renders more evenly than starting hot. Set aside and pour off most of the fat.",
        "Form and season the patty, then sear in the same pan 3-4 minutes per side.",
        "Add cheese in the final minute and cover to melt.",
        "Toast the bun in the residual bacon fat and build with bacon, lettuce, and tomato.",
      ],
      storageInstructions: "Best fresh; cook bacon ahead and refrigerate up to 5 days.",
    },
    {
      name: "Mushroom Swiss Burger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 539,
      proteinG: 40,
      carbsG: 34,
      fatG: 27,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 18,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cremini mushrooms, sliced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Swiss cheese", quantity: 1, unit: "slice", section: "dairy" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
        { name: "Fresh thyme", quantity: 0.5, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Cook the mushrooms in butter over medium-high heat without stirring for the first 3 minutes so they brown rather than steam.",
        "Add thyme and a pinch of salt once they've released and reabsorbed their liquid; set aside.",
        "Sear the seasoned patty 3-4 minutes per side.",
        "Top with mushrooms and Swiss, cover 1 minute to melt, and serve on the toasted bun.",
      ],
      storageInstructions: "Mushrooms keep 4 days refrigerated and reheat well.",
    },
    {
      name: "BBQ Bacon Burger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 610,
      proteinG: 41,
      carbsG: 44,
      fatG: 30,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Barbecue sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Cheddar cheese", quantity: 1, unit: "slice", section: "dairy" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Red onion", quantity: 2, unit: "slice", section: "produce" },
      ],
      instructions: [
        "Render the bacon slowly from a cold pan; reserve.",
        "Sear the seasoned patty 3-4 minutes per side, brushing barbecue sauce on during the final minute so it glazes rather than burns.",
        "Melt the cheddar over the top under a lid.",
        "Build on the toasted bun with bacon and raw red onion for bite against the sweet sauce.",
      ],
      storageInstructions: "Best fresh; sauce and bacon can be prepped days ahead.",
    },
    {
      name: "Buffalo Chicken Burger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 480,
      proteinG: 42,
      carbsG: 33,
      fatG: 20,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Ground chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Buffalo hot sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Blue cheese crumbles", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Celery, thinly sliced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Season and form the ground chicken into a patty; chill briefly so it holds.",
        "Cook 5-6 minutes per side over medium until 165F.",
        "Toss the cooked patty in buffalo sauce off the heat.",
        "Serve on the toasted bun with blue cheese and the sliced celery, which does the cooling job a dressing usually would.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; sauce separately to avoid a soggy bun.",
    },
    {
      name: "Salmon Burger with Dill Yogurt",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 470,
      proteinG: 36,
      carbsG: 32,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "milk", "wheat"],
      ingredients: [
        { name: "Salmon fillet, skin removed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Red onion", quantity: 2, unit: "slice", section: "produce" },
      ],
      instructions: [
        "Chop the salmon by hand into a coarse mince — a food processor turns it to paste and the patty goes rubbery.",
        "Mix with Dijon, salt, and pepper, then form a patty and chill 15 minutes.",
        "Sear 4 minutes per side over medium-high; the center should stay just slightly translucent.",
        "Stir the yogurt with dill and lemon juice, and build on the toasted bun with red onion.",
      ],
      storageInstructions: "Eat the day it's cooked; the yogurt sauce keeps 4 days.",
    },
    {
      name: "Portobello Mushroom Burger",
      mealType: "lunch",
      cuisine: "american",
      dishType: "burger",
      calories: 368,
      proteinG: 16,
      carbsG: 40,
      fatG: 16,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Portobello mushroom cap", quantity: 1, unit: "each", section: "produce" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Fresh mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Roasted red pepper", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Arugula", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Scrape the dark gills from the underside of the cap — they release a lot of dark liquid otherwise.",
        "Marinate 10 minutes in balsamic, olive oil, salt, and pepper.",
        "Grill or pan-sear gill-side up first, 5 minutes per side, so the released juices don't pool in the cap.",
        "Melt the mozzarella over the cap, then build with roasted pepper and arugula.",
      ],
      storageInstructions: "Marinate up to a day ahead; cooked caps keep 3 days.",
    },
    {
      name: "Green Chile Cheeseburger",
      mealType: "dinner",
      cuisine: "american",
      dishType: "burger",
      calories: 556,
      proteinG: 40,
      carbsG: 36,
      fatG: 28,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Roasted green chiles, chopped", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Monterey Jack cheese", quantity: 1, unit: "slice", section: "dairy" },
        { name: "Whole wheat burger bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Ground cumin", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Season the beef with cumin, salt, and pepper and form into a patty.",
        "Sear 3-4 minutes per side in a hot skillet.",
        "Pile the green chiles on top, cover with the Jack cheese, and cover the pan 1 minute to melt.",
        "Serve on the toasted bun — no lettuce or tomato, which only mute the chile.",
      ],
      storageInstructions: "Roasted chiles keep a week refrigerated and freeze for months.",
    },

    // ---------------------------------------------------------------
    // Sandwiches (bucket had 1)
    // ---------------------------------------------------------------
    {
      name: "Classic BLT",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 432,
      proteinG: 20,
      carbsG: 34,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: [],
      allergens: ["eggs", "wheat"],
      ingredients: [
        { name: "Bacon", quantity: 3, unit: "slice", section: "protein" },
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Tomato", quantity: 3, unit: "slice", section: "produce" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Render the bacon from a cold pan to crisp evenly, then drain on paper towel.",
        "Toast the bread — untoasted bread collapses under tomato juice.",
        "Salt the tomato slices and let them sit 2 minutes, then blot; this seasons them and keeps the sandwich from going watery.",
        "Spread mayonnaise edge to edge on both slices, layer lettuce, tomato, then bacon, and cut on the diagonal.",
      ],
      storageInstructions: "Assemble to order; cooked bacon keeps 5 days refrigerated.",
    },
    {
      name: "Turkey Club Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 508,
      proteinG: 42,
      carbsG: 40,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "wheat"],
      ingredients: [
        { name: "Roasted turkey breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Whole wheat bread", quantity: 3, unit: "slice", section: "bakery" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
        { name: "Tomato", quantity: 3, unit: "slice", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Toast all three slices of bread and cook the bacon until crisp.",
        "Spread mayonnaise on the facing sides of each layer.",
        "Build the first tier with turkey and lettuce, add the middle slice, then bacon and tomato on the second tier.",
        "Skewer with picks at four points before cutting into quarters, or the whole thing slides apart.",
      ],
      storageInstructions: "Assemble fresh; components keep 3-4 days separately.",
    },
    {
      name: "Classic Grilled Cheese",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 474,
      proteinG: 24,
      carbsG: 36,
      fatG: 26,
      fiberG: 3,
      prepMinutes: 5,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Sourdough bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Sharp cheddar cheese", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
      ],
      instructions: [
        "Grate the cheese rather than slicing it — grated cheese melts before the bread over-browns.",
        "Butter the outside faces of both slices, right to the edges.",
        "Cook covered over medium-LOW heat 3-4 minutes per side; high heat browns the crust long before the center melts.",
        "Rest 1 minute before cutting so the cheese sets enough to pull rather than run.",
      ],
      storageInstructions: "Eat immediately — this one does not keep.",
    },
    {
      name: "Tuna Salad Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 434,
      proteinG: 34,
      carbsG: 34,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "eggs", "wheat"],
      ingredients: [
        { name: "Canned tuna in water, drained", quantity: 5, unit: "oz", section: "protein" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Celery, finely diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Red onion, minced", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Lemon", quantity: 0.25, unit: "each", section: "produce" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Press the tuna firmly in the sieve to drain — excess water is what makes tuna salad loose.",
        "Flake it and fold in mayonnaise, celery, onion, lemon juice, salt, and plenty of black pepper.",
        "Chill 10 minutes if you have it; the celery and onion mellow noticeably.",
        "Spread on bread with lettuce as a barrier layer.",
      ],
      storageInstructions: "Tuna salad keeps 3 days refrigerated in a sealed container.",
    },
    {
      name: "Egg Salad Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 426,
      proteinG: 24,
      carbsG: 33,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "wheat"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh chives, chopped", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Lower the eggs into already-boiling water and cook 10 minutes, then move straight to ice water — this makes them far easier to peel than a cold-water start.",
        "Peel and chop coarsely; egg salad wants texture, not paste.",
        "Fold in mayonnaise, Dijon, chives, salt, and pepper.",
        "Pile onto bread over a lettuce leaf.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; do not freeze.",
    },
    {
      name: "Philly Cheesesteak",
      mealType: "dinner",
      cuisine: "american",
      dishType: "sandwich",
      calories: 586,
      proteinG: 42,
      carbsG: 46,
      fatG: 26,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Beef sirloin, very thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Hoagie roll", quantity: 1, unit: "each", section: "bakery" },
        { name: "Provolone cheese", quantity: 2, unit: "slice", section: "dairy" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Green bell pepper, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Freeze the sirloin 20 minutes before slicing — it's the only reliable way to get paper-thin slices at home.",
        "Cook onion and pepper in oil over medium-high until softened and browned at the edges, then push to one side of the pan.",
        "Add the beef to the clear side in a single layer and cook 2-3 minutes, chopping it with the edge of a spatula as it browns.",
        "Combine everything, lay the provolone over the top, and let it melt for a minute.",
        "Scoop directly into the split roll with the spatula.",
      ],
      storageInstructions: "Filling keeps 3 days refrigerated; toast a fresh roll when reheating.",
    },
    {
      name: "Italian Sub",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "sandwich",
      calories: 588,
      proteinG: 38,
      carbsG: 46,
      fatG: 28,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Sliced deli ham", quantity: 2, unit: "oz", section: "protein" },
        { name: "Genoa salami", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Provolone cheese", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Sub roll", quantity: 1, unit: "each", section: "bakery" },
        { name: "Shredded lettuce", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Tomato", quantity: 3, unit: "slice", section: "produce" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Dried oregano", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Split the roll without cutting all the way through so the filling stays put.",
        "Layer cheese directly against the bread on both sides — it acts as a moisture barrier against the dressing.",
        "Shingle the meats so every bite gets both, then add lettuce, tomato, and onion.",
        "Whisk oil, vinegar, and oregano and drizzle over the vegetables, not the bread.",
        "Wrap tightly and let it sit 10 minutes; a pressed sub is meaningfully better than a freshly built one.",
      ],
      storageInstructions: "Best within a few hours; wrap tightly to keep the roll from drying.",
    },
    {
      name: "Pulled Pork Sandwich",
      mealType: "dinner",
      cuisine: "american",
      dishType: "sandwich",
      calories: 488,
      proteinG: 38,
      carbsG: 48,
      fatG: 16,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 240,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Pork shoulder", quantity: 5, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole wheat sandwich bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Green cabbage, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Rub the pork with smoked paprika, brown sugar, salt, and pepper and refrigerate at least an hour, ideally overnight.",
        "Cook low and slow — 300F oven, covered, about 4 hours, until a fork twists in it with no resistance.",
        "Rest 20 minutes before pulling, then shred with two forks and toss with the rendered juices before adding sauce.",
        "Dress the cabbage with cider vinegar, salt, and pepper for a sharp slaw.",
        "Pile pork on the toasted bun and top with slaw.",
      ],
      storageInstructions: "Pulled pork keeps 4 days refrigerated and freezes 3 months in its juices.",
    },
    {
      name: "Meatball Sub",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "sandwich",
      calories: 584,
      proteinG: 40,
      carbsG: 52,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat", "eggs"],
      ingredients: [
        { name: "Ground turkey (93% lean)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 0.5, unit: "each", section: "protein" },
        { name: "Marinara sauce", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Sub roll", quantity: 1, unit: "each", section: "bakery" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Grated Parmesan", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Mix turkey, breadcrumbs, egg, Parmesan, garlic, salt, and pepper just until combined — overmixing makes meatballs dense.",
        "Roll into 5 or 6 balls and brown on all sides in a skillet.",
        "Add marinara, cover, and simmer 15 minutes until cooked through.",
        "Load into the split roll, top with mozzarella, and broil 2 minutes until bubbling and spotted brown.",
      ],
      storageInstructions: "Meatballs in sauce keep 4 days refrigerated, 3 months frozen.",
    },
    {
      name: "Chicken Salad Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 442,
      proteinG: 36,
      carbsG: 34,
      fatG: 18,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Celery, finely diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Red grapes, halved", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Green leaf lettuce", quantity: 2, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Dice the chicken rather than shredding it so the salad holds its shape in a sandwich.",
        "Fold with yogurt, Dijon, celery, grapes, salt, and pepper.",
        "Taste and adjust acid before it chills — cold mutes seasoning, so it should taste slightly sharp warm.",
        "Serve on bread over lettuce.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
    {
      name: "Cuban Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 570,
      proteinG: 40,
      carbsG: 44,
      fatG: 26,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Roast pork, sliced", quantity: 3, unit: "oz", section: "protein" },
        { name: "Sliced deli ham", quantity: 2, unit: "oz", section: "protein" },
        { name: "Swiss cheese", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Dill pickle, sliced lengthwise", quantity: 1, unit: "each", section: "produce" },
        { name: "Yellow mustard", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cuban bread", quantity: 1, unit: "each", section: "bakery" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Split the bread and spread mustard on both cut faces — no mayonnaise, no lettuce, no tomato.",
        "Layer pork, ham, Swiss, and pickles, keeping the cheese against the pork so it glues the stack.",
        "Butter the outside and press in a hot skillet under a heavy pan or foil-wrapped brick.",
        "Press 4-5 minutes per side until the bread is flattened to about half its height and deeply crisp.",
      ],
      storageInstructions: "Best fresh off the press; components keep 4 days.",
    },
    {
      name: "Reuben Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 572,
      proteinG: 38,
      carbsG: 42,
      fatG: 28,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat", "eggs"],
      ingredients: [
        { name: "Corned beef, sliced", quantity: 4, unit: "oz", section: "protein" },
        { name: "Sauerkraut, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Swiss cheese", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Rye bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Russian dressing", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Squeeze the sauerkraut dry in a towel — this is the single step that separates a good Reuben from a soggy one.",
        "Warm the sauerkraut briefly in a dry pan to drive off more moisture.",
        "Build with dressing on both slices, cheese against the bread on both sides, and corned beef and kraut in the middle.",
        "Butter the outside and griddle over medium 4-5 minutes per side until the cheese is fully melted.",
      ],
      storageInstructions: "Assemble to order; corned beef keeps 4 days refrigerated.",
    },
    {
      name: "Buffalo Chicken Sandwich",
      mealType: "lunch",
      cuisine: "american",
      dishType: "sandwich",
      calories: 490,
      proteinG: 42,
      carbsG: 40,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Buffalo hot sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole wheat sandwich bun", quantity: 1, unit: "each", section: "bakery" },
        { name: "Blue cheese dressing", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Shredded lettuce", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, thinly sliced", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Pound the chicken to an even thickness so it cooks through without drying at the thin end.",
        "Season and sear 5-6 minutes per side over medium-high until 165F.",
        "Rest 5 minutes, then toss in buffalo sauce off the heat.",
        "Build on the toasted bun with dressing, lettuce, and celery.",
      ],
      storageInstructions: "Cooked chicken keeps 4 days; sauce it just before serving.",
    },
    {
      name: "French Dip Sandwich",
      mealType: "dinner",
      cuisine: "american",
      dishType: "sandwich",
      calories: 542,
      proteinG: 42,
      carbsG: 44,
      fatG: 22,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Roast beef, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Hoagie roll", quantity: 1, unit: "each", section: "bakery" },
        { name: "Provolone cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Beef broth", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Worcestershire sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh thyme", quantity: 0.5, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Cook the onion slowly in a dry-ish pan until deeply browned, 10 minutes, scraping up the fond.",
        "Add broth, Worcestershire, and thyme and simmer 5 minutes to make the jus.",
        "Warm the beef in the jus for under a minute — any longer and it toughens.",
        "Fill the roll, melt provolone under the broiler, and serve the strained jus alongside for dipping.",
      ],
      storageInstructions: "Jus keeps 4 days refrigerated and freezes well.",
    },
    {
      name: "Caprese Chicken Ciabatta",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "sandwich",
      calories: 518,
      proteinG: 40,
      carbsG: 40,
      fatG: 22,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Fresh mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Tomato", quantity: 3, unit: "slice", section: "produce" },
        { name: "Fresh basil leaves", quantity: 6, unit: "leaf", section: "produce" },
        { name: "Ciabatta roll", quantity: 1, unit: "each", section: "bakery" },
        { name: "Balsamic glaze", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Pound the chicken thin, season, and sear 4-5 minutes per side until just cooked.",
        "Slice on the bias and layer onto the bottom half of the ciabatta.",
        "Top with mozzarella, tomato, and basil, tearing the basil rather than cutting it.",
        "Drizzle with balsamic glaze and olive oil and close; do not toast after assembling or the basil blackens.",
      ],
      storageInstructions: "Assemble fresh; cooked chicken keeps 4 days.",
    },

    // ---------------------------------------------------------------
    // Pizza (bucket had 2)
    // ---------------------------------------------------------------
    {
      name: "Classic Pepperoni Pizza",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pizza",
      calories: 594,
      proteinG: 32,
      carbsG: 58,
      fatG: 26,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: [],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Marinara sauce", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Pepperoni", quantity: 1, unit: "oz", section: "protein" },
        { name: "Dried oregano", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Heat the oven as hot as it goes with a steel or inverted sheet pan inside for at least 45 minutes — home ovens need the thermal mass.",
        "Stretch the dough by hand from the center outward, leaving the outer inch untouched for the crust.",
        "Sauce thinly, cheese lightly, then pepperoni; overloading is the most common cause of a soggy center.",
        "Bake 10-12 minutes until the crust is blistered and the pepperoni edges have cupped and crisped.",
      ],
      storageInstructions: "Reheat leftover slices in a dry skillet, covered — far better than a microwave.",
    },
    {
      name: "Margherita Pizza",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pizza",
      calories: 532,
      proteinG: 28,
      carbsG: 60,
      fatG: 20,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Canned San Marzano tomatoes, crushed", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Fresh mozzarella", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Fresh basil leaves", quantity: 8, unit: "leaf", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Crush the tomatoes by hand with salt — no cooking. A raw sauce is what distinguishes this from a generic cheese pizza.",
        "Tear the mozzarella and blot it dry; wet mozzarella floods the center.",
        "Stretch the dough, sauce sparsely, and dot with cheese, leaving gaps.",
        "Bake in the hottest possible oven 10-12 minutes, then add basil and a drizzle of olive oil after it comes out.",
      ],
      storageInstructions: "Best fresh; dough can be made 3 days ahead and cold-fermented.",
    },
    {
      name: "BBQ Chicken Pizza",
      mealType: "dinner",
      cuisine: "american",
      dishType: "pizza",
      calories: 562,
      proteinG: 38,
      carbsG: 62,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Cooked chicken breast, shredded", quantity: 4, unit: "oz", section: "protein" },
        { name: "Shredded mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Toss the shredded chicken with 1 tablespoon of the barbecue sauce so it doesn't dry out in the oven.",
        "Spread the remaining sauce over the stretched dough in place of tomato sauce.",
        "Top with mozzarella, chicken, and red onion.",
        "Bake in a very hot oven 10-12 minutes, then scatter cilantro over the top after baking.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a skillet to keep the crust crisp.",
    },
    {
      name: "Supreme Pizza",
      mealType: "dinner",
      cuisine: "american",
      dishType: "pizza",
      calories: 584,
      proteinG: 34,
      carbsG: 58,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: [],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Marinara sauce", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Italian sausage, cooked and crumbled", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Pepperoni", quantity: 0.5, unit: "oz", section: "protein" },
        { name: "Green bell pepper, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red onion, diced", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Pre-cook the sausage and dry-saute the mushrooms; raw toppings release water directly onto the crust.",
        "Stretch the dough and sauce thinly.",
        "Distribute toppings in a single layer with visible gaps — a supreme fails when it's piled.",
        "Bake in the hottest oven 12 minutes until the crust is set and browned underneath.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },
    {
      name: "White Pizza with Ricotta and Spinach",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pizza",
      calories: 544,
      proteinG: 28,
      carbsG: 54,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Ricotta cheese", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lemon zest", quantity: 0.5, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Wilt the spinach with the garlic in olive oil, then squeeze it bone dry — this is non-negotiable on a white pizza.",
        "Season the ricotta with salt, pepper, and lemon zest.",
        "Brush the stretched dough with olive oil, dot with ricotta, scatter spinach, then mozzarella.",
        "Bake 10-12 minutes until the crust browns and the ricotta sets.",
      ],
      storageInstructions: "Best fresh; the ricotta weeps slightly on reheating.",
    },
    {
      name: "Buffalo Chicken Flatbread Pizza",
      mealType: "lunch",
      cuisine: "american",
      dishType: "pizza",
      calories: 498,
      proteinG: 36,
      carbsG: 48,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Whole wheat flatbread", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cooked chicken breast, shredded", quantity: 4, unit: "oz", section: "protein" },
        { name: "Buffalo hot sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Blue cheese crumbles", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Celery, thinly sliced", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Toss the chicken in buffalo sauce.",
        "Pre-crisp the flatbread 3 minutes in a 450F oven before topping — flatbread goes limp otherwise.",
        "Top with mozzarella and chicken and bake 8 more minutes.",
        "Finish with blue cheese and raw celery after baking.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Hawaiian Pizza",
      mealType: "dinner",
      cuisine: "american",
      dishType: "pizza",
      calories: 546,
      proteinG: 32,
      carbsG: 64,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: [],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Marinara sauce", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Sliced deli ham", quantity: 2, unit: "oz", section: "protein" },
        { name: "Pineapple chunks, drained", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Shredded mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
      ],
      instructions: [
        "Pat the pineapple thoroughly dry and, if you have time, roast it 10 minutes first to concentrate it and drive off juice.",
        "Sauce and cheese the stretched dough, then add ham and pineapple.",
        "Bake in the hottest oven 10-12 minutes.",
        "Let it sit 2 minutes before slicing so the cheese sets around the toppings.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a skillet.",
    },
    {
      name: "Garden Veggie Pizza",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "pizza",
      calories: 506,
      proteinG: 26,
      carbsG: 60,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Pizza dough", quantity: 5, unit: "oz", section: "bakery" },
        { name: "Marinara sauce", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Cremini mushrooms, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red bell pepper, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Red onion, diced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Kalamata olives, sliced", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Zucchini, thinly sliced", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Salt the zucchini slices for 10 minutes and blot dry; dry-saute the mushrooms.",
        "Stretch and sauce the dough, then cheese lightly.",
        "Arrange vegetables in a single sparse layer.",
        "Bake 12 minutes in the hottest oven until the crust is browned underneath.",
      ],
      storageInstructions: "Keeps 3 days refrigerated.",
    },

    // ---------------------------------------------------------------
    // Burritos (bucket had 2)
    // ---------------------------------------------------------------
    {
      name: "Chicken Burrito",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 586,
      proteinG: 44,
      carbsG: 62,
      fatG: 18,
      fiberG: 12,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cooked brown rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Salsa", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Shredded Monterey Jack cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Season the chicken with cumin, salt, and pepper and sear over high heat until browned and cooked through.",
        "Warm the tortilla directly over a burner or in a dry pan for 15 seconds a side — a cold tortilla cracks when rolled.",
        "Stir lime juice into the rice.",
        "Lay fillings in a line slightly below center, leaving 2 inches clear at each end.",
        "Fold the sides in first, then roll tightly from the bottom, and sear the seam-side down in a dry pan to seal.",
      ],
      storageInstructions: "Wrap in foil and refrigerate up to 3 days, or freeze 2 months.",
    },
    {
      name: "Carne Asada Burrito",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 614,
      proteinG: 46,
      carbsG: 58,
      fatG: 22,
      fiberG: 10,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Flank steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Pinto beans", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Pico de gallo", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Shredded Monterey Jack cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Marinate the flank steak in lime juice, salt, and pepper for 30 minutes — longer and the acid starts to cure it.",
        "Grill or sear over the highest heat 3-4 minutes per side for medium-rare.",
        "Rest 10 minutes, then slice thinly against the grain; slicing with the grain makes flank chewy.",
        "Warm the tortilla, layer rice, beans, steak, pico, and cheese, and roll tightly.",
        "Sear the finished burrito seam-side down to seal.",
      ],
      storageInstructions: "Best fresh; cooked steak keeps 3 days.",
    },
    {
      name: "Breakfast Burrito with Sausage and Egg",
      mealType: "breakfast",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 504,
      proteinG: 32,
      carbsG: 40,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk", "wheat"],
      ingredients: [
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Turkey breakfast sausage", quantity: 2, unit: "oz", section: "protein" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Yukon gold potato, diced small", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Salsa", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Crisp the diced potato in oil over medium heat, 10 minutes, without stirring too often.",
        "Brown the sausage in the same pan and set both aside.",
        "Scramble the eggs low and slow, pulling them off while still slightly wet — they finish cooking inside the burrito.",
        "Warm the tortilla, layer everything with cheese against the hot filling so it melts, and roll tightly.",
      ],
      storageInstructions: "Wrap individually in foil and freeze up to 2 months; reheat from frozen at 350F for 25 minutes.",
    },
    {
      name: "Bean and Cheese Burrito",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 504,
      proteinG: 22,
      carbsG: 68,
      fatG: 16,
      fiberG: 14,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Refried pinto beans", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Shredded cheddar cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Cooked white rice", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Salsa", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Warm the refried beans in a pan with the cumin and a splash of water until spreadable but not runny.",
        "Warm the tortilla until pliable.",
        "Spread the beans in a band below center, add rice, cheese, and salsa.",
        "Roll tightly and toast seam-side down in a dry pan until the outside is spotted and crisp.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; freezes 2 months wrapped in foil.",
    },
    {
      name: "California Burrito",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 674,
      proteinG: 44,
      carbsG: 66,
      fatG: 26,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Flank steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Yukon gold potato, cut into fries", quantity: 1, unit: "cup", section: "produce" },
        { name: "Shredded Monterey Jack cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Guacamole", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Sour cream", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Bake the potato fries at 425F for 25 minutes until genuinely crisp — soft fries turn the burrito to mush.",
        "Sear the seasoned steak 3-4 minutes per side, rest, and slice thin against the grain.",
        "Warm the tortilla and layer steak, fries, cheese, guacamole, and sour cream.",
        "Roll tightly and sear seam-side down. Eat immediately; this one does not hold.",
      ],
      storageInstructions: "Eat immediately — the fries lose their texture within the hour.",
    },
    {
      name: "Shrimp Burrito with Chipotle Crema",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 536,
      proteinG: 38,
      carbsG: 60,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk", "wheat"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 5, unit: "oz", section: "protein" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Green cabbage, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Chipotle in adobo, minced", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Pat the shrimp very dry and sear over high heat 90 seconds per side — they overcook in under a minute past done.",
        "Stir the yogurt with chipotle and lime juice to make the crema.",
        "Toss the cabbage with lime juice and salt.",
        "Warm the tortilla, layer rice, shrimp, slaw, and crema, and roll tightly.",
      ],
      storageInstructions: "Best fresh; crema keeps 5 days refrigerated.",
    },
    {
      name: "Sweet Potato and Black Bean Burrito",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "burrito",
      calories: 478,
      proteinG: 18,
      carbsG: 70,
      fatG: 14,
      fiberG: 16,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Sweet potato, diced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Cooked brown rice", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Salsa", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Toss the sweet potato with oil, cumin, paprika, and salt and roast at 425F for 25 minutes until caramelized at the edges.",
        "Warm the beans and mash a third of them so the filling binds.",
        "Warm the tortilla until pliable.",
        "Layer rice, beans, sweet potato, avocado, and salsa, then roll tightly and sear the seam.",
      ],
      storageInstructions: "Keeps 4 days refrigerated; freezes well without the avocado.",
    },
  ],
};
