import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 2a of 4 (2026-08-16) — soups, stews, chili.
 *
 * Same non-balanced premise as batch 1 (see
 * popular-american-1-handhelds-2026-08.ts): fill the dish-type buckets
 * people actually browse for, rather than keeping cuisines even. `chili`
 * held exactly 1 recipe and `stew` 5 before this batch.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 *
 * `gluten-free` is claimed sparingly here on purpose — soy sauce, fish
 * sauce, and commercial broths routinely contain wheat, and the tag is a
 * promise rather than a hint, so it's omitted wherever a common
 * supermarket version of an ingredient would break it.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Soups
    // ---------------------------------------------------------------
    {
      name: "Chicken Noodle Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 370,
      proteinG: 32,
      carbsG: 38,
      fatG: 10,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "eggs"],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Egg noodles", quantity: 1.5, unit: "oz", section: "grains" },
        { name: "Carrot, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Bay leaf", quantity: 1, unit: "each", section: "pantry" },
      ],
      instructions: [
        "Sweat the onion, carrot, and celery in a little oil for 6-8 minutes until softened but not browned.",
        "Add broth, bay leaf, and the whole chicken thighs, and simmer 20 minutes.",
        "Pull the chicken out, shred it, and return it to the pot.",
        "Cook the noodles separately and add them to each bowl rather than the pot — noodles left in soup keep swelling and turn to mush by day two.",
        "Finish with dill off the heat and a squeeze of lemon if you have it.",
      ],
      storageInstructions: "Soup base keeps 4 days refrigerated or 3 months frozen; store noodles separately.",
    },
    {
      name: "Broccoli Cheddar Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 408,
      proteinG: 22,
      carbsG: 26,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Broccoli florets", quantity: 2, unit: "cup", section: "produce" },
        { name: "Sharp cheddar cheese, grated", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.25, unit: "each", section: "produce" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Ground nutmeg", quantity: 0.125, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the onion in butter until soft, then stir in the flour and cook 2 minutes to lose the raw taste.",
        "Whisk in the milk gradually, then the broth, and simmer until it thickens enough to coat a spoon.",
        "Add broccoli and cook just 6-8 minutes — overcooked broccoli turns the whole pot grey-green and sulfurous.",
        "Take the pot OFF the heat before adding the cheddar, stirring in handfuls. Cheese added to a boiling base splits into grainy curds.",
        "Season with nutmeg, salt, and plenty of black pepper.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; reheat gently and never boil. Does not freeze well.",
    },
    {
      name: "Tomato Basil Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 320,
      proteinG: 10,
      carbsG: 34,
      fatG: 16,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      ingredients: [
        { name: "Canned whole tomatoes", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Heavy cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Fresh basil leaves", quantity: 12, unit: "leaf", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Vegetable broth", quantity: 0.75, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Cook the onion in olive oil until genuinely soft and sweet, 10 minutes — rushing this is why most tomato soup tastes sharp.",
        "Add garlic for 30 seconds, then the tomatoes, crushing them with a spoon.",
        "Simmer 20 minutes with the broth to concentrate.",
        "Blend smooth, then stir in cream off the heat and add the basil at the very end so it stays bright rather than stewed.",
      ],
      storageInstructions: "Keeps 4 days refrigerated; freeze before adding cream.",
    },
    {
      name: "Creamy Potato Leek Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 358,
      proteinG: 12,
      carbsG: 46,
      fatG: 14,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      ingredients: [
        { name: "Yukon gold potato, diced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Leek, white and light green only", quantity: 1, unit: "each", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Vegetable broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Fresh chives, chopped", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Slice the leek and wash it in a bowl of water, lifting it out rather than pouring — grit sinks, and pouring returns it to the leek.",
        "Sweat the leek in butter over low heat 10 minutes without colouring.",
        "Add potato, broth, and thyme, and simmer 20 minutes until the potato falls apart at the edges.",
        "Blend partially, leaving some texture, then stir in the milk and finish with chives.",
      ],
      storageInstructions: "Keeps 4 days refrigerated. Blended potato soups turn gluey if over-blended, so re-blend nothing on reheating.",
    },
    {
      name: "New England Clam Chowder",
      mealType: "dinner",
      cuisine: "american",
      dishType: "soup",
      calories: 470,
      proteinG: 28,
      carbsG: 40,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "milk", "wheat"],
      ingredients: [
        { name: "Canned chopped clams with juice", quantity: 6, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 1, unit: "slice", section: "protein" },
        { name: "Yukon gold potato, diced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Whole milk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Celery, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Render the bacon, then cook onion and celery in the fat until soft.",
        "Stir in flour and cook 2 minutes, then add the clam juice and potatoes and simmer until the potatoes are tender, about 15 minutes.",
        "Add the milk and warm through without boiling.",
        "Add the clams in the last 2 minutes only — clams simmered any longer go rubbery, which is the classic chowder mistake.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; reheat gently. Do not freeze — the potatoes go grainy.",
    },
    {
      name: "Beef and Barley Soup",
      mealType: "dinner",
      cuisine: "american",
      dishType: "soup",
      calories: 428,
      proteinG: 34,
      carbsG: 46,
      fatG: 12,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 75,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Beef chuck, cubed", quantity: 4, unit: "oz", section: "protein" },
        { name: "Pearl barley", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Carrot, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Beef broth", quantity: 3, unit: "cup", section: "pantry" },
        { name: "Bay leaf", quantity: 1, unit: "each", section: "pantry" },
      ],
      instructions: [
        "Brown the beef hard in batches — crowding the pan steams it and you lose the fond that makes this soup taste like anything.",
        "Cook the vegetables in the same pot, scraping up the browned bits.",
        "Return the beef with broth and bay leaf and simmer covered 45 minutes.",
        "Add the barley and cook 30 more minutes until both the beef and barley are tender.",
        "Barley keeps absorbing liquid, so expect to loosen leftovers with broth.",
      ],
      storageInstructions: "Keeps 4 days refrigerated, 3 months frozen; thin with broth when reheating.",
    },
    {
      name: "Split Pea Soup with Ham",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 392,
      proteinG: 30,
      carbsG: 50,
      fatG: 8,
      fiberG: 18,
      prepMinutes: 10,
      cookMinutes: 75,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Dried split peas", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Diced ham", quantity: 3, unit: "oz", section: "protein" },
        { name: "Carrot, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 3, unit: "cup", section: "pantry" },
        { name: "Bay leaf", quantity: 1, unit: "each", section: "pantry" },
      ],
      instructions: [
        "Sweat the onion, carrot, and celery until soft.",
        "Add the split peas, broth, and bay leaf and simmer covered 60-75 minutes, stirring occasionally so the peas don't catch on the bottom.",
        "Add the ham in the last 15 minutes; adding it at the start makes the whole pot aggressively salty as it reduces.",
        "Season only at the end, for the same reason.",
      ],
      storageInstructions: "Keeps 4 days refrigerated and freezes 3 months. It thickens to a paste when cold — thin generously.",
    },
    {
      name: "Butternut Squash Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 334,
      proteinG: 8,
      carbsG: 44,
      fatG: 14,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Butternut squash, cubed", quantity: 2, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Vegetable broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Heavy cream", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Fresh sage", quantity: 3, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Roast the squash with olive oil and salt at 425F for 30 minutes until the edges caramelize — boiling it instead gives you a flat, watery soup.",
        "Cook the onion until soft while the squash roasts.",
        "Blend the roasted squash with the onion and broth until completely smooth.",
        "Warm through, stir in cream, and season with cinnamon, salt, and pepper. Fry the sage in a little oil for a garnish if you like.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and freezes 3 months without the cream.",
    },
    {
      name: "Corn Chowder",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 384,
      proteinG: 12,
      carbsG: 48,
      fatG: 16,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      ingredients: [
        { name: "Corn kernels", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Yukon gold potato, diced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Whole milk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Red bell pepper, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook onion and pepper in butter until soft.",
        "Add potato and broth and simmer 15 minutes until tender.",
        "Blend about a third of the pot and return it — this thickens the chowder without flour or cream.",
        "Add corn and milk and warm 5 minutes; don't boil after the milk goes in.",
      ],
      storageInstructions: "Keeps 3 days refrigerated; reheat gently.",
    },
    {
      name: "French Onion Soup",
      mealType: "dinner",
      cuisine: "american",
      dishType: "soup",
      calories: 418,
      proteinG: 24,
      carbsG: 40,
      fatG: 18,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 60,
      servings: 1,
      dietaryTags: [],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Yellow onion, thinly sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Beef broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Gruyere cheese, grated", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Crusty bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Dry sherry", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Cook the onions in butter over medium-LOW heat for a full 45 minutes, stirring every few minutes. There is no shortcut; anything faster is browned onion, not caramelized onion.",
        "Deglaze with sherry, scraping the pan hard.",
        "Add broth and thyme and simmer 15 minutes.",
        "Float the toasted bread on top, cover thickly with Gruyere, and broil until bubbling and browned in spots.",
      ],
      storageInstructions: "Soup base keeps 5 days refrigerated and freezes well; toast and cheese are assembled fresh.",
    },
    {
      name: "Chicken and Rice Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 360,
      proteinG: 32,
      carbsG: 40,
      fatG: 8,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Carrot, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, sliced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Sweat the vegetables until soft, then add broth and bring to a bare simmer.",
        "Poach the whole chicken breast in the broth 15 minutes, then shred and return.",
        "Stir in already-cooked rice at the end rather than cooking it in the pot, which would absorb most of your broth.",
        "Finish with lemon juice — rice soups taste flat without acid.",
      ],
      storageInstructions: "Keeps 4 days; store rice separately if you want it to stay distinct.",
    },
    {
      name: "Kale Minestrone",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "soup",
      calories: 362,
      proteinG: 16,
      carbsG: 52,
      fatG: 10,
      fiberG: 12,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Canned cannellini beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Small pasta shapes", quantity: 1, unit: "oz", section: "grains" },
        { name: "Lacinato kale, chopped", quantity: 2, unit: "cup", section: "produce" },
        { name: "Carrot, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Canned diced tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Vegetable broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Build a soffritto: cook carrot, celery, and onion slowly in olive oil for 10 minutes before anything else goes in.",
        "Add garlic, tomatoes, and broth and simmer 15 minutes.",
        "Add beans and kale and cook 8 minutes until the kale is tender but still dark green.",
        "Cook the pasta separately and add per bowl, or it will drink the broth overnight.",
      ],
      storageInstructions: "Keeps 4 days refrigerated; freezes 3 months without pasta.",
    },
    {
      name: "Matzo Ball Soup",
      mealType: "lunch",
      cuisine: "american",
      dishType: "soup",
      calories: 374,
      proteinG: 22,
      carbsG: 40,
      fatG: 14,
      fiberG: 4,
      prepMinutes: 20,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: [],
      allergens: ["wheat", "eggs"],
      ingredients: [
        { name: "Matzo meal", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Chicken broth", quantity: 3, unit: "cup", section: "pantry" },
        { name: "Cooked chicken, shredded", quantity: 2, unit: "oz", section: "protein" },
        { name: "Carrot, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Mix matzo meal, eggs, oil, salt, and 1 tablespoon of broth, then refrigerate the batter a full 30 minutes — unrested batter gives you dense, heavy balls.",
        "Wet your hands and roll loosely; packing them tight has the same effect.",
        "Simmer the balls gently in salted water, covered, 25 minutes. Never boil hard.",
        "Warm the broth with carrots and chicken separately and combine in the bowl so the soup stays clear.",
      ],
      storageInstructions: "Store matzo balls in the broth up to 3 days; they continue to soften.",
    },
    {
      name: "Wonton Soup",
      mealType: "lunch",
      cuisine: "chinese",
      dishType: "soup",
      calories: 346,
      proteinG: 26,
      carbsG: 38,
      fatG: 10,
      fiberG: 3,
      prepMinutes: 25,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "eggs", "soybeans", "sesame"],
      ingredients: [
        { name: "Wonton wrappers", quantity: 10, unit: "each", section: "grains" },
        { name: "Ground pork", quantity: 3, unit: "oz", section: "protein" },
        { name: "Chicken broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Baby bok choy", quantity: 1, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Mix pork with ginger, half the scallion, soy sauce, and sesame oil.",
        "Place a teaspoon of filling per wrapper, wet two edges, and fold into a triangle, pressing out all air — trapped air makes wontons burst.",
        "Simmer the wontons in water, not the broth, for 4-5 minutes, so the broth stays clear rather than cloudy with starch.",
        "Warm the broth with bok choy, then add the drained wontons and remaining scallion.",
      ],
      storageInstructions: "Freeze uncooked wontons on a tray, then bag; cook from frozen, adding 2 minutes.",
    },
    {
      name: "Avgolemono Chicken Lemon Soup",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "soup",
      calories: 380,
      proteinG: 30,
      carbsG: 38,
      fatG: 12,
      fiberG: 2,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs"],
      ingredients: [
        { name: "Chicken breast", quantity: 4, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Poach the chicken in the broth 15 minutes, then shred it and keep the broth at a bare simmer.",
        "Whisk the eggs with the lemon juice until frothy.",
        "Temper: ladle hot broth into the egg mixture in a thin stream while whisking constantly. Add at least a cup before it goes anywhere near the pot.",
        "Pour the tempered mixture back off the heat and stir until silky. If it ever boils it will scramble and cannot be rescued.",
        "Add rice, chicken, and dill.",
      ],
      storageInstructions: "Keeps 2 days; reheat very gently, never above a bare steam.",
    },
    {
      name: "Chicken Pho",
      mealType: "lunch",
      cuisine: "thai",
      dishType: "soup",
      calories: 392,
      proteinG: 32,
      carbsG: 48,
      fatG: 8,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Rice noodles", quantity: 2, unit: "oz", section: "grains" },
        { name: "Chicken broth", quantity: 3, unit: "cup", section: "pantry" },
        { name: "Fresh ginger, halved", quantity: 2, unit: "inch", section: "produce" },
        { name: "Yellow onion, halved", quantity: 1, unit: "each", section: "produce" },
        { name: "Star anise", quantity: 2, unit: "each", section: "pantry" },
        { name: "Cinnamon stick", quantity: 1, unit: "each", section: "pantry" },
        { name: "Fish sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh Thai basil", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Char the ginger and onion halves directly over a flame or under the broiler until blackened in spots — this is where pho's depth comes from, not the simmering.",
        "Toast the star anise and cinnamon in a dry pan 30 seconds until fragrant.",
        "Simmer broth with the charred aromatics and spices 40 minutes, then strain.",
        "Poach the chicken in the strained broth, slice thin, and season the broth with fish sauce.",
        "Soak the rice noodles in hot water rather than boiling, then assemble with basil and lime at the table.",
      ],
      storageInstructions: "Broth keeps 4 days refrigerated and freezes 3 months; assemble bowls fresh.",
    },
    {
      name: "Roasted Red Pepper and Tomato Soup",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "soup",
      calories: 328,
      proteinG: 10,
      carbsG: 36,
      fatG: 16,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      ingredients: [
        { name: "Red bell pepper", quantity: 2, unit: "each", section: "produce" },
        { name: "Canned whole tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Blister the peppers whole under the broiler until blackened all over, then steam them in a covered bowl 10 minutes — the skins slip off with no effort.",
        "Cook onion and garlic in olive oil until soft.",
        "Add peeled peppers, tomatoes, broth, and paprika and simmer 15 minutes.",
        "Blend smooth and swirl yogurt into each bowl rather than the pot.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and freezes 3 months.",
    },
    {
      name: "Chicken Gnocchi Soup",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "soup",
      calories: 466,
      proteinG: 30,
      carbsG: 46,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Potato gnocchi", quantity: 4, unit: "oz", section: "grains" },
        { name: "Chicken breast, diced", quantity: 4, unit: "oz", section: "protein" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Carrot, grated", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Brown the chicken and set aside.",
        "Make a light roux with butter and flour, then whisk in broth and milk and simmer until slightly thickened.",
        "Add the gnocchi and cook 3 minutes only — they're done the moment they float, and go pasty past that.",
        "Return the chicken, wilt in the spinach, and season well.",
      ],
      storageInstructions: "Best fresh; the gnocchi soften considerably by day two.",
    },
    {
      name: "Black Bean Soup",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "soup",
      calories: 376,
      proteinG: 20,
      carbsG: 56,
      fatG: 8,
      fiberG: 18,
      prepMinutes: 10,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Canned black beans, drained", quantity: 1.25, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Ground cumin", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Chipotle in adobo, minced", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Vegetable broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook onion and garlic in oil, then bloom the cumin in the hot oil for 30 seconds — dry spices added to liquid taste dusty.",
        "Add beans, chipotle, and broth and simmer 20 minutes.",
        "Blend half the pot and return it for body.",
        "Finish with lime juice and cilantro; this soup needs noticeably more acid than you'd expect.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and freezes 3 months.",
    },
    {
      name: "Classic Egg Drop Soup",
      mealType: "lunch",
      cuisine: "chinese",
      dishType: "soup",
      calories: 348,
      proteinG: 24,
      carbsG: 36,
      fatG: 12,
      fiberG: 3,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Chicken broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Cornstarch", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Soy sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Bring the broth to a simmer with ginger and soy sauce.",
        "Slurry the cornstarch with cold water and stir it in; the slight thickness is what suspends the egg ribbons instead of letting them sink.",
        "Beat the eggs well, then pour them in a thin stream while stirring the broth in one direction.",
        "Stop stirring immediately and let it sit 10 seconds — over-stirring shreds the ribbons into fragments.",
        "Serve over rice with scallion and sesame oil.",
      ],
      storageInstructions: "Best fresh; the egg toughens on reheating.",
    },

    // ---------------------------------------------------------------
    // Stews
    // ---------------------------------------------------------------
    {
      name: "Beef Stew with Root Vegetables",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 480,
      proteinG: 38,
      carbsG: 46,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 120,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Beef chuck, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yukon gold potato, chunked", quantity: 1, unit: "cup", section: "produce" },
        { name: "Carrot, chunked", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Parsnip, chunked", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Yellow onion, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Beef broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Tomato paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Bay leaf", quantity: 1, unit: "each", section: "pantry" },
      ],
      instructions: [
        "Dry the beef thoroughly, toss in seasoned flour, and brown hard in batches. Wet or crowded meat will never brown, and unbrowned stew tastes grey.",
        "Cook the tomato paste in the pot for a minute until it darkens.",
        "Deglaze with broth, scraping everything up, return the beef, and simmer covered at the barest bubble for 90 minutes.",
        "Add the root vegetables for the final 30 minutes so they hold their shape.",
        "Rest off the heat 15 minutes before serving; stew tastes better the next day for the same reason.",
      ],
      storageInstructions: "Keeps 4 days refrigerated, 3 months frozen. Genuinely better on day two.",
    },
    {
      name: "Chicken and Dumplings",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 506,
      proteinG: 36,
      carbsG: 50,
      fatG: 18,
      fiberG: 4,
      prepMinutes: 20,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "All-purpose flour", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Whole milk", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chicken broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Carrot, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, sliced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Brown the chicken, add vegetables and broth, and simmer 20 minutes, then shred the chicken back in.",
        "Stir flour, baking powder, and salt together, cut in cold butter, then add milk and mix just until it comes together — overworking makes leaden dumplings.",
        "Drop spoonfuls onto the simmering stew, leaving gaps; they double in size.",
        "Cover and steam 15 minutes WITHOUT lifting the lid. Peeking drops the steam that leavens them.",
      ],
      storageInstructions: "Keeps 3 days; the dumplings soften but stay good.",
    },
    {
      name: "Irish Lamb Stew",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 482,
      proteinG: 36,
      carbsG: 44,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 120,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Lamb shoulder, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Yukon gold potato, chunked", quantity: 1.25, unit: "cup", section: "produce" },
        { name: "Carrot, chunked", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Brown the lamb well and pour off the rendered fat — lamb throws a lot, and leaving it makes the stew greasy.",
        "Layer onion, carrot, and lamb in the pot, add broth and thyme, and simmer covered 90 minutes.",
        "Add potatoes for the last 30 minutes; some will break down and thicken the broth, which is the point.",
        "Skim the surface fat before serving and finish with parsley.",
      ],
      storageInstructions: "Keeps 4 days; skimming is easier once chilled, as the fat sets on top.",
    },
    {
      name: "Beef Bourguignon",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 478,
      proteinG: 40,
      carbsG: 30,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 25,
      cookMinutes: 150,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Beef chuck, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 1, unit: "slice", section: "protein" },
        { name: "Cremini mushrooms, quartered", quantity: 1, unit: "cup", section: "produce" },
        { name: "Pearl onions", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Carrot, chunked", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Dry red wine", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Beef broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Tomato paste", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Render the bacon, brown the beef in the fat in batches, and set both aside.",
        "Cook carrot and tomato paste, dust in the flour, then deglaze with the wine and reduce by half — unreduced wine leaves a raw, sharp edge.",
        "Return beef and bacon with broth and braise, covered, at 325F for 2 hours.",
        "Brown the mushrooms and pearl onions separately and add them for the last 20 minutes so they keep their texture.",
      ],
      storageInstructions: "Keeps 4 days and improves overnight; freezes 3 months.",
    },
    {
      name: "Chicken and Sausage Gumbo",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 500,
      proteinG: 34,
      carbsG: 46,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 75,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 3, unit: "oz", section: "protein" },
        { name: "Andouille sausage, sliced", quantity: 2, unit: "oz", section: "protein" },
        { name: "All-purpose flour", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Vegetable oil", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Green bell pepper, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
      ],
      instructions: [
        "Make the roux: equal oil and flour, stirred constantly over medium heat for 20-30 minutes until it reaches the colour of milk chocolate. Do not walk away — a burnt roux has black flecks and must be thrown out and restarted.",
        "Drop the onion, pepper, and celery straight into the hot roux; they stop the cooking and soften in the residual heat.",
        "Add broth slowly, whisking, then the chicken and sausage, and simmer 45 minutes.",
        "Serve over rice, with the rice added to the bowl rather than the pot.",
      ],
      storageInstructions: "Keeps 4 days and is better on day two; freezes 3 months.",
    },
    {
      name: "Moroccan Chickpea Tagine",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "stew",
      calories: 446,
      proteinG: 18,
      carbsG: 62,
      fatG: 14,
      fiberG: 16,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Canned chickpeas, drained", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Sweet potato, cubed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Canned diced tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Dried apricots, chopped", quantity: 3, unit: "each", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground coriander", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Bloom the cumin, coriander, and cinnamon in hot olive oil for 30 seconds before anything else.",
        "Add sweet potato, tomatoes, chickpeas, apricots, and broth.",
        "Simmer uncovered 30-35 minutes until the sweet potato is tender and the sauce has reduced and darkened.",
        "The apricots are structural, not a garnish — their sweetness is what balances the spice. Finish with cilantro.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and freezes 3 months.",
    },
    {
      name: "Hungarian Beef Goulash",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 482,
      proteinG: 38,
      carbsG: 42,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 120,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Beef chuck, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Sweet Hungarian paprika", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Yukon gold potato, chunked", quantity: 1, unit: "cup", section: "produce" },
        { name: "Beef broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Caraway seeds", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Vegetable oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cook the onions slowly until deeply soft — goulash uses roughly as much onion as meat, and they become the sauce.",
        "Take the pot OFF the heat before stirring in the paprika. Paprika scorches in seconds over direct heat and turns bitter, which ruins the dish.",
        "Return to the heat, add beef, caraway, and just enough broth to barely cover.",
        "Simmer gently 90 minutes, adding the peppers and potatoes for the final 30.",
      ],
      storageInstructions: "Keeps 4 days and improves overnight; freezes 3 months.",
    },
    {
      name: "Cioppino Seafood Stew",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "stew",
      calories: 408,
      proteinG: 40,
      carbsG: 26,
      fatG: 16,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "shellfish"],
      ingredients: [
        { name: "Cod fillet, cubed", quantity: 3, unit: "oz", section: "protein" },
        { name: "Shrimp, peeled", quantity: 2, unit: "oz", section: "protein" },
        { name: "Mussels, cleaned", quantity: 4, unit: "oz", section: "protein" },
        { name: "Canned crushed tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Dry white wine", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Fennel bulb, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Soften the fennel and garlic in olive oil with the pepper flakes.",
        "Add wine and reduce by half, then the tomatoes, and simmer 15 minutes to build the base.",
        "Add seafood in order of cooking time: mussels first, then cod after 2 minutes, then shrimp for the final 2.",
        "Everything is done the moment the mussels open. Discard any that stay shut, and stop cooking immediately — this is a 5-minute window.",
      ],
      storageInstructions: "Base keeps 3 days; add fresh seafood each time rather than reheating it.",
    },
    {
      name: "Brunswick Stew",
      mealType: "dinner",
      cuisine: "american",
      dishType: "stew",
      calories: 454,
      proteinG: 34,
      carbsG: 48,
      fatG: 14,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 60,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Cooked chicken, shredded", quantity: 3, unit: "oz", section: "protein" },
        { name: "Pulled pork", quantity: 2, unit: "oz", section: "protein" },
        { name: "Lima beans", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Yukon gold potato, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Canned crushed tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Barbecue sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Simmer tomatoes, broth, potato, and lima beans 30 minutes until the potato starts breaking down.",
        "Add the chicken, pork, and corn and cook 20 more minutes.",
        "Stir in barbecue sauce and vinegar at the end — the vinegar is what keeps a stew this sweet from being cloying.",
        "It should be thick enough that a spoon leaves a brief trail; keep reducing if not.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months.",
    },
    {
      name: "Pozole Rojo",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "stew",
      calories: 456,
      proteinG: 34,
      carbsG: 44,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 25,
      cookMinutes: 90,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork shoulder, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned hominy, drained", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Dried guajillo chiles", quantity: 3, unit: "each", section: "pantry" },
        { name: "Dried ancho chile", quantity: 1, unit: "each", section: "pantry" },
        { name: "Yellow onion, quartered", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic", quantity: 3, unit: "clove", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Radish, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Simmer the pork with onion and garlic in salted water 60 minutes until tender, reserving the broth.",
        "Toast the dried chiles in a dry pan 30 seconds per side until fragrant but not smoking, then soak in hot water 20 minutes.",
        "Blend the softened chiles with some soaking liquid and strain through a sieve — skipping the sieve leaves gritty skin fragments.",
        "Combine pork, broth, chile purée, and hominy and simmer 30 minutes.",
        "The raw garnishes are not optional: cabbage, radish, oregano, and lime are what make it pozole.",
      ],
      storageInstructions: "Keeps 4 days and improves overnight; freezes 3 months. Garnish fresh.",
    },

    // ---------------------------------------------------------------
    // Chili (bucket held 1)
    // ---------------------------------------------------------------
    {
      name: "Classic Beef Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 498,
      proteinG: 38,
      carbsG: 46,
      fatG: 18,
      fiberG: 14,
      prepMinutes: 15,
      cookMinutes: 60,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned kidney beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Canned crushed tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Chili powder", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Tomato paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Beef broth", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Unsweetened cocoa powder", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brown the beef hard and leave the fond in the pot.",
        "Cook the onion, then the tomato paste and dry spices, in the fat for a full minute before any liquid — this blooming step is the difference between chili and seasoned mince.",
        "Add tomatoes, broth, and beans and simmer uncovered at least 45 minutes.",
        "Stir in the cocoa near the end; it reads as depth rather than chocolate and rounds off the chili powder's edge.",
      ],
      storageInstructions: "Keeps 4 days and is markedly better on day two; freezes 3 months.",
    },
    {
      name: "White Chicken Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 448,
      proteinG: 36,
      carbsG: 40,
      fatG: 16,
      fiberG: 10,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned cannellini beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Roasted green chiles, chopped", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Sour cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cook the onion, bloom the cumin and oregano, then add chicken and broth and simmer 20 minutes.",
        "Mash a third of the beans before adding them — this thickens the chili without flour or cream.",
        "Add the green chiles and simmer 15 more minutes.",
        "Stir the sour cream in off the heat, or it will split.",
      ],
      storageInstructions: "Keeps 4 days; add sour cream per bowl if you plan to reheat.",
    },
    {
      name: "Vegetarian Three-Bean Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 442,
      proteinG: 22,
      carbsG: 66,
      fatG: 10,
      fiberG: 22,
      prepMinutes: 15,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Canned kidney beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Canned pinto beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Canned crushed tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Red bell pepper, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Chili powder", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook onion and pepper until soft and starting to brown at the edges.",
        "Bloom the chili powder and cumin in the oil for a minute.",
        "Add tomatoes and all three beans and simmer 35 minutes uncovered.",
        "Finish with cider vinegar. Meatless chili tastes hollow without an acid at the end — this single teaspoon does more than any extra spice would.",
      ],
      storageInstructions: "Keeps 5 days and freezes 3 months.",
    },
    {
      name: "Chili con Carne",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "chili",
      calories: 492,
      proteinG: 40,
      carbsG: 38,
      fatG: 20,
      fiberG: 9,
      prepMinutes: 20,
      cookMinutes: 120,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Beef chuck, cut into small cubes", quantity: 5, unit: "oz", section: "protein" },
        { name: "Dried ancho chiles", quantity: 2, unit: "each", section: "pantry" },
        { name: "Dried guajillo chiles", quantity: 2, unit: "each", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Garlic", quantity: 4, unit: "clove", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Beef broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Masa harina", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Canned pinto beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Toast the dried chiles briefly, soak in hot water 20 minutes, then blend with garlic and strain.",
        "Brown the cubed beef — cubes, not ground, is what separates this from everyday chili.",
        "Add the chile purée, cumin, and broth and simmer very gently 90 minutes until the beef shreds under a fork.",
        "Whisk masa harina with water and stir it in for the last 10 minutes to thicken and add corn flavour.",
        "Add the beans at the end only, so they don't disintegrate.",
      ],
      storageInstructions: "Keeps 4 days and is better on day two; freezes 3 months.",
    },
    {
      name: "Turkey Pumpkin Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 428,
      proteinG: 36,
      carbsG: 44,
      fatG: 12,
      fiberG: 12,
      prepMinutes: 10,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Ground turkey (93% lean)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned pumpkin purée", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Canned diced tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Chili powder", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Chicken broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brown the turkey, breaking it up well; lean turkey needs real heat to colour at all.",
        "Cook the onion, then bloom the chili powder and cinnamon.",
        "Stir in the pumpkin and cook 2 minutes before adding liquid — it tastes raw otherwise.",
        "Add tomatoes, beans, and broth and simmer 30 minutes. The pumpkin thickens it and reads as body, not squash.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months.",
    },
    {
      name: "Chipotle Sweet Potato Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 442,
      proteinG: 20,
      carbsG: 68,
      fatG: 10,
      fiberG: 18,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Sweet potato, diced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Canned black beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Chipotle in adobo, minced", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Canned diced tomatoes", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cook the onion, bloom the cumin, then add the sweet potato and coat it in the spiced oil.",
        "Add chipotle, tomatoes, and broth and simmer 25 minutes until the sweet potato is tender but still holding its shape.",
        "Add the beans for the last 10 minutes.",
        "Finish with lime juice. Sweet potato and chipotle both lean sweet-smoky, and the acid is what keeps the bowl from being one-note.",
      ],
      storageInstructions: "Keeps 5 days refrigerated; freezes 3 months.",
    },
    {
      name: "Cincinnati-Style Chili",
      mealType: "dinner",
      cuisine: "american",
      dishType: "chili",
      calories: 522,
      proteinG: 34,
      carbsG: 56,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 90,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 4, unit: "oz", section: "protein" },
        { name: "Dry spaghetti", quantity: 2, unit: "oz", section: "grains" },
        { name: "Shredded cheddar cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Canned tomato sauce", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Unsweetened cocoa powder", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Ground allspice", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Do NOT brown the beef. Simmer it raw in water, breaking it up finely — this is what gives Cincinnati chili its distinctive fine, soft texture rather than crumbles.",
        "Add tomato sauce, onion, cocoa, cinnamon, and allspice and simmer 90 minutes uncovered until thick.",
        "Finish with vinegar.",
        "Serve over spaghetti and bury it in shredded cheddar — that's 'three-way'.",
      ],
      storageInstructions: "Chili keeps 4 days and improves overnight; cook pasta fresh.",
    },
    {
      name: "Green Chili with Pork",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "chili",
      calories: 458,
      proteinG: 40,
      carbsG: 34,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 90,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork shoulder, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Tomatillos, husked", quantity: 6, unit: "each", section: "produce" },
        { name: "Roasted green chiles, chopped", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Jalapeno", quantity: 1, unit: "each", section: "produce" },
        { name: "Yellow onion, quartered", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Garlic", quantity: 3, unit: "clove", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Broil the tomatillos, jalapeno, onion, and garlic until blackened in spots, 10 minutes — raw tomatillos make a thin, sour sauce.",
        "Blend the charred vegetables into a coarse purée.",
        "Brown the pork well, then add the purée, green chiles, cumin, and broth.",
        "Simmer covered 75 minutes until the pork shreds easily, then finish with cilantro.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months.",
    },
  ],
};
