import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 3b of 4 (2026-08-16) — grilled mains and
 * breakfast forms (eggs, pancakes, oatmeal, toast).
 *
 * The breakfast buckets were the most lopsided in the library: `oatmeal`
 * held 11 recipes but 8 of them were overnight-oats variations, and
 * `toast` held 4. `pancakes` held 6, only one of which was a pancake in
 * the sense an American would mean.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Grilled mains
    // ---------------------------------------------------------------
    {
      name: "Grilled Ribeye with Herb Butter",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 686,
      proteinG: 46,
      carbsG: 28,
      fatG: 44,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Ribeye steak", quantity: 7, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Fresh rosemary", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Asparagus, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Salt the steak and leave it uncovered in the fridge for an hour if you can — a dry surface is what produces a crust.",
        "Grill over the hottest possible heat 4-5 minutes per side for medium-rare, moving it only once.",
        "Pull at 130F internal. Carryover heat adds 5 more degrees while it rests.",
        "Rest a full 10 minutes under a loose foil tent, then top with the mashed herb butter.",
        "Cutting early loses the juice onto the board, and no amount of butter fixes that.",
      ],
      storageInstructions: "Keeps 3 days; slice cold for salads rather than reheating.",
    },
    {
      name: "Grilled Chicken Breast with Chimichurri",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 500,
      proteinG: 44,
      carbsG: 26,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken breast", quantity: 6, unit: "oz", section: "protein" },
        { name: "Fresh parsley", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Fresh oregano", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Garlic", quantity: 3, unit: "clove", section: "produce" },
        { name: "Red wine vinegar", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Sweet potato, cubed", quantity: 0.75, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Brine the chicken in salted water for 20 minutes; lean breast on a grill dries out otherwise.",
        "Chop the chimichurri by hand and let it sit 30 minutes so the vinegar softens the garlic's raw bite.",
        "Grill 6 minutes per side over medium-high to 165F.",
        "Rest 5 minutes, slice, and spoon chimichurri over. Never marinate in chimichurri — the acid turns the surface mealy.",
      ],
      storageInstructions: "Chimichurri keeps a week; chicken keeps 4 days.",
    },
    {
      name: "Grilled Pork Chops with Apple Slaw",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 552,
      proteinG: 44,
      carbsG: 38,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs"],
      ingredients: [
        { name: "Bone-in pork chop", quantity: 7, unit: "oz", section: "protein" },
        { name: "Apple, julienned", quantity: 1, unit: "each", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brine the chop 30 minutes in salted water with the brown sugar — this is the single biggest factor in a pork chop not being dry.",
        "Dry thoroughly, rub with paprika, and grill 6-7 minutes per side.",
        "Pull at 145F, not the 160F older recipes call for. Slightly pink pork is both safe and the point.",
        "Rest 5 minutes while you toss the slaw.",
      ],
      storageInstructions: "Keeps 3 days; slaw is best within a day.",
    },
    {
      name: "Grilled Flank Steak with Peppers",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "grilled",
      calories: 528,
      proteinG: 46,
      carbsG: 30,
      fatG: 24,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Flank steak", quantity: 6, unit: "oz", section: "protein" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chili powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Marinate the flank in lime, cumin, and chili powder for 30 minutes to 2 hours. Past that the acid starts to cure the outside grey.",
        "Grill over very high heat 3-4 minutes per side; flank is thin and wants speed.",
        "Rest 10 minutes.",
        "Slice thinly ACROSS the grain — flank has long, obvious muscle fibres and slicing along them makes it inedibly chewy.",
      ],
      storageInstructions: "Keeps 3 days; excellent cold in salads and tacos.",
    },
    {
      name: "Grilled Lamb Chops with Mint",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 604,
      proteinG: 42,
      carbsG: 26,
      fatG: 38,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Lamb loin chops", quantity: 7, unit: "oz", section: "protein" },
        { name: "Fresh mint", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Zucchini, sliced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Rub the chops with garlic, oregano, oil, salt, and pepper and rest at room temperature 30 minutes.",
        "Grill over high heat 3-4 minutes per side for medium-rare.",
        "Stand the chops on their fat edge for a minute to render it — this step is skipped constantly and it's why lamb chops often come with a rubbery fat cap.",
        "Rest 5 minutes and finish with mint and lemon.",
      ],
      storageInstructions: "Keeps 3 days; best served warm rather than reheated hot.",
    },
    {
      name: "Grilled Chicken Shawarma Plate",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 566,
      proteinG: 44,
      carbsG: 40,
      fatG: 24,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "sesame"],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 6, unit: "oz", section: "protein" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Tahini", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground coriander", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Marinate the thighs in yogurt and spices at least 2 hours, ideally overnight. Yogurt's mild acidity tenderizes without turning the meat to mush the way lemon alone would.",
        "Grill over medium-high 8-10 minutes per side until charred at the edges.",
        "Use thighs, not breast — the fat is what lets the exterior char before the inside dries.",
        "Rest, slice, and serve over rice with a tahini-lemon sauce and cucumber.",
      ],
      storageInstructions: "Marinated raw chicken keeps 2 days; cooked keeps 4.",
    },
    {
      name: "Grilled Salmon with Dill",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 512,
      proteinG: 42,
      carbsG: 30,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "milk"],
      ingredients: [
        { name: "Salmon fillet, skin on", quantity: 6, unit: "oz", section: "protein" },
        { name: "Fresh dill", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Green beans, trimmed", quantity: 1, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Oil the fish, not the grates, and make sure the grill is fully preheated — cold grates are why salmon sticks and tears.",
        "Place skin-side down and leave it for 6 minutes without touching it. It releases on its own when the crust forms.",
        "Flip once for 3-4 minutes more, to 130F internal.",
        "Serve with a yogurt-dill sauce and lemon.",
      ],
      storageInstructions: "Keeps 3 days and is excellent cold.",
    },
    {
      name: "Grilled Turkey Burger Steak with Mushroom Gravy",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 518,
      proteinG: 44,
      carbsG: 32,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Ground turkey (93% lean)", quantity: 6, unit: "oz", section: "protein" },
        { name: "Cremini mushrooms, sliced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Beef broth", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Yukon gold potato, cubed", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Form the turkey into an oval patty and chill it — lean turkey is loose and falls apart on a hot grate otherwise.",
        "Grill 5-6 minutes per side to 165F.",
        "Brown the mushrooms and onion hard in butter, dust with flour, and add broth to make the gravy.",
        "Simmer until it coats a spoon and pour over the rested patty.",
      ],
      storageInstructions: "Keeps 3 days; gravy thickens when cold, so thin with broth.",
    },
    {
      name: "Grilled Chicken Kebabs with Vegetables",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 476,
      proteinG: 44,
      carbsG: 30,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast, cubed", quantity: 6, unit: "oz", section: "protein" },
        { name: "Red bell pepper, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Red onion, chunked", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Zucchini, thick sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cut the chicken and vegetables to the same size so they finish together.",
        "Thread chicken and vegetables on SEPARATE skewers. Mixed skewers look better and cook worse — the vegetables are always either raw or incinerated.",
        "Marinate the chicken in yogurt, lemon, and oregano 1-2 hours.",
        "Grill chicken skewers 12 minutes and vegetable skewers 8, turning every few minutes.",
      ],
      storageInstructions: "Keeps 3 days; good cold in wraps.",
    },
    {
      name: "Grilled Portobello Steaks with Balsamic",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "grilled",
      calories: 386,
      proteinG: 14,
      carbsG: 40,
      fatG: 20,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Portobello mushroom caps", quantity: 3, unit: "each", section: "produce" },
        { name: "Balsamic vinegar", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Polenta, cooked", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Scrape out the gills so the caps don't bleed dark liquid over everything.",
        "Marinate 15 minutes only — mushrooms are sponges and a long soak makes them soggy rather than flavourful.",
        "Grill gill-side up first so the juices collect rather than drip into the flames, 6 minutes, then flip for 5.",
        "Serve over soft polenta with blistered tomatoes.",
      ],
      storageInstructions: "Keeps 3 days; good sliced cold into salads.",
    },
    {
      name: "Grilled Shrimp and Chorizo Skewers",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 512,
      proteinG: 38,
      carbsG: 30,
      fatG: 26,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Spanish chorizo, sliced", quantity: 2, unit: "oz", section: "protein" },
        { name: "Red bell pepper, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Cooked white rice", quantity: 0.33, unit: "cup", section: "grains" },
      ],
      instructions: [
        "Alternate shrimp and chorizo on the skewer — the chorizo renders its paprika-red fat directly onto the shrimp, which is the entire idea.",
        "Use cured Spanish chorizo, not fresh Mexican chorizo, which will fall apart.",
        "Grill 3 minutes per side over high heat, no more.",
        "Squeeze lemon over immediately and finish with parsley.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Grilled Sirloin with Garlic Mushrooms",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 574,
      proteinG: 48,
      carbsG: 30,
      fatG: 28,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 18,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Sirloin steak", quantity: 7, unit: "oz", section: "protein" },
        { name: "Cremini mushrooms, halved", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Dry-brine the sirloin with salt 40 minutes ahead. Under 15 minutes or over 40 both leave the surface wet, which is the one thing you can't grill through.",
        "Grill 4-5 minutes per side to 130F for medium-rare.",
        "Cook the mushrooms in a dry pan first until browned, THEN add butter and garlic. Butter first means the mushrooms boil in it.",
        "Rest the steak 8 minutes before slicing.",
      ],
      storageInstructions: "Keeps 3 days; slice cold.",
    },
    {
      name: "Grilled Halloumi and Vegetable Platter",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 496,
      proteinG: 26,
      carbsG: 34,
      fatG: 28,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Halloumi cheese", quantity: 3.5, unit: "oz", section: "dairy" },
        { name: "Zucchini, sliced lengthwise", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper, quartered", quantity: 1, unit: "each", section: "produce" },
        { name: "Red onion, thick rings", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh mint", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Canned chickpeas, drained", quantity: 0.5, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Pat the halloumi dry and slice about half an inch thick — thinner and it goes rubbery before it marks.",
        "Grill the halloumi 2 minutes per side on clean, oiled grates. It holds its shape because of its high melting point, but it will still stick to a dirty grill.",
        "Grill the vegetables in larger pieces than feels natural so they don't fall through.",
        "Dress everything with lemon, olive oil, and mint while warm.",
      ],
      storageInstructions: "Best warm; halloumi turns squeaky and firm once cold.",
    },
    {
      name: "Grilled Chicken Thighs with Peach Glaze",
      mealType: "dinner",
      cuisine: "american",
      dishType: "grilled",
      calories: 550,
      proteinG: 42,
      carbsG: 44,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken thighs, bone-in", quantity: 7, unit: "oz", section: "protein" },
        { name: "Peach, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Simmer the peach with vinegar, Dijon, and thyme for 10 minutes and mash into a glaze.",
        "Grill the thighs skin-side down over INDIRECT heat 18 minutes so the fat renders without flare-ups.",
        "Move to direct heat and glaze only in the last 4 minutes; the fruit sugars burn fast.",
        "Cook thighs to 175F rather than 165F — the extra time breaks down connective tissue and they get more tender, not less.",
      ],
      storageInstructions: "Keeps 4 days; glaze keeps a week.",
    },
    {
      name: "Grilled Swordfish Kebabs",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "grilled",
      calories: 486,
      proteinG: 44,
      carbsG: 28,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish"],
      ingredients: [
        { name: "Swordfish, cubed", quantity: 6, unit: "oz", section: "protein" },
        { name: "Cherry tomatoes", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Red onion, chunked", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Bay leaf", quantity: 3, unit: "each", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.33, unit: "cup", section: "grains" },
      ],
      instructions: [
        "Swordfish is the right fish for skewers — dense enough that it won't disintegrate the way cod or snapper would.",
        "Marinate in lemon, oil, and oregano 20 minutes maximum; citrus starts cooking fish chemically past that.",
        "Thread with bay leaves between the cubes for aroma.",
        "Grill 3 minutes per side over high heat. The fish should just barely lose its translucency in the center.",
      ],
      storageInstructions: "Keeps 2 days; good cold over salad.",
    },
    {
      name: "Grilled Steak Fajita Platter",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "grilled",
      calories: 592,
      proteinG: 46,
      carbsG: 42,
      fatG: 26,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Skirt steak", quantity: 6, unit: "oz", section: "protein" },
        { name: "Green bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Red bell pepper, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Sour cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Skirt steak has an even more pronounced grain than flank, and slicing it correctly matters more than how you cook it.",
        "Marinate in lime and cumin 30 minutes.",
        "Grill 2-3 minutes per side over the highest heat available — skirt is thin and wants to be seared and off.",
        "Char the peppers and onion in a grill basket until blackened at the edges.",
        "Rest 10 minutes, slice thin across the grain, and serve with rice and sour cream.",
      ],
      storageInstructions: "Keeps 3 days; slice only what you'll eat.",
    },

    // ---------------------------------------------------------------
    // Eggs
    // ---------------------------------------------------------------
    {
      name: "Classic French Omelette",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 386,
      proteinG: 24,
      carbsG: 6,
      fatG: 30,
      fiberG: 1,
      prepMinutes: 5,
      cookMinutes: 5,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Gruyere cheese, grated", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Fresh chives, chopped", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Beat the eggs until completely homogeneous with no streaks of white — visible white is the mark of a rushed omelette.",
        "Melt butter over medium-LOW heat and pour in the eggs.",
        "Stir constantly with a spatula while shaking the pan for about 45 seconds, until it looks like very soft scrambled eggs.",
        "Stop stirring, smooth the top, add cheese, and let it set 20 seconds.",
        "Roll it out of the pan onto a plate. A French omelette should be pale yellow with no browning at all — brown means the heat was too high.",
      ],
      storageInstructions: "Eat immediately.",
    },
    {
      name: "Eggs Benedict",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 596,
      proteinG: 30,
      carbsG: 32,
      fatG: 38,
      fiberG: 3,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk", "wheat"],
      ingredients: [
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Egg yolks", quantity: 2, unit: "each", section: "protein" },
        { name: "English muffin", quantity: 1, unit: "each", section: "bakery" },
        { name: "Canadian bacon", quantity: 2, unit: "oz", section: "protein" },
        { name: "Butter", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "White vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cayenne pepper", quantity: 0.125, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Make the hollandaise first: whisk yolks and lemon over a bare simmer, then drizzle in melted butter very slowly while whisking. If it splits, whisk a fresh yolk in a clean bowl and add the broken sauce to it drop by drop.",
        "Bring water to a bare tremble — not a boil — and add the vinegar.",
        "Crack each egg into a small bowl first, then slide it in. Poach 3 minutes for a runny yolk.",
        "Toast the muffin, warm the bacon, and assemble immediately. Hollandaise waits for no one and holds about 30 minutes at most.",
      ],
      storageInstructions: "Eat immediately; hollandaise cannot be refrigerated and reheated.",
    },
    {
      name: "Denver Omelette",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 448,
      proteinG: 32,
      carbsG: 14,
      fatG: 30,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Diced ham", quantity: 2, unit: "oz", section: "protein" },
        { name: "Green bell pepper, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.25, unit: "each", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
      ],
      instructions: [
        "Cook the pepper, onion, and ham FIRST and set them aside. Raw vegetables added to eggs release water and make the omelette weep.",
        "Beat the eggs and cook over medium heat, pulling the set edges toward the center and tilting to fill the gaps.",
        "When the top is just barely wet, add the filling and cheese to one half.",
        "Fold and slide out. Residual heat finishes the center.",
      ],
      storageInstructions: "Best fresh; keeps 1 day.",
    },
    {
      name: "Soft Scrambled Eggs with Chives",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 372,
      proteinG: 24,
      carbsG: 8,
      fatG: 28,
      fiberG: 1,
      prepMinutes: 5,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Heavy cream", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Fresh chives, chopped", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Beat the eggs with the cream but do NOT salt them yet — salt added early breaks down the proteins and makes scrambled eggs watery.",
        "Cook over low heat, stirring constantly with a spatula, scraping the bottom every few seconds.",
        "This takes 6-8 minutes. Rushing over high heat gives you dry curds in 90 seconds instead.",
        "Pull the pan off while they still look slightly underdone, then salt and add chives — they keep cooking on the plate.",
      ],
      storageInstructions: "Eat immediately.",
    },
    {
      name: "Sausage and Cheese Egg Muffins",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 396,
      proteinG: 32,
      carbsG: 10,
      fatG: 25,
      fiberG: 2,
      prepMinutes: 15,
      cookMinutes: 22,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Turkey breakfast sausage", quantity: 2, unit: "oz", section: "protein" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Red bell pepper, diced", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Baby spinach, chopped", quantity: 1, unit: "cup", section: "produce" },
        { name: "Whole milk", quantity: 2, unit: "tbsp", section: "dairy" },
      ],
      instructions: [
        "Cook the sausage and wilt the spinach, then squeeze the spinach dry.",
        "Whisk eggs with milk and season well.",
        "Fill greased muffin cups two-thirds full — they puff dramatically and then sink, which is normal.",
        "Bake at 350F for 20-22 minutes until just set. Overbaking makes them spongy and weepy on reheating.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and freezes 2 months; reheat 30 seconds.",
    },
    {
      name: "Cheesy Baked Eggs with Spinach",
      mealType: "breakfast",
      cuisine: "mediterranean",
      dishType: "eggs",
      calories: 424,
      proteinG: 28,
      carbsG: 14,
      fatG: 28,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Baby spinach", quantity: 3, unit: "cup", section: "produce" },
        { name: "Feta cheese, crumbled", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Heavy cream", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Wilt the spinach with garlic and squeeze out every bit of water.",
        "Spread in a small baking dish with the cream, and make three wells with the back of a spoon.",
        "Crack an egg into each well and scatter feta around them, not on top of the yolks.",
        "Bake at 400F for 12-14 minutes until the whites are set but the yolks still jiggle.",
      ],
      storageInstructions: "Best fresh; the yolks set fully on reheating.",
    },
    {
      name: "Egg White Veggie Scramble",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 262,
      proteinG: 30,
      carbsG: 18,
      fatG: 8,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Egg whites", quantity: 1, unit: "cup", section: "protein" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Feta cheese, crumbled", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the mushrooms until browned and the moisture has gone — egg whites are watery enough already.",
        "Wilt the spinach and drain off any liquid.",
        "Add the whites over low heat and stir gently; whites toughen far faster than whole eggs.",
        "Pull them while glossy and fold in feta and tomatoes off the heat.",
      ],
      storageInstructions: "Best fresh; keeps 1 day.",
    },
    {
      name: "Bacon and Potato Breakfast Hash with Eggs",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 566,
      proteinG: 26,
      carbsG: 42,
      fatG: 32,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs"],
      ingredients: [
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Yukon gold potato, diced small", quantity: 1.25, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Red bell pepper, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Render the bacon and reserve the fat.",
        "Add the potatoes in a single layer and DON'T STIR for 5 full minutes. Constant stirring is why most home hash is pale and soft rather than crusty.",
        "Stir once, add onion and pepper, and repeat for another 10 minutes.",
        "Make two wells, crack in the eggs, cover, and cook 3-4 minutes until the whites set.",
      ],
      storageInstructions: "Hash keeps 3 days; add fresh eggs each time.",
    },
    {
      name: "Poached Eggs with Smoked Salmon",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "eggs",
      calories: 440,
      proteinG: 32,
      carbsG: 26,
      fatG: 24,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["eggs", "fish", "milk", "wheat"],
      ingredients: [
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Smoked salmon", quantity: 2.5, unit: "oz", section: "protein" },
        { name: "Whole wheat bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Cream cheese", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Red onion, thinly sliced", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Capers, drained", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "White vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Use the freshest eggs you can. Older whites spread into wisps no matter how good your technique is.",
        "Bring water to a bare tremble with the vinegar, and stir a gentle whirlpool before sliding each egg in.",
        "Poach 3 minutes and lift out with a slotted spoon onto paper towel to drain.",
        "Build on toast with cream cheese, salmon, onion, capers, and dill.",
      ],
      storageInstructions: "Eat immediately.",
    },
    {
      name: "Green Chile Egg Casserole Cups",
      mealType: "breakfast",
      cuisine: "mexican",
      dishType: "eggs",
      calories: 384,
      proteinG: 28,
      carbsG: 16,
      fatG: 24,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 22,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Roasted green chiles, chopped", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Shredded Monterey Jack cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Drain the green chiles well; canned chiles carry a lot of liquid that will pool in the cups.",
        "Whisk eggs with milk, cumin, salt, and pepper.",
        "Divide chiles, cheese, and scallion between greased muffin cups, then pour the egg over.",
        "Bake at 350F for 20 minutes until puffed and just set, and finish with cilantro.",
      ],
      storageInstructions: "Keeps 5 days and freezes 2 months.",
    },

    // ---------------------------------------------------------------
    // Pancakes
    // ---------------------------------------------------------------
    {
      name: "Buttermilk Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 520,
      proteinG: 16,
      carbsG: 72,
      fatG: 18,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Buttermilk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Butter, melted", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Baking soda", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Whisk the dry ingredients, then add the wet and stir ONLY until the flour disappears. The batter should be lumpy — a smooth batter means developed gluten and rubbery pancakes.",
        "Rest the batter 10 minutes so the flour hydrates and the leavening starts working.",
        "Cook on a medium griddle, and flip when the bubbles on top pop and stay open, about 2-3 minutes.",
        "Flip once only. Pressing them down with the spatula deflates everything you just built.",
      ],
      storageInstructions: "Cooked pancakes freeze well; reheat in a toaster.",
    },
    {
      name: "Blueberry Buttermilk Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 546,
      proteinG: 16,
      carbsG: 80,
      fatG: 17,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Buttermilk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Blueberries", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Butter, melted", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Make the batter as usual, leaving it lumpy.",
        "Do NOT stir the blueberries into the batter — they'll break and turn the whole thing grey-purple.",
        "Ladle the batter onto the griddle, then drop blueberries onto each pancake individually.",
        "Flip once when the edges look dry, 2-3 minutes.",
      ],
      storageInstructions: "Freeze in a single layer, then bag; toast from frozen.",
    },
    {
      name: "Banana Oat Protein Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 486,
      proteinG: 34,
      carbsG: 56,
      fatG: 14,
      fiberG: 8,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein", "high-fiber"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Banana", quantity: 1, unit: "each", section: "produce" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Cottage cheese", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Blend the oats into a coarse flour first, then add everything else and blend smooth.",
        "Let the batter sit 5 minutes; it thickens noticeably as the oats absorb liquid.",
        "Cook on a medium-LOW griddle. These have no gluten structure and brown faster than they set, so lower heat and longer time is essential.",
        "Flip carefully — they're more fragile than flour pancakes.",
      ],
      storageInstructions: "Keeps 3 days; reheats well in a toaster.",
    },
    {
      name: "Belgian Waffles",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 578,
      proteinG: 16,
      carbsG: 72,
      fatG: 25,
      fiberG: 3,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Butter, melted", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Baking powder", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Cornstarch", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Separate the egg. Whip the white to soft peaks and fold it in at the end — this is what makes a waffle light rather than a thick pancake.",
        "Add the cornstarch to the flour; it lowers the protein content and gives a crisper shell.",
        "Preheat the iron fully before the batter goes in.",
        "Cook until the steam slows dramatically, about 4-5 minutes. Opening early tears the waffle in half.",
      ],
      storageInstructions: "Freeze and reheat in a toaster; they re-crisp better than pancakes.",
    },
    {
      name: "Lemon Ricotta Pancakes",
      mealType: "breakfast",
      cuisine: "italian",
      dishType: "pancakes",
      calories: 526,
      proteinG: 24,
      carbsG: 62,
      fatG: 20,
      fiberG: 3,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Ricotta cheese", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Whole milk", quantity: 0.25, unit: "cup", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Separate the eggs, whip the whites to soft peaks, and fold them in last — ricotta is heavy and the batter needs the lift.",
        "Zest the lemon directly into the sugar or flour so the oils distribute.",
        "Cook on medium-low; these are wetter than standard pancakes and need longer to set through.",
        "Make them smaller than usual, about 3 inches, so they're flippable.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Pumpkin Spice Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 512,
      proteinG: 16,
      carbsG: 74,
      fatG: 16,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Canned pumpkin purée", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Buttermilk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Ground cinnamon", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground ginger", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Use pumpkin purée, not pie filling, which is pre-sweetened and spiced.",
        "The purée makes the batter noticeably thicker — thin with extra buttermilk until it ribbons off the spoon.",
        "Cook on medium-low; pumpkin batter browns fast because of its sugars but takes longer to cook through.",
        "Give them an extra minute per side compared to plain pancakes.",
      ],
      storageInstructions: "Keeps 3 days; freezes well.",
    },
    {
      name: "Whole Wheat Banana Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 508,
      proteinG: 18,
      carbsG: 76,
      fatG: 14,
      fiberG: 9,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Whole wheat flour", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Banana, mashed", quantity: 1, unit: "each", section: "produce" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Butter, melted", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Use a properly overripe banana — brown-spotted. An underripe one adds starch and no sweetness.",
        "Whole wheat flour absorbs more liquid, so let this batter rest a full 15 minutes or the pancakes come out dense and dry.",
        "Cook on medium-low.",
        "Expect these to be heartier than white-flour pancakes; that's the trade for the fibre.",
      ],
      storageInstructions: "Keeps 3 days; freezes well.",
    },
    {
      name: "Dutch Baby Pancake",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 494,
      proteinG: 20,
      carbsG: 56,
      fatG: 20,
      fiberG: 3,
      prepMinutes: 10,
      cookMinutes: 22,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Butter", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Powdered sugar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Blueberries", quantity: 0.33, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Blend the batter until completely smooth and let it rest 20 minutes at room temperature. Cold batter will not climb the pan.",
        "Preheat a cast-iron skillet in a 425F oven with the butter until it's foaming.",
        "Pour the batter into the screaming-hot pan and return it to the oven immediately.",
        "Bake 20 minutes WITHOUT opening the door. It will climb the sides dramatically and then collapse when it comes out — that's correct.",
        "Finish with lemon, powdered sugar, and berries.",
      ],
      storageInstructions: "Eat immediately; it deflates within minutes by design.",
    },
    {
      name: "Cornmeal Johnnycakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 468,
      proteinG: 14,
      carbsG: 66,
      fatG: 16,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk", "eggs"],
      ingredients: [
        { name: "Yellow cornmeal", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Pour boiling milk over the cornmeal and let it stand 10 minutes. Scalding hydrates the cornmeal so the cakes aren't gritty.",
        "Beat in the egg and baking powder once it has cooled slightly, so the egg doesn't scramble.",
        "Fry in butter on a medium griddle, 3 minutes per side, keeping them small and thick.",
        "These are naturally gluten-free if you use certified cornmeal, though we don't tag them so because most brands share equipment with wheat.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Savory Scallion and Corn Pancakes",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "pancakes",
      calories: 452,
      proteinG: 16,
      carbsG: 62,
      fatG: 16,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "All-purpose flour", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 4, unit: "each", section: "produce" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Baking powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Char the corn in a dry pan for 3 minutes before it goes in the batter.",
        "Mix a fairly thick batter — thin batter lets the corn sink and the pancakes tear when flipped.",
        "Cook in butter over medium heat, 3 minutes per side.",
        "Season the batter properly with salt; savoury pancakes taste flat if you season them like sweet ones.",
      ],
      storageInstructions: "Keeps 2 days; reheat in a dry pan.",
    },

    // ---------------------------------------------------------------
    // Oatmeal
    // ---------------------------------------------------------------
    {
      name: "Steel-Cut Oats with Brown Sugar",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 392,
      proteinG: 14,
      carbsG: 62,
      fatG: 9,
      fiberG: 10,
      prepMinutes: 5,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Steel-cut oats", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Brown sugar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Toast the dry oats in the butter for 2 minutes until they smell nutty — this single step is the difference between good steel-cut oats and wallpaper paste.",
        "Add water and simmer 25-30 minutes, stirring occasionally.",
        "Add the milk only in the last 5 minutes; adding dairy early slows the starch from swelling properly.",
        "Finish with brown sugar and cinnamon, and salt it — unsalted oatmeal tastes like nothing.",
      ],
      storageInstructions: "Keeps 5 days; make a large batch and reheat with water.",
    },
    {
      name: "Savory Oatmeal with Egg and Scallion",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 448,
      proteinG: 24,
      carbsG: 48,
      fatG: 18,
      fiberG: 8,
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein", "high-fiber"],
      allergens: ["eggs", "milk", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Vegetable broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Soy sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
      ],
      instructions: [
        "Cook the oats in broth rather than water or milk — this is what makes savoury oatmeal read as a grain bowl rather than a mistake.",
        "Simmer 10 minutes until creamy.",
        "Stir in Parmesan, soy sauce, and sesame oil.",
        "Top with a soft-fried or jammy egg and scallion, and break the yolk into the oats.",
      ],
      storageInstructions: "Oats keep 4 days; cook the egg fresh.",
    },
    {
      name: "Apple Cinnamon Baked Oatmeal",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 466,
      proteinG: 16,
      carbsG: 70,
      fatG: 13,
      fiberG: 10,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Apple, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Baking powder", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Use rolled oats, not instant, or the texture collapses to mush in the oven.",
        "Whisk milk, egg, maple syrup, and cinnamon, then fold in oats, apple, and baking powder.",
        "Bake at 350F for 35-40 minutes until set in the middle and browned at the edges.",
        "Let it cool 10 minutes before cutting; it firms up considerably as it sets.",
      ],
      storageInstructions: "Keeps 5 days and reheats beautifully; portion and freeze 2 months.",
    },
    {
      name: "Protein Oatmeal with Berries",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 460,
      proteinG: 34,
      carbsG: 56,
      fatG: 10,
      fiberG: 10,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Vanilla whey protein powder", quantity: 1, unit: "scoop", section: "pantry" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Mixed berries", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the oats in milk and water until creamy, 8-10 minutes.",
        "Take the pan OFF the heat and let it cool for a minute before stirring in the protein powder.",
        "Whey added to boiling oats seizes into rubbery lumps — this is the single most common way this recipe goes wrong.",
        "Loosen with a splash of milk and top with berries.",
      ],
      storageInstructions: "Best fresh; protein oats stiffen considerably when chilled.",
    },
    {
      name: "Banana Nut Oatmeal",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 486,
      proteinG: 16,
      carbsG: 66,
      fatG: 18,
      fiberG: 10,
      prepMinutes: 5,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk", "tree_nuts"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Banana, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Walnuts, chopped", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Maple syrup", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Mash half the banana into the oats as they cook — it sweetens the whole pot and thickens it without more oats.",
        "Simmer 8-10 minutes with the milk and cinnamon.",
        "Toast the walnuts in a dry pan while the oats cook.",
        "Top with the remaining sliced banana and the walnuts so there's textural contrast.",
      ],
      storageInstructions: "Keeps 3 days; add nuts at serving.",
    },
    {
      name: "Coconut Mango Steel-Cut Oats",
      mealType: "breakfast",
      cuisine: "thai",
      dishType: "oatmeal",
      calories: 470,
      proteinG: 12,
      carbsG: 68,
      fatG: 16,
      fiberG: 10,
      prepMinutes: 5,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Steel-cut oats", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Light coconut milk", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Mango, diced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Shredded unsweetened coconut", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Maple syrup", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toast the oats dry for 2 minutes before adding liquid.",
        "Simmer in water 20 minutes, then add the coconut milk for the last 8.",
        "Toast the shredded coconut separately until golden.",
        "Finish with mango, toasted coconut, and a squeeze of lime — the acid is what stops this tasting like dessert.",
      ],
      storageInstructions: "Keeps 4 days; reheat with extra coconut milk.",
    },
    {
      name: "Pumpkin Pie Oatmeal",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 424,
      proteinG: 16,
      carbsG: 62,
      fatG: 12,
      fiberG: 12,
      prepMinutes: 5,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Rolled oats", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Canned pumpkin purée", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground ginger", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the oats in milk until nearly done, about 8 minutes.",
        "Stir in the pumpkin and cook 3 more minutes — adding it at the start makes the oats gluey and stops them swelling.",
        "Season with cinnamon, ginger, and a real pinch of salt.",
        "Finish with maple syrup off the heat.",
      ],
      storageInstructions: "Keeps 4 days and thickens; thin with milk.",
    },
    {
      name: "Blueberry Almond Overnight Steel-Cut Oats",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "oatmeal",
      calories: 478,
      proteinG: 16,
      carbsG: 64,
      fatG: 18,
      fiberG: 12,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["tree_nuts", "milk"],
      ingredients: [
        { name: "Steel-cut oats", quantity: 0.33, unit: "cup", section: "grains" },
        { name: "Greek yogurt", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Blueberries", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Almonds, sliced", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Maple syrup", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Steel-cut oats need a full overnight soak, not the 4 hours rolled oats want — they stay pleasantly chewy rather than going soft.",
        "Combine oats, milk, yogurt, syrup, and cinnamon in a jar and refrigerate 8-12 hours.",
        "Add blueberries in the morning rather than overnight, so they don't bleed and go grey.",
        "Top with almonds at serving so they stay crunchy.",
      ],
      storageInstructions: "Keeps 4 days; add fruit and nuts fresh each morning.",
    },

    // ---------------------------------------------------------------
    // Toast
    // ---------------------------------------------------------------
    {
      name: "Classic Avocado Toast with Egg",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "toast",
      calories: 452,
      proteinG: 20,
      carbsG: 36,
      fatG: 26,
      fiberG: 11,
      prepMinutes: 10,
      cookMinutes: 5,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "eggs"],
      ingredients: [
        { name: "Sourdough bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Avocado", quantity: 1, unit: "each", section: "produce" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toast the bread until genuinely crisp on both sides — soft toast collapses under avocado.",
        "Mash the avocado with lemon juice, flaky salt, and pepper in a bowl, not on the toast.",
        "Season it more aggressively than feels right; avocado is bland and takes a lot of salt and acid.",
        "Top with a fried or jammy egg, olive oil, and pepper flakes.",
      ],
      storageInstructions: "Assemble immediately; mashed avocado browns within an hour.",
    },
    {
      name: "Peanut Butter Banana Toast",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "toast",
      calories: 456,
      proteinG: 18,
      carbsG: 54,
      fatG: 19,
      fiberG: 8,
      prepMinutes: 5,
      cookMinutes: 3,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "peanuts"],
      ingredients: [
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Peanut butter", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Banana, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Ground cinnamon", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Honey", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toast the bread and spread the peanut butter while it's still hot so it melts into the surface.",
        "Layer banana slices in a single overlapping layer.",
        "Dust with cinnamon and drizzle honey.",
        "Use natural peanut butter and stir it thoroughly — the separated oil at the top is what keeps it spreadable.",
      ],
      storageInstructions: "Eat immediately.",
    },
    {
      name: "Smoked Salmon and Cream Cheese Toast",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "toast",
      calories: 428,
      proteinG: 26,
      carbsG: 34,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 8,
      cookMinutes: 3,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "fish", "milk"],
      ingredients: [
        { name: "Whole wheat bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Smoked salmon", quantity: 2.5, unit: "oz", section: "protein" },
        { name: "Cream cheese", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Red onion, thinly sliced", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Capers, drained", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 0.25, unit: "each", section: "produce" },
      ],
      instructions: [
        "Let the cream cheese come to room temperature so it spreads without tearing the toast.",
        "Toast the bread and cool it for a minute — hot toast melts cream cheese into a greasy layer.",
        "Drape the salmon rather than laying it flat; the folds make it far better to eat.",
        "Finish with onion, capers, dill, and a squeeze of lemon.",
      ],
      storageInstructions: "Assemble fresh.",
    },
    {
      name: "Ricotta Toast with Honey and Pistachio",
      mealType: "breakfast",
      cuisine: "italian",
      dishType: "toast",
      calories: 442,
      proteinG: 20,
      carbsG: 46,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 8,
      cookMinutes: 3,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk", "tree_nuts"],
      ingredients: [
        { name: "Sourdough bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Ricotta cheese", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Honey", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Pistachios, chopped", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Lemon zest", quantity: 0.5, unit: "tsp", section: "produce" },
        { name: "Fresh thyme", quantity: 0.5, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Whip the ricotta with a fork or briefly in a processor with a pinch of salt and the lemon zest — this turns grainy ricotta silky and is worth the extra minute.",
        "Toast the bread well.",
        "Spread thickly, then drizzle honey and scatter pistachios and thyme.",
      ],
      storageInstructions: "Whipped ricotta keeps 3 days; assemble at serving.",
    },
    {
      name: "Tomato and Burrata Toast",
      mealType: "breakfast",
      cuisine: "italian",
      dishType: "toast",
      calories: 470,
      proteinG: 22,
      carbsG: 40,
      fatG: 25,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 3,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Sourdough bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Burrata cheese", quantity: 2.5, unit: "oz", section: "dairy" },
        { name: "Cherry tomatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Fresh basil leaves", quantity: 8, unit: "leaf", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic", quantity: 1, unit: "clove", section: "produce" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toast the bread, then rub the cut side of a raw garlic clove across it while still hot — the surface acts like a grater.",
        "Toss the tomatoes with salt and a little balsamic and let them sit 10 minutes to draw out juice.",
        "Tear the burrata over the toast rather than slicing it, letting the cream run.",
        "Spoon the tomatoes and their juices over, then oil and basil.",
      ],
      storageInstructions: "Assemble immediately; burrata is best at room temperature.",
    },
    {
      name: "Hummus and Cucumber Toast",
      mealType: "breakfast",
      cuisine: "mediterranean",
      dishType: "toast",
      calories: 396,
      proteinG: 16,
      carbsG: 50,
      fatG: 15,
      fiberG: 10,
      prepMinutes: 8,
      cookMinutes: 3,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat", "sesame"],
      ingredients: [
        { name: "Whole wheat bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Hummus", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Cucumber, thinly sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Za'atar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 0.25, unit: "each", section: "produce" },
      ],
      instructions: [
        "Toast the bread until firm.",
        "Spread the hummus thickly and make a swirl in it with the back of a spoon so the oil pools.",
        "Layer cucumber and tomato, then oil, za'atar, lemon, and flaky salt.",
      ],
      storageInstructions: "Assemble fresh.",
    },
    {
      name: "Cinnamon French Toast",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "toast",
      calories: 542,
      proteinG: 22,
      carbsG: 64,
      fatG: 22,
      fiberG: 4,
      prepMinutes: 10,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "eggs", "milk"],
      ingredients: [
        { name: "Brioche bread", quantity: 2, unit: "slice", section: "bakery" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Whole milk", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Ground cinnamon", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Vanilla extract", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Maple syrup", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Use day-old or slightly stale bread cut thick. Fresh soft bread turns to mush the moment it hits the custard.",
        "Whisk eggs, milk, cinnamon, vanilla, and a pinch of salt thoroughly — streaks of unbeaten white fry into visible ribbons.",
        "Soak each slice 20-30 seconds per side, no longer.",
        "Cook in butter over medium heat 3-4 minutes per side. High heat browns the outside while the custard inside stays raw.",
      ],
      storageInstructions: "Keeps 2 days; reheat in a toaster oven.",
    },
    {
      name: "Egg in a Hole with Spinach",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "toast",
      calories: 402,
      proteinG: 22,
      carbsG: 34,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 5,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["wheat", "eggs", "milk"],
      ingredients: [
        { name: "Whole wheat bread", quantity: 1, unit: "slice", section: "bakery" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Garlic, minced", quantity: 1, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Cut a hole in the bread with a glass, and keep the round — it toasts alongside and is the best part.",
        "Butter the pan, add the bread, and crack the egg into the hole.",
        "Cook over medium-low 3 minutes until the white is mostly set, then flip carefully with a wide spatula for 1 more minute.",
        "Wilt the spinach with garlic alongside and serve under the toast with Parmesan.",
      ],
      storageInstructions: "Eat immediately.",
    },
  ],
};
