import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 2b of 4 (2026-08-16) — salads, BBQ,
 * casseroles. `bbq` held exactly 1 recipe and `casserole` 6 before this.
 *
 * Salads here are deliberately main-course sized (lunch/dinner calorie
 * ranges), not side salads. A 120-calorie bowl of leaves isn't something
 * anyone plans a meal slot around, and the meal-type calorie floors in
 * validate-spec.ts would reject it anyway.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Salads
    // ---------------------------------------------------------------
    {
      name: "Classic Caesar Salad with Chicken",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 470,
      proteinG: 42,
      carbsG: 22,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat", "eggs", "fish"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Romaine lettuce, chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Croutons", quantity: 0.33, unit: "cup", section: "bakery" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Anchovy fillets, minced", quantity: 2, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 1, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Mash the anchovies and garlic to a paste with the side of a knife — anchovy is what makes a Caesar taste like a Caesar, and left in pieces it reads as fishy rather than savoury.",
        "Whisk the paste with mayonnaise, Dijon, and lemon juice.",
        "Season and sear the chicken 5-6 minutes per side, rest, then slice.",
        "Dress the romaine in a large bowl and toss until every leaf is lightly coated, not pooled.",
        "Add Parmesan, croutons, and chicken last so they stay crisp.",
      ],
      storageInstructions: "Dressing keeps 5 days refrigerated; dress leaves only at serving time.",
    },
    {
      name: "Cobb Salad",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 560,
      proteinG: 40,
      carbsG: 20,
      fatG: 36,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 4, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Hard-boiled egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Blue cheese crumbles", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Romaine lettuce, chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Arrange the toppings in distinct stripes across the lettuce rather than tossing — a Cobb is a composed salad, and the point is choosing your own ratio per forkful.",
        "Cook the bacon crisp and chop it.",
        "Whisk vinegar and olive oil with salt and pepper and serve it alongside.",
        "Slice the avocado just before serving so it doesn't brown across the plate.",
      ],
      storageInstructions: "Prep components separately up to 3 days; assemble at serving.",
    },
    {
      name: "Buffalo Chicken Salad",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 452,
      proteinG: 44,
      carbsG: 18,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast", quantity: 6, unit: "oz", section: "protein" },
        { name: "Buffalo hot sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Romaine lettuce, chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Blue cheese dressing", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Celery, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Season and sear the chicken, rest 5 minutes, then slice and toss in buffalo sauce.",
        "Sauce the chicken AFTER resting, not before cooking — hot sauce in the pan burns and turns acrid.",
        "Build the salad and add the warm chicken on top so it slightly wilts the leaves underneath.",
        "Drizzle with blue cheese dressing.",
      ],
      storageInstructions: "Keeps 3 days with components stored separately.",
    },
    {
      name: "Southwest Chicken Salad with Avocado",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "salad",
      calories: 528,
      proteinG: 40,
      carbsG: 38,
      fatG: 24,
      fiberG: 12,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Romaine lettuce, chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Rub the chicken with cumin, salt, and pepper and sear until charred at the edges.",
        "Char the corn in the same dry pan for 2 minutes — raw corn on a salad is fine, charred corn is much better.",
        "Whisk lime juice with olive oil, cumin, and salt.",
        "Toss everything except the avocado, which goes on last so it holds its shape.",
      ],
      storageInstructions: "Components keep 3 days; add avocado and dressing at serving.",
    },
    {
      name: "Steak and Blue Cheese Salad",
      mealType: "dinner",
      cuisine: "american",
      dishType: "salad",
      calories: 540,
      proteinG: 44,
      carbsG: 20,
      fatG: 32,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Sirloin steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Blue cheese crumbles", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Mixed baby greens", quantity: 3, unit: "cup", section: "produce" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Bring the steak to room temperature and dry it thoroughly; a cold wet steak steams instead of searing.",
        "Sear hard 3-4 minutes per side for medium-rare, then rest a full 8 minutes.",
        "Slice against the grain — with the grain, even a good sirloin eats tough.",
        "Whisk balsamic, Dijon, and olive oil, dress the greens, and lay the steak over the top with blue cheese and onion.",
      ],
      storageInstructions: "Best fresh; cooked steak keeps 3 days and is good cold on this salad.",
    },
    {
      name: "Chopped Italian Salad",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "salad",
      calories: 486,
      proteinG: 28,
      carbsG: 26,
      fatG: 30,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Genoa salami, diced", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Sliced deli ham, diced", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Provolone cheese, diced", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Canned chickpeas, drained", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Romaine lettuce, chopped", quantity: 2.5, unit: "cup", section: "produce" },
        { name: "Pepperoncini, sliced", quantity: 3, unit: "each", section: "pantry" },
        { name: "Red onion, diced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Dried oregano", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cut everything to roughly the same small dice — a chopped salad works because each forkful gets all of it, which fails if the pieces are uneven.",
        "Whisk vinegar, oregano, and olive oil.",
        "Toss the sturdy ingredients with the dressing first and let them sit 5 minutes.",
        "Add the lettuce last and toss briefly.",
      ],
      storageInstructions: "Undressed components keep 3 days; dress at serving.",
    },
    {
      name: "Kale Caesar with Roasted Chickpeas",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 448,
      proteinG: 20,
      carbsG: 42,
      fatG: 22,
      fiberG: 12,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk", "eggs"],
      ingredients: [
        { name: "Lacinato kale, shredded", quantity: 3, unit: "cup", section: "produce" },
        { name: "Canned chickpeas, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 1, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Dry the chickpeas completely, toss with oil and paprika, and roast at 425F for 30 minutes until they rattle in the pan.",
        "Strip the kale from its stems, shred finely, and massage it with a pinch of salt and a squeeze of lemon for a full minute until it darkens and softens. Unmassaged raw kale is genuinely unpleasant.",
        "Whisk mayonnaise, Dijon, garlic, lemon juice, and Parmesan into a dressing.",
        "Toss and top with the roasted chickpeas. Unlike lettuce, this salad is fine dressed an hour ahead.",
      ],
      storageInstructions: "Dressed kale holds 2 days; store chickpeas separately or they soften.",
    },
    {
      name: "Caprese Salad with White Beans",
      mealType: "lunch",
      cuisine: "italian",
      dishType: "salad",
      calories: 442,
      proteinG: 24,
      carbsG: 38,
      fatG: 22,
      fiberG: 10,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Fresh mozzarella", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Canned cannellini beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Tomato, sliced thick", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Fresh basil leaves", quantity: 12, unit: "leaf", section: "produce" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Arugula", quantity: 1, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Salt the tomato slices and let them drain on a towel for 10 minutes; this seasons them and stops the plate flooding.",
        "Bring the mozzarella to room temperature — cold mozzarella is squeaky and tastes of almost nothing.",
        "Layer tomato and mozzarella with the beans and arugula.",
        "Dress with olive oil, a little balsamic, flaky salt, and torn basil.",
      ],
      storageInstructions: "Assemble fresh; this does not keep once dressed.",
    },
    {
      name: "Salmon Nicoise Salad",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "salad",
      calories: 566,
      proteinG: 42,
      carbsG: 32,
      fatG: 30,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "eggs"],
      ingredients: [
        { name: "Salmon fillet", quantity: 5, unit: "oz", section: "protein" },
        { name: "Hard-boiled egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Green beans, trimmed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Nicoise olives", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Boil the potatoes until tender and dress them while still warm — warm potatoes absorb vinaigrette, cold ones repel it.",
        "Blanch the green beans 3 minutes and shock in ice water to keep them bright and snappy.",
        "Sear the salmon skin-side down 4 minutes, then 2 minutes on the flesh side.",
        "Compose in sections rather than tossing, and spoon the Dijon vinaigrette over everything.",
      ],
      storageInstructions: "Components keep 3 days; assemble at serving.",
    },
    {
      name: "Waldorf Chicken Salad",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 486,
      proteinG: 36,
      carbsG: 34,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["tree_nuts", "milk"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Apple, diced", quantity: 1, unit: "each", section: "produce" },
        { name: "Celery, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Walnuts, chopped", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red grapes, halved", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Mixed baby greens", quantity: 2, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Toast the walnuts in a dry pan 3 minutes; raw walnuts taste chalky and slightly bitter here.",
        "Toss the diced apple in lemon juice immediately to stop it browning.",
        "Fold chicken, apple, celery, and grapes with yogurt and season well.",
        "Serve over greens with the walnuts scattered on top so they stay crunchy.",
      ],
      storageInstructions: "Keeps 3 days; add walnuts at serving.",
    },
    {
      name: "Tuna Poke Salad Bowl",
      mealType: "lunch",
      cuisine: "japanese",
      dishType: "salad",
      calories: 498,
      proteinG: 40,
      carbsG: 40,
      fatG: 18,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Sushi-grade tuna, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Edamame, shelled", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Mixed baby greens", quantity: 1.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Buy tuna explicitly sold for raw consumption; nothing in this recipe cooks it.",
        "Cut against the grain into clean half-inch cubes with a sharp knife — sawing tears the flesh and it goes mushy.",
        "Marinate in soy sauce, sesame oil, and scallion for 10-15 minutes only. Longer and the soy starts curing the outside grey.",
        "Build over rice and greens with cucumber, edamame, avocado, and sesame seeds.",
      ],
      storageInstructions: "Eat the day it's made. Do not store marinated raw fish.",
    },
    {
      name: "Roasted Beet and Goat Cheese Salad",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "salad",
      calories: 424,
      proteinG: 16,
      carbsG: 38,
      fatG: 24,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 50,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk", "tree_nuts"],
      ingredients: [
        { name: "Beets", quantity: 2, unit: "each", section: "produce" },
        { name: "Goat cheese", quantity: 1.5, unit: "oz", section: "dairy" },
        { name: "Pistachios, chopped", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Arugula", quantity: 3, unit: "cup", section: "produce" },
        { name: "Orange", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Honey", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Wrap the beets whole in foil and roast at 400F for 50 minutes — roasting concentrates them, boiling leaches the colour and sweetness into the water.",
        "Rub the skins off with a paper towel while still warm; they slip away with no peeling.",
        "Whisk balsamic, honey, orange juice, and olive oil.",
        "Toss the arugula, then top with beets, crumbled goat cheese, and pistachios.",
      ],
      storageInstructions: "Roasted beets keep 5 days refrigerated.",
    },
    {
      name: "Thai Peanut Chicken Salad",
      mealType: "lunch",
      cuisine: "thai",
      dishType: "salad",
      calories: 524,
      proteinG: 40,
      carbsG: 34,
      fatG: 26,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["peanuts", "soybeans", "wheat", "fish"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Peanut butter", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fish sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Napa cabbage, shredded", quantity: 2, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red bell pepper, julienned", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Fresh mint", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Whisk peanut butter with lime juice, soy sauce, fish sauce, and enough warm water to make it pourable. It will seize at first, then loosen — keep adding water a teaspoon at a time.",
        "Sear and slice the chicken.",
        "Toss the cabbage, carrot, and pepper with most of the dressing.",
        "Add the herbs by the handful at the very end; they're an ingredient here, not a garnish.",
      ],
      storageInstructions: "Dressing keeps a week refrigerated and thickens — thin with water.",
    },
    {
      name: "Antipasto Salad with Tortellini",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "salad",
      calories: 592,
      proteinG: 30,
      carbsG: 54,
      fatG: 28,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: [],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Cheese tortellini", quantity: 4, unit: "oz", section: "grains" },
        { name: "Genoa salami, diced", quantity: 1.5, unit: "oz", section: "protein" },
        { name: "Fresh mozzarella pearls", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Roasted red pepper, sliced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Kalamata olives, halved", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Artichoke hearts, quartered", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh basil leaves", quantity: 8, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Cook the tortellini, drain, and toss immediately with a little olive oil so they don't fuse into a block.",
        "Cool them to room temperature before adding anything else — hot pasta melts the mozzarella into strings.",
        "Fold in the salami, peppers, olives, and artichokes with vinegar and oil.",
        "Rest 20 minutes before serving; this salad is better after the flavours settle.",
      ],
      storageInstructions: "Keeps 3 days refrigerated and is good cold straight from the fridge.",
    },
    {
      name: "Shrimp and Avocado Salad",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "salad",
      calories: 432,
      proteinG: 36,
      carbsG: 22,
      fatG: 24,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 5,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Avocado", quantity: 1, unit: "each", section: "produce" },
        { name: "Mixed baby greens", quantity: 3, unit: "cup", section: "produce" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh dill", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Pat the shrimp bone dry and sear in a hot pan 90 seconds per side. They're done when they form a loose C — a tight O means overcooked.",
        "Soak the sliced red onion in cold water 10 minutes to take the harsh bite out.",
        "Whisk lemon juice, olive oil, dill, salt, and pepper.",
        "Toss greens and cucumber, then top with shrimp and avocado.",
      ],
      storageInstructions: "Best fresh; cooked shrimp keep 2 days.",
    },
    {
      name: "Chicken Taco Salad",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "salad",
      calories: 546,
      proteinG: 40,
      carbsG: 42,
      fatG: 24,
      fiberG: 11,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned pinto beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Corn tortilla", quantity: 2, unit: "each", section: "bakery" },
        { name: "Romaine lettuce, chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Salsa", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Chili powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cut the corn tortillas into strips, toss with a little oil and salt, and bake at 400F for 10 minutes until crisp — far better than crumbled chips and the reason to use corn rather than flour here.",
        "Cook the chicken with chili powder until browned.",
        "Thin the yogurt with lime juice to make a drizzling crema.",
        "Build lettuce, beans, chicken, cheese, and salsa, then top with the tortilla strips just before eating.",
      ],
      storageInstructions: "Components keep 3 days; strips keep 2 days in a sealed container.",
    },
    {
      name: "Broccoli Crunch Salad",
      mealType: "lunch",
      cuisine: "american",
      dishType: "salad",
      calories: 424,
      proteinG: 18,
      carbsG: 34,
      fatG: 24,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-fiber"],
      allergens: ["milk", "eggs", "tree_nuts"],
      ingredients: [
        { name: "Broccoli florets, finely chopped", quantity: 3, unit: "cup", section: "produce" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Sharp cheddar cheese, diced", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Almonds, sliced", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red onion, minced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Dried cranberries", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Chop the broccoli much finer than feels right — pea-sized. Large florets make this salad hard to eat and badly dressed.",
        "Cook the bacon crisp and chop it.",
        "Whisk yogurt, mayonnaise, vinegar, and a pinch of sugar into a dressing.",
        "Toss everything and refrigerate at least 30 minutes; this salad genuinely needs the rest to soften the broccoli slightly.",
      ],
      storageInstructions: "Keeps 3 days and is best on day two; add almonds at serving.",
    },
    {
      name: "Farro and Roasted Vegetable Salad",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "salad",
      calories: 486,
      proteinG: 16,
      carbsG: 62,
      fatG: 18,
      fiberG: 12,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Pearled farro", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Zucchini, chunked", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Red onion, wedged", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Feta cheese, crumbled", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Cook the farro in well-salted water until chewy-tender, about 25 minutes, then drain and spread on a tray to cool.",
        "Roast the vegetables at 425F for 25 minutes in a single layer — crowded vegetables steam and go limp.",
        "Dress the farro while still warm with lemon and olive oil.",
        "Fold in the roasted vegetables, feta, and parsley once everything is at room temperature.",
      ],
      storageInstructions: "Keeps 4 days refrigerated and travels well; add feta at serving if packing.",
    },

    // ---------------------------------------------------------------
    // BBQ (bucket held 1)
    // ---------------------------------------------------------------
    {
      name: "BBQ Pulled Chicken",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 468,
      proteinG: 44,
      carbsG: 48,
      fatG: 10,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 6, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 1, unit: "cup", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Season the thighs with paprika, salt, and pepper and brown them well.",
        "Add onion and a splash of water, cover, and cook 35 minutes until the chicken shreds easily.",
        "Shred and return to the pan with the barbecue sauce and vinegar, simmering 5 minutes to glaze rather than drown it.",
        "Use thighs, not breast — breast dries out to string before it ever pulls properly.",
        "Serve with roasted potatoes and raw cabbage.",
      ],
      storageInstructions: "Keeps 4 days refrigerated and freezes 3 months.",
    },
    {
      name: "Baby Back Ribs with Dry Rub",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 622,
      proteinG: 44,
      carbsG: 36,
      fatG: 34,
      fiberG: 4,
      prepMinutes: 20,
      cookMinutes: 180,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork baby back ribs", quantity: 7, unit: "oz", section: "protein" },
        { name: "Brown sugar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Onion powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Barbecue sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 2, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Peel the thin membrane off the bone side — grab it with a paper towel and pull. Left on, it goes leathery and blocks the rub.",
        "Coat with the sugar and spice rub and rest at least an hour, ideally overnight.",
        "Wrap in foil with the vinegar and bake at 275F for 2.5 hours.",
        "Unwrap, brush with sauce, and finish uncovered at 425F for 15 minutes to set a glaze.",
        "Done means a toothpick slides in with no resistance, not 'meat falling off the bone' — that's overcooked.",
      ],
      storageInstructions: "Keeps 4 days; reheat wrapped in foil at 300F.",
    },
    {
      name: "Grilled BBQ Chicken Thighs",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 508,
      proteinG: 42,
      carbsG: 36,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken thighs, bone-in", quantity: 6, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Corn on the cob", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Set up two heat zones: hot direct, and a cooler indirect side.",
        "Start the thighs skin-side down over indirect heat for 18 minutes so the fat renders without flaring.",
        "Move to direct heat and brush with sauce only in the last 5 minutes. Barbecue sauce is mostly sugar and will carbonize if applied early.",
        "Grill the corn alongside, and dress the cabbage with vinegar for a sharp slaw.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a 350F oven, not a microwave.",
    },
    {
      name: "Smoked Brisket Plate",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 640,
      proteinG: 48,
      carbsG: 40,
      fatG: 32,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 360,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Beef brisket", quantity: 6, unit: "oz", section: "protein" },
        { name: "Coarse black pepper", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Kosher salt", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 1, unit: "cup", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Barbecue sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Rub with nothing but equal parts coarse salt and pepper — Texas-style, and the meat carries it.",
        "Smoke or bake at 250F fat-side up for about 5 hours, until the internal temperature stalls around 165F.",
        "Wrap tightly in butcher paper or foil and continue to 203F. The stall is evaporative cooling and lasts hours; wrapping pushes through it.",
        "Rest wrapped at least 1 hour before slicing. Slicing early loses every bit of juice onto the board.",
        "Slice against the grain, noting that the grain changes direction between the flat and the point.",
      ],
      storageInstructions: "Keeps 4 days; slice only what you'll eat and store the rest whole.",
    },
    {
      name: "BBQ Baked Beans with Sausage",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 528,
      proteinG: 28,
      carbsG: 64,
      fatG: 18,
      fiberG: 16,
      prepMinutes: 10,
      cookMinutes: 60,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Canned navy beans, drained", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Smoked sausage, sliced", quantity: 3, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Molasses", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yellow mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Brown the sausage and onion together in an ovenproof pan.",
        "Stir in beans, barbecue sauce, molasses, mustard, and vinegar.",
        "Bake uncovered at 325F for 50 minutes until the top darkens and the sauce thickens around the edges.",
        "The uncovered bake is the whole point — covered, you get warm beans in sauce rather than the caramelized top.",
      ],
      storageInstructions: "Keeps 5 days refrigerated and reheats well.",
    },
    {
      name: "BBQ Pork Belly Burnt Ends",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 668,
      proteinG: 34,
      carbsG: 42,
      fatG: 40,
      fiberG: 4,
      prepMinutes: 20,
      cookMinutes: 180,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork belly, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Brown sugar", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cut the belly into even 1.5-inch cubes so they render at the same rate.",
        "Toss with paprika and half the sugar and bake at 275F for 2 hours on a rack, so the rendering fat drips away.",
        "Transfer to a pan, toss with sauce and remaining sugar, cover, and cook 45 more minutes.",
        "Uncover and blast at 425F for 10 minutes to set the bark. They should be lacquered, not wet.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a hot oven to re-crisp.",
    },
    {
      name: "Grilled BBQ Shrimp Skewers",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 396,
      proteinG: 38,
      carbsG: 36,
      fatG: 10,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 7, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 2.5, unit: "tbsp", section: "pantry" },
        { name: "Red bell pepper, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Red onion, chunked", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Soak wooden skewers 30 minutes, or use metal.",
        "Thread shrimp through both the tail and the thick end so they can't spin when you turn the skewer.",
        "Grill over high heat 2-3 minutes per side only, brushing with sauce in the final minute.",
        "Shrimp go from raw to rubbery in about 90 seconds — stand there and watch them.",
      ],
      storageInstructions: "Best immediately; keeps 2 days.",
    },
    {
      name: "BBQ Meatloaf",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 546,
      proteinG: 40,
      carbsG: 42,
      fatG: 24,
      fiberG: 4,
      prepMinutes: 15,
      cookMinutes: 60,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "eggs", "milk"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Breadcrumbs", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Whole milk", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, grated", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Soak the breadcrumbs in the milk for 5 minutes first. This panade is what keeps meatloaf moist; dry crumbs pull water out of the meat instead.",
        "Grate rather than dice the onion so it melts in and doesn't leave crunchy pockets.",
        "Mix gently with your hands only until combined, then shape free-form on a tray rather than packing it into a loaf pan, which steams the sides.",
        "Bake at 350F for 45 minutes, glaze with barbecue sauce, and bake 15 more.",
        "Rest 10 minutes before slicing.",
      ],
      storageInstructions: "Keeps 4 days and makes excellent cold sandwiches.",
    },
    {
      name: "Carolina Vinegar Pulled Pork Plate",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 520,
      proteinG: 42,
      carbsG: 40,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 300,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork shoulder", quantity: 6, unit: "oz", section: "protein" },
        { name: "Apple cider vinegar", quantity: 4, unit: "tbsp", section: "pantry" },
        { name: "Red pepper flakes", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Brown sugar", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Rub the pork with paprika, salt, and pepper and cook at 275F for about 5 hours until it pulls apart with no effort.",
        "Make the sauce by stirring vinegar, pepper flakes, sugar, and salt together — no tomato, no thickener. Eastern Carolina sauce is thin and sharp on purpose.",
        "Pull the pork and dress it with the vinegar sauce while hot so it absorbs rather than sits in it.",
        "Dress the cabbage with a spoonful of the same sauce.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months in its juices.",
    },
    {
      name: "BBQ Chicken Drumsticks with Slaw",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 494,
      proteinG: 40,
      carbsG: 38,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs"],
      ingredients: [
        { name: "Chicken drumsticks", quantity: 6, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Pat the drumsticks very dry and season with paprika, salt, and pepper.",
        "Bake at 425F on a rack for 30 minutes so air circulates and the skin crisps all the way around.",
        "Brush with sauce and bake 10 more minutes.",
        "Toss cabbage and carrot with mayonnaise and vinegar, and salt the cabbage 15 minutes beforehand if you want a slaw that stays crunchy rather than watering out.",
      ],
      storageInstructions: "Chicken keeps 3 days; dress slaw within a day of serving.",
    },
    {
      name: "Grilled BBQ Tofu Steaks",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 442,
      proteinG: 26,
      carbsG: 44,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-protein"],
      allergens: ["soybeans"],
      ingredients: [
        { name: "Extra-firm tofu", quantity: 7, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Corn on the cob", quantity: 1, unit: "each", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Press the tofu under something heavy for at least 20 minutes. Unpressed tofu will not brown, will not absorb sauce, and will fall apart on a grill.",
        "Slice into thick slabs, oil, and season with paprika.",
        "Grill 5 minutes per side until well marked before any sauce touches it.",
        "Brush with barbecue sauce in the last 2 minutes per side.",
      ],
      storageInstructions: "Keeps 4 days and is good cold; re-crisp in a hot pan.",
    },
    {
      name: "BBQ Beef Short Ribs",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bbq",
      calories: 664,
      proteinG: 46,
      carbsG: 38,
      fatG: 36,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 210,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Beef short ribs, bone-in", quantity: 8, unit: "oz", section: "protein" },
        { name: "Barbecue sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Beef broth", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Baby potatoes, halved", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Green cabbage, shredded", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Season heavily with paprika, sugar, salt, and pepper and sear on all sides.",
        "Braise covered with the broth at 300F for 3 hours until the meat pulls back from the bone.",
        "Skim the fat, brush with barbecue sauce, and finish uncovered at 450F for 10 minutes.",
        "Short ribs carry enormous amounts of fat — chilling the braise and lifting the solid fat off is worth doing if you have the time.",
      ],
      storageInstructions: "Keeps 4 days; braise a day ahead to make defatting easy.",
    },

    // ---------------------------------------------------------------
    // Casseroles
    // ---------------------------------------------------------------
    {
      name: "Chicken Pot Pie Casserole",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 596,
      proteinG: 36,
      carbsG: 52,
      fatG: 28,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Puff pastry sheet", quantity: 2, unit: "oz", section: "bakery" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Carrot, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Chicken broth", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Make a roux with butter and flour, then whisk in broth and milk to a thick, gravy-like sauce.",
        "Fold in chicken, carrot, peas, and thyme, and season aggressively — the pastry is bland and the filling has to carry both.",
        "Cool the filling before topping with pastry. Hot filling melts the butter layers and you lose the puff entirely.",
        "Bake at 400F for 30 minutes until the pastry is deep golden and the filling bubbles at the edges.",
      ],
      storageInstructions: "Keeps 3 days; the pastry softens, so reheat uncovered in the oven.",
    },
    {
      name: "Baked Ziti",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "casserole",
      calories: 620,
      proteinG: 34,
      carbsG: 68,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry ziti pasta", quantity: 3, unit: "oz", section: "grains" },
        { name: "Ground turkey (93% lean)", quantity: 3, unit: "oz", section: "protein" },
        { name: "Marinara sauce", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Ricotta cheese", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Fresh basil leaves", quantity: 6, unit: "leaf", section: "produce" },
      ],
      instructions: [
        "Boil the pasta 2 minutes SHORT of al dente. It finishes cooking in the oven, and fully-cooked pasta bakes to mush.",
        "Brown the turkey with garlic and stir into the marinara.",
        "Layer pasta, sauce, and dollops of ricotta — dollops, not a spread layer, so you get pockets rather than a uniform paste.",
        "Top with mozzarella and Parmesan and bake at 375F for 25 minutes, then rest 10 minutes before serving.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months, baked or unbaked.",
    },
    {
      name: "King Ranch Chicken Casserole",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "casserole",
      calories: 588,
      proteinG: 38,
      carbsG: 48,
      fatG: 26,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Cooked chicken breast, shredded", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Roasted green chiles, chopped", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 1.25, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Canned diced tomatoes", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cook onion, bloom the cumin, then make a quick sauce with flour, milk, tomatoes, and chiles.",
        "Char the tortillas briefly over a flame or in a dry pan — untoasted, they disintegrate into paste in the bake.",
        "Layer torn tortillas, chicken, sauce, and cheese twice over.",
        "Bake at 350F for 35 minutes until bubbling, then rest 10 minutes so it holds a cut edge.",
      ],
      storageInstructions: "Keeps 4 days; freezes 2 months.",
    },
    {
      name: "Tuna Noodle Casserole",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 570,
      proteinG: 38,
      carbsG: 56,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "wheat", "milk", "eggs"],
      ingredients: [
        { name: "Egg noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Canned tuna in water, drained", quantity: 5, unit: "oz", section: "protein" },
        { name: "Whole milk", quantity: 0.66, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Brown the mushrooms properly before making the sauce — this is what replaces canned soup and is the difference between a good version and the cafeteria one.",
        "Make a roux with butter and flour, whisk in milk, and simmer to a thick sauce.",
        "Undercook the noodles by 2 minutes, then fold everything together with the tuna and peas.",
        "Top with breadcrumbs and bake at 375F for 25 minutes until browned on top.",
      ],
      storageInstructions: "Keeps 3 days; reheat covered so the top doesn't burn.",
    },
    {
      name: "Green Bean Casserole with Chicken",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 518,
      proteinG: 40,
      carbsG: 40,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Green beans, trimmed", quantity: 2, unit: "cup", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, thinly sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Blanch the green beans 4 minutes and shock in ice water so they stay green through the bake.",
        "Brown the mushrooms hard, then build a roux sauce with butter, flour, and milk.",
        "Fold in beans and chicken and transfer to a baking dish.",
        "Crisp the sliced onion with the breadcrumbs in a dry pan and scatter on top before baking 25 minutes at 375F.",
      ],
      storageInstructions: "Keeps 3 days; the topping softens, so re-crisp under the broiler.",
    },
    {
      name: "Shepherd's Pie",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 596,
      proteinG: 38,
      carbsG: 54,
      fatG: 26,
      fiberG: 8,
      prepMinutes: 25,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Ground lamb", quantity: 5, unit: "oz", section: "protein" },
        { name: "Yukon gold potato", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Whole milk", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Carrot, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Tomato paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "All-purpose flour", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Beef broth", quantity: 0.5, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Brown the lamb hard, drain the excess fat, then cook the carrot with tomato paste and flour before adding broth.",
        "Simmer until thick — a loose filling bleeds up through the potato and turns the top grey.",
        "Boil and mash the potatoes with butter and warm milk. Cold milk makes gluey mash.",
        "Spread the mash over the filling, rough up the surface with a fork so the peaks catch colour, and bake at 400F for 25 minutes.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months; bake from frozen at 375F for an hour.",
    },
    {
      name: "Chicken Broccoli Rice Casserole",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 588,
      proteinG: 40,
      carbsG: 58,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk", "wheat"],
      ingredients: [
        { name: "Cooked chicken breast, diced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Broccoli florets", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Sharp cheddar cheese, grated", quantity: 1.25, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.33, unit: "each", section: "produce" },
      ],
      instructions: [
        "Blanch the broccoli 3 minutes; raw broccoli releases water into the casserole and never quite cooks through.",
        "Make a cheese sauce: roux, then milk, then cheddar off the heat.",
        "Fold with the rice and chicken, keeping the mixture looser than you think — rice absorbs a surprising amount during the bake.",
        "Bake at 375F for 30 minutes until bubbling and browned at the edges.",
      ],
      storageInstructions: "Keeps 4 days; add a splash of milk when reheating.",
    },
    {
      name: "Enchilada Casserole with Beef",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "casserole",
      calories: 604,
      proteinG: 38,
      carbsG: 52,
      fatG: 26,
      fiberG: 10,
      prepMinutes: 20,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 4, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Red enchilada sauce", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Shredded Monterey Jack cheese", quantity: 1.25, unit: "oz", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Brown the beef with onion and cumin.",
        "Dip each tortilla briefly in the warm enchilada sauce before layering — this is the step that keeps them pliable and seasoned rather than papery.",
        "Layer tortillas, beef, beans, sauce, and cheese in a small dish, finishing with cheese.",
        "Bake at 375F for 30 minutes and rest 10 minutes before cutting.",
      ],
      storageInstructions: "Keeps 4 days and freezes 2 months.",
    },
    {
      name: "Spinach and Mushroom Lasagna",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "casserole",
      calories: 578,
      proteinG: 30,
      carbsG: 62,
      fatG: 24,
      fiberG: 9,
      prepMinutes: 30,
      cookMinutes: 50,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Lasagna noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Baby spinach", quantity: 3, unit: "cup", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Ricotta cheese", quantity: 0.5, unit: "cup", section: "dairy" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Marinara sauce", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Cook the mushrooms until they've released and reabsorbed their liquid, then wilt the spinach and squeeze it completely dry.",
        "Wet vegetables are the single reason vegetable lasagna comes out soupy — take this seriously.",
        "Mix the ricotta with Parmesan, garlic, salt, and pepper.",
        "Layer sauce, noodles, ricotta, vegetables, repeating, and finish with mozzarella.",
        "Bake covered at 375F for 35 minutes, uncover for 15, then rest 15 minutes before cutting.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months; rest is mandatory for clean slices.",
    },
    {
      name: "Breakfast Sausage and Egg Casserole",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "casserole",
      calories: 516,
      proteinG: 34,
      carbsG: 32,
      fatG: 28,
      fiberG: 3,
      prepMinutes: 15,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "milk", "wheat"],
      ingredients: [
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Turkey breakfast sausage", quantity: 2.5, unit: "oz", section: "protein" },
        { name: "Sourdough bread, cubed", quantity: 1.5, unit: "oz", section: "bakery" },
        { name: "Whole milk", quantity: 0.33, unit: "cup", section: "dairy" },
        { name: "Sharp cheddar cheese, grated", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Red bell pepper, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Brown the sausage and pepper, and use stale or lightly toasted bread cubes — fresh soft bread turns to paste.",
        "Whisk eggs with milk and plenty of salt and pepper.",
        "Assemble and refrigerate at least an hour, ideally overnight, so the custard fully soaks in.",
        "Bake at 350F for 40-45 minutes until the center is set and no longer wobbles.",
      ],
      storageInstructions: "Assemble the night before; baked casserole keeps 4 days.",
    },
    {
      name: "Sweet Potato and Black Bean Casserole",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "casserole",
      calories: 512,
      proteinG: 20,
      carbsG: 76,
      fatG: 14,
      fiberG: 18,
      prepMinutes: 20,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Sweet potato, thinly sliced", quantity: 2, unit: "cup", section: "produce" },
        { name: "Canned black beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Red enchilada sauce", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Shredded Monterey Jack cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Corn kernels", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Slice the sweet potato thin and even — a mandoline if you have one. Thick slices simply won't cook through in the time the top takes to brown.",
        "Toss the slices with oil, cumin, and salt.",
        "Layer sweet potato, beans, corn, and sauce, finishing with cheese.",
        "Cover with foil and bake at 400F for 35 minutes, then uncover 10 minutes to brown. Test with a knife before serving.",
      ],
      storageInstructions: "Keeps 4 days refrigerated.",
    },
    {
      name: "Baked Mac and Cheese with Broccoli",
      mealType: "dinner",
      cuisine: "american",
      dishType: "casserole",
      calories: 638,
      proteinG: 30,
      carbsG: 66,
      fatG: 28,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Dry elbow pasta", quantity: 3, unit: "oz", section: "grains" },
        { name: "Sharp cheddar cheese, grated", quantity: 2, unit: "oz", section: "dairy" },
        { name: "Whole milk", quantity: 0.75, unit: "cup", section: "dairy" },
        { name: "All-purpose flour", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Broccoli florets", quantity: 1, unit: "cup", section: "produce" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Grate the cheese yourself. Pre-shredded cheese is coated in anti-caking starch and will never melt smoothly.",
        "Make a roux, whisk in milk, and simmer to a proper béchamel before adding cheese OFF the heat.",
        "Add the Dijon — you won't taste mustard, but the sauce tastes noticeably more like cheese.",
        "Fold with undercooked pasta and blanched broccoli, top with breadcrumbs, and bake at 375F for 25 minutes.",
      ],
      storageInstructions: "Keeps 3 days; loosen with milk when reheating.",
    },
  ],
};
