import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 4b of 4 (2026-08-16) — stir-fry, rice, bowls.
 * Final batch of the 300-recipe expansion.
 *
 * These three buckets were the least starved (14/20/26) but they're the
 * weekday-dinner workhorses, so they get the remaining budget rather than
 * the snack forms, which were already the library's healthiest.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Stir-fry
    // ---------------------------------------------------------------
    {
      name: "Szechuan Chicken Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 534,
      proteinG: 40,
      carbsG: 46,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["soybeans", "wheat", "sesame", "peanuts"],
      ingredients: [
        { name: "Chicken thighs, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Dried red chiles", quantity: 6, unit: "each", section: "pantry" },
        { name: "Sichuan peppercorns", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Peanuts", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Scallion, cut into batons", quantity: 3, unit: "each", section: "produce" },
        { name: "Cornstarch", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Marinate the chicken in soy sauce and cornstarch 15 minutes — the starch forms a coating that keeps it juicy under high heat.",
        "Fry the whole dried chiles and peppercorns in oil for 20 seconds until fragrant but NOT blackened. Burnt chiles make the whole wok bitter and you have to start over.",
        "Add the chicken in one layer and leave it 45 seconds before stirring.",
        "Finish with scallion, peanuts, and sesame oil off the heat.",
      ],
      storageInstructions: "Keeps 3 days; the peanuts soften, so add fresh if you mind.",
    },
    {
      name: "Broccoli Beef Stir-Fry with Garlic",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 528,
      proteinG: 42,
      carbsG: 44,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "shellfish"],
      ingredients: [
        { name: "Beef flank, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Broccoli florets", quantity: 2, unit: "cup", section: "produce" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Oyster sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Cornstarch", quantity: 1.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Blanch the broccoli 90 seconds and shock it in cold water. Stir-frying raw broccoli from scratch either burns the outside or leaves it raw.",
        "Velvet the beef in soy sauce and cornstarch for 20 minutes.",
        "Sear the beef in a very hot wok in one layer, then remove while still rare — it finishes in the sauce.",
        "Cook the aromatics, add the sauce and a cornstarch slurry, then return beef and broccoli for 60 seconds.",
      ],
      storageInstructions: "Keeps 3 days and reheats well.",
    },
    {
      name: "Honey Garlic Shrimp Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 496,
      proteinG: 38,
      carbsG: 52,
      fatG: 14,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Honey", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 5, unit: "clove", section: "produce" },
        { name: "Snap peas", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cook the vegetables first and set aside; shrimp need the pan to themselves.",
        "Sear the shrimp 60 seconds per side and remove them the moment they curl into a C.",
        "Add honey, soy, and vinegar to the empty pan and let it bubble down to a syrup for a minute.",
        "Return everything and toss to coat. Adding honey earlier means it scorches before the shrimp are done.",
      ],
      storageInstructions: "Keeps 2 days; shrimp toughen on reheating.",
    },
    {
      name: "Pork and Green Bean Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 512,
      proteinG: 36,
      carbsG: 44,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat"],
      ingredients: [
        { name: "Ground pork", quantity: 5, unit: "oz", section: "protein" },
        { name: "Green beans, trimmed", quantity: 2, unit: "cup", section: "produce" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Chili flakes", quantity: 0.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Dry-fry the green beans in a hot pan with barely any oil until they blister and wrinkle, about 8 minutes.",
        "This blistering is the whole dish — steamed or boiled beans give you a completely different and much worse result.",
        "Remove the beans, brown the pork hard, then add aromatics.",
        "Return the beans with soy and vinegar and toss 1 minute.",
      ],
      storageInstructions: "Keeps 3 days and is good cold.",
    },
    {
      name: "Cashew Chicken Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 566,
      proteinG: 40,
      carbsG: 46,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["tree_nuts", "soybeans", "wheat", "shellfish"],
      ingredients: [
        { name: "Chicken breast, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cashews", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Oyster sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Celery, sliced on the bias", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red bell pepper, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Cornstarch", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Toast the cashews in the dry wok first and remove them — left in through the stir-fry they go soft and slightly bitter.",
        "Velvet the chicken with cornstarch and soy 15 minutes.",
        "Stir-fry the chicken, then the vegetables, keeping the celery crisp.",
        "Add the sauce, thicken with a slurry, and fold the cashews back in at the very last second.",
      ],
      storageInstructions: "Keeps 3 days; store cashews separately for best texture.",
    },
    {
      name: "Ginger Scallion Tofu Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 486,
      proteinG: 26,
      carbsG: 50,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 25,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-protein"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Extra-firm tofu, cubed", quantity: 7, unit: "oz", section: "protein" },
        { name: "Cooked brown rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Fresh ginger, julienned", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Scallion, cut into batons", quantity: 5, unit: "each", section: "produce" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Cornstarch", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Bok choy, chopped", quantity: 1.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Press the tofu 20 minutes, then toss the cubes in cornstarch — this is what produces a genuinely crisp shell rather than pale, floppy tofu.",
        "Fry in a shallow layer of oil, undisturbed, until golden on several sides, then remove.",
        "Use twice as much ginger and scallion as feels reasonable; they're the dish, not a seasoning.",
        "Stir-fry the aromatics and bok choy, then return the tofu and toss with soy and sesame oil off the heat so the crust survives.",
      ],
      storageInstructions: "Keeps 3 days; re-crisp the tofu in a hot dry pan.",
    },
    {
      name: "Thai Basil Chicken Stir-Fry",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "stir_fry",
      calories: 520,
      proteinG: 40,
      carbsG: 44,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "soybeans", "wheat", "shellfish"],
      ingredients: [
        { name: "Ground chicken", quantity: 5, unit: "oz", section: "protein" },
        { name: "Fresh Thai basil", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Cooked jasmine rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Fish sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Oyster sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Thai chili, minced", quantity: 3, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 5, unit: "clove", section: "produce" },
        { name: "Soy sauce", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Pound the garlic and chilies to a rough paste rather than mincing them — this is how pad krapow is actually made and the texture matters.",
        "Get the pan smoking, fry the paste for 15 seconds, then add the chicken and press it flat to brown.",
        "Add the sauces and let them reduce and caramelize onto the meat.",
        "Kill the heat, then add the basil by the handful. It should wilt from residual heat only; cooked basil goes black and loses its anise note.",
      ],
      storageInstructions: "Keeps 3 days; add fresh basil when reheating.",
    },
    {
      name: "Sweet Chili Tempeh Stir-Fry",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "stir_fry",
      calories: 528,
      proteinG: 28,
      carbsG: 58,
      fatG: 20,
      fiberG: 10,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat"],
      ingredients: [
        { name: "Tempeh, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked brown rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Sweet chili sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Snap peas", quantity: 1, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Steam the tempeh for 10 minutes before frying. This removes its characteristic bitterness and is the step almost everyone skips.",
        "Pat dry and sear until deeply golden on all sides.",
        "Stir-fry the vegetables fast, keeping the snap peas squeaky.",
        "Add the sauces off the heat and finish with lime and cilantro.",
      ],
      storageInstructions: "Keeps 4 days; tempeh holds up well.",
    },
    {
      name: "Beef and Snow Pea Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 518,
      proteinG: 42,
      carbsG: 44,
      fatG: 19,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Snow peas", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Shaoxing wine", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cornstarch", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Slice the beef across the grain, as thin as you can manage — freeze it 20 minutes first if it fights you.",
        "Velvet with soy, wine, and cornstarch for 20 minutes.",
        "Cook in two small batches. One crowded batch drops the pan temperature and the beef stews grey.",
        "Add the snow peas for the final 90 seconds only; they should stay bright and audible.",
      ],
      storageInstructions: "Keeps 3 days.",
    },
    {
      name: "Chicken and Asparagus Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 494,
      proteinG: 42,
      carbsG: 42,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Asparagus, cut into pieces", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Cooked brown rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Cornstarch", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Snap the woody ends off the asparagus and cut on a sharp bias, which exposes more surface to the pan.",
        "Velvet the chicken briefly with cornstarch and soy.",
        "Sear the chicken, remove, then cook the asparagus 3 minutes until bright green with brown blisters.",
        "Combine with garlic and sauce for 60 seconds, finishing with lemon off the heat.",
      ],
      storageInstructions: "Keeps 3 days.",
    },
    {
      name: "Kung Pao Shrimp",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 520,
      proteinG: 36,
      carbsG: 48,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "peanuts", "soybeans", "wheat"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Peanuts", quantity: 2.5, unit: "tbsp", section: "pantry" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Dried red chiles", quantity: 6, unit: "each", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Black vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sichuan peppercorns", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Scallion, cut into batons", quantity: 3, unit: "each", section: "produce" },
        { name: "Cornstarch", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Mix the sauce completely before you start — soy, black vinegar, a pinch of sugar, and the cornstarch slurry. Stir-frying gives you no time to measure mid-cook.",
        "Fry the chiles and peppercorns briefly in oil.",
        "Sear the shrimp 45 seconds per side and remove.",
        "Add the sauce, let it thicken, then return shrimp with scallion and peanuts and toss once.",
      ],
      storageInstructions: "Keeps 2 days.",
    },
    {
      name: "Vegetable Fried Rice Stir-Fry with Egg",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 486,
      proteinG: 20,
      carbsG: 62,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Day-old cooked rice", quantity: 1.25, unit: "cup", section: "grains" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Frozen peas and carrots", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Vegetable oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Use rice cooked at least a day ahead and refrigerated uncovered. Fresh rice is too moist and steams into a sticky mass — this is the single rule of fried rice.",
        "Break the cold rice up with your fingers before it goes near the pan.",
        "Scramble the eggs and remove, then fry the rice hard, pressing it against the pan to get toasted grains.",
        "Add vegetables, soy, and sesame oil, then fold the egg back in.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a hot pan, not a microwave.",
    },
    {
      name: "Mongolian Beef Stir-Fry with Peppers",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 556,
      proteinG: 40,
      carbsG: 52,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Beef flank, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cornstarch", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Scallion, cut into batons", quantity: 4, unit: "each", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Coat the sliced beef in dry cornstarch — a thicker coat than for velveting, because here you want a crisp exterior.",
        "Shallow-fry in batches until browned and crisp at the edges, then drain.",
        "Reduce soy, sugar, and ginger to a syrup in the same pan.",
        "Toss the beef through the sauce at the last moment. Left to sit, the coating goes soft immediately.",
      ],
      storageInstructions: "Keeps 3 days; the coating softens but the flavour holds.",
    },
    {
      name: "Chicken and Cabbage Stir-Fry",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "stir_fry",
      calories: 468,
      proteinG: 40,
      carbsG: 40,
      fatG: 17,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Chicken thighs, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Napa cabbage, shredded", quantity: 3, unit: "cup", section: "produce" },
        { name: "Cooked brown rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Separate the thick cabbage stems from the leaves and start the stems 2 minutes earlier — they need roughly twice as long.",
        "Brown the chicken thighs hard and remove.",
        "Stir-fry the cabbage over high heat until it collapses but still has bite at the stem.",
        "Return the chicken with soy, vinegar, and sesame oil.",
      ],
      storageInstructions: "Keeps 3 days; cabbage softens further but stays good.",
    },

    // ---------------------------------------------------------------
    // Rice
    // ---------------------------------------------------------------
    {
      name: "Chicken Fried Rice",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "rice",
      calories: 552,
      proteinG: 38,
      carbsG: 60,
      fatG: 18,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Day-old cooked rice", quantity: 1.25, unit: "cup", section: "grains" },
        { name: "Chicken breast, diced", quantity: 4, unit: "oz", section: "protein" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Frozen peas and carrots", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Vegetable oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cold day-old rice, broken up by hand. Fresh rice makes mush and there is no way around it.",
        "Cook the chicken first and remove.",
        "Scramble the eggs and remove those too.",
        "Fry the rice alone over the highest heat for 3-4 minutes, spreading and pressing it so the grains toast.",
        "Fold everything back in with soy and sesame oil at the end.",
      ],
      storageInstructions: "Keeps 3 days; reheat in a hot pan.",
    },
    {
      name: "Spanish Rice with Chicken",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "rice",
      calories: 560,
      proteinG: 40,
      carbsG: 58,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Long-grain white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Tomato sauce", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Chicken broth", quantity: 1.25, unit: "cup", section: "pantry" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Toast the DRY rice in oil until the grains turn chalky white and smell nutty, about 4 minutes. This is what keeps the grains separate.",
        "Brown the chicken and set aside.",
        "Add onion, garlic, cumin, tomato sauce, and broth to the rice, bring to a simmer, then nestle the chicken back in.",
        "Cover and cook 20 minutes without lifting the lid, then rest off the heat 10 minutes before fluffing.",
      ],
      storageInstructions: "Keeps 4 days; add a splash of broth when reheating.",
    },
    {
      name: "Chicken Biryani",
      mealType: "dinner",
      cuisine: "indian",
      dishType: "rice",
      calories: 616,
      proteinG: 40,
      carbsG: 66,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 30,
      cookMinutes: 45,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Basmati rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Yellow onion, thinly sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Garam masala", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Turmeric", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Saffron threads", quantity: 1, unit: "pinch", section: "pantry" },
        { name: "Fresh mint", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Ghee", quantity: 1, unit: "tbsp", section: "dairy" },
      ],
      instructions: [
        "Soak the basmati 30 minutes, then parboil it only to 70% done — it finishes steaming on top of the chicken.",
        "Fry the onions slowly until deep brown and crisp; these birista are a core flavour, not a garnish.",
        "Marinate the chicken in yogurt and spices, then layer: chicken on the bottom, rice on top, saffron milk and fried onions over that.",
        "Seal the pot tightly and cook on the lowest heat 25 minutes. The steam trapped inside is the whole cooking method — do not stir, and do not peek.",
      ],
      storageInstructions: "Keeps 4 days; reheat covered with a splash of water.",
    },
    {
      name: "Cilantro Lime Rice Bowl with Chicken",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "rice",
      calories: 552,
      proteinG: 42,
      carbsG: 58,
      fatG: 16,
      fiberG: 9,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Long-grain white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Lime", quantity: 2, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Canned black beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Rinse the rice until the water runs clear, then cook it normally.",
        "Add the lime juice and cilantro AFTER cooking, while fluffing. Cooking rice in acid keeps the grains from softening properly.",
        "Season the chicken with cumin and sear until charred at the edges.",
        "Assemble with warmed beans and charred corn.",
      ],
      storageInstructions: "Keeps 4 days; refresh with fresh lime and cilantro.",
    },
    {
      name: "Mushroom Risotto",
      mealType: "dinner",
      cuisine: "italian",
      dishType: "rice",
      calories: 574,
      proteinG: 20,
      carbsG: 70,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      ingredients: [
        { name: "Arborio rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Cremini mushrooms, sliced", quantity: 2, unit: "cup", section: "produce" },
        { name: "Vegetable broth", quantity: 2.5, unit: "cup", section: "pantry" },
        { name: "Dry white wine", quantity: 0.25, unit: "cup", section: "pantry" },
        { name: "Grated Parmesan", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Butter", quantity: 1, unit: "tbsp", section: "dairy" },
        { name: "Shallot, minced", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh thyme", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Keep the broth at a bare simmer in a separate pan. Cold broth shocks the rice and stops the starch releasing.",
        "Toast the rice in butter until the edges turn translucent, then add wine and let it absorb fully.",
        "Add broth one ladle at a time, stirring, waiting until each is nearly absorbed. This takes 18-20 minutes and cannot be rushed.",
        "Off the heat, beat in cold butter and Parmesan hard — this mantecatura is what makes risotto creamy without cream.",
        "It should spread slowly on the plate, not hold a mound.",
      ],
      storageInstructions: "Best immediately; leftovers make excellent arancini.",
    },
    {
      name: "Coconut Rice with Grilled Shrimp",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "rice",
      calories: 578,
      proteinG: 36,
      carbsG: 62,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "fish"],
      ingredients: [
        { name: "Jasmine rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Light coconut milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Fish sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Red chili, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Vegetable oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Rinse the rice, then cook it in coconut milk cut with water, roughly half and half.",
        "Full-strength coconut milk scorches on the bottom before the rice cooks through — this is the usual failure.",
        "Salt the rice properly; coconut rice tastes flat and vaguely sweet without it.",
        "Sear the shrimp 90 seconds a side and serve over the rice with lime, chili, and cilantro.",
      ],
      storageInstructions: "Rice keeps 3 days; shrimp best fresh.",
    },
    {
      name: "Jambalaya with Chicken and Sausage",
      mealType: "dinner",
      cuisine: "american",
      dishType: "rice",
      calories: 604,
      proteinG: 40,
      carbsG: 62,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Long-grain white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Chicken thighs, cubed", quantity: 3, unit: "oz", section: "protein" },
        { name: "Andouille sausage, sliced", quantity: 2, unit: "oz", section: "protein" },
        { name: "Green bell pepper, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Celery, diced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Canned diced tomatoes", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Chicken broth", quantity: 1.25, unit: "cup", section: "pantry" },
        { name: "Smoked paprika", quantity: 1.5, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brown the sausage first and cook everything else in its rendered fat.",
        "Build the holy trinity — onion, celery, green pepper — until soft.",
        "Add rice and toast briefly, then tomatoes, broth, and paprika.",
        "Cover and cook 20 minutes WITHOUT stirring. Stirring releases starch and turns jambalaya into risotto, which is a different dish.",
        "Rest 10 minutes off the heat before fluffing.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months.",
    },
    {
      name: "Lemon Herb Rice with Salmon",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "rice",
      calories: 588,
      proteinG: 42,
      carbsG: 56,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish"],
      ingredients: [
        { name: "Long-grain white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Salmon fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "Lemon", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Fresh dill", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Chicken broth", quantity: 1.25, unit: "cup", section: "pantry" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
      ],
      instructions: [
        "Cook the rice in broth with garlic for a base that tastes of something on its own.",
        "Sear the salmon skin-side down 5 minutes without moving it, then 2 minutes flesh side.",
        "Fold lemon zest and the herbs through the rice after cooking, off the heat.",
        "Add the lemon juice at the very end — added early it dulls to a flat, cooked-citrus taste.",
      ],
      storageInstructions: "Keeps 3 days; good cold as a rice salad.",
    },
    {
      name: "Kimchi Fried Rice with Egg",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "rice",
      calories: 520,
      proteinG: 24,
      carbsG: 62,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian"],
      allergens: ["eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Day-old cooked rice", quantity: 1.25, unit: "cup", section: "grains" },
        { name: "Kimchi, chopped", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Eggs", quantity: 2, unit: "each", section: "protein" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Gochujang", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Use properly sour, well-fermented kimchi — fresh kimchi lacks the acidity that makes this dish work.",
        "Fry the chopped kimchi in oil for 3-4 minutes first, along with its juice, until it darkens.",
        "Add the cold broken-up rice and gochujang and fry hard, pressing the rice into the pan.",
        "Top with a fried egg with a runny yolk, sesame oil, scallion, and seeds.",
      ],
      storageInstructions: "Keeps 3 days; fry a fresh egg each time.",
    },
    {
      name: "Beef and Broccoli Rice Bowl",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "rice",
      calories: 588,
      proteinG: 42,
      carbsG: 58,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Beef sirloin, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked brown rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Broccoli florets", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cornstarch", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Steam the broccoli 4 minutes until bright green and just tender.",
        "Velvet and sear the beef fast over high heat.",
        "Build the sauce with soy, sugar, ginger, and a cornstarch slurry and simmer 60 seconds until it coats a spoon.",
        "Spoon over rice, keeping the broccoli on top rather than tossed through, so it doesn't go army-green in the sauce.",
      ],
      storageInstructions: "Keeps 4 days; excellent meal-prep.",
    },
    {
      name: "Paella with Chicken and Shrimp",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "rice",
      calories: 622,
      proteinG: 44,
      carbsG: 62,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 25,
      cookMinutes: 40,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish"],
      ingredients: [
        { name: "Bomba or arborio rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Chicken thighs, cubed", quantity: 3, unit: "oz", section: "protein" },
        { name: "Shrimp, shell-on", quantity: 4, unit: "oz", section: "protein" },
        { name: "Saffron threads", quantity: 1, unit: "pinch", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chicken broth", quantity: 1.5, unit: "cup", section: "pantry" },
        { name: "Red bell pepper, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Frozen peas", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Bloom the saffron in a little warm broth for 10 minutes before it goes in.",
        "Brown the chicken, build the sofrito, then add rice and toast it briefly.",
        "Add the hot broth, spread the rice flat, and DO NOT STIR again. Stirring makes risotto; leaving it makes paella.",
        "Add shrimp and peas in the last 6 minutes.",
        "For the last 90 seconds, raise the heat until you hear crackling — that's the socarrat, the toasted crust on the bottom, and it's the best part.",
      ],
      storageInstructions: "Keeps 3 days; the socarrat doesn't survive reheating.",
    },
    {
      name: "Egg Roll in a Bowl over Rice",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "rice",
      calories: 520,
      proteinG: 36,
      carbsG: 50,
      fatG: 20,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Ground pork", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Green cabbage, shredded", quantity: 2.5, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
      ],
      instructions: [
        "Brown the pork hard and drain the excess fat.",
        "Add the cabbage and carrot over high heat and cook only 4-5 minutes — it should stay crunchy, since the whole point is egg-roll filling, not stewed cabbage.",
        "Season with soy, vinegar, ginger, and sesame oil off the heat.",
        "Serve over rice with scallion.",
      ],
      storageInstructions: "Keeps 4 days; the cabbage softens on reheating.",
    },
    {
      name: "Stuffed Pepper Rice Skillet",
      mealType: "dinner",
      cuisine: "american",
      dishType: "rice",
      calories: 566,
      proteinG: 38,
      carbsG: 58,
      fatG: 20,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 35,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Long-grain white rice", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Red bell pepper, diced", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Canned diced tomatoes", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Beef broth", quantity: 1, unit: "cup", section: "pantry" },
        { name: "Shredded mozzarella", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Yellow onion, diced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Brown the beef and onion, then add peppers and cook 5 minutes.",
        "Stir in rice, tomatoes, broth, and oregano.",
        "Cover and simmer 20 minutes until the rice is tender and the liquid absorbed.",
        "Scatter mozzarella over, cover 2 minutes to melt, and serve straight from the skillet — all the flavour of stuffed peppers without hollowing anything out.",
      ],
      storageInstructions: "Keeps 4 days and freezes 2 months.",
    },

    // ---------------------------------------------------------------
    // Bowls
    // ---------------------------------------------------------------
    {
      name: "Chicken Teriyaki Broccoli Bowl",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "bowl",
      calories: 566,
      proteinG: 44,
      carbsG: 58,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked brown rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Broccoli florets", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Mirin", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Brown sugar", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Sear the thighs skin-side down until deeply browned, then cook through and remove.",
        "Reduce soy, mirin, sugar, and ginger in the same pan until it thickens into a glaze that coats a spoon.",
        "Return the chicken and turn it in the glaze off the heat.",
        "Build the bowl with rice, steamed broccoli, sliced chicken, and the remaining glaze spooned over.",
      ],
      storageInstructions: "Keeps 4 days; excellent meal-prep.",
    },
    {
      name: "Mediterranean Falafel Bowl",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "bowl",
      calories: 592,
      proteinG: 22,
      carbsG: 72,
      fatG: 24,
      fiberG: 16,
      prepMinutes: 25,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["sesame", "wheat"],
      ingredients: [
        { name: "Dried chickpeas, soaked overnight", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Cooked quinoa", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Tahini", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Fresh parsley", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Ground cumin", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Use dried chickpeas soaked overnight, never canned. Canned chickpeas contain too much water and the falafel will disintegrate in the pan — this is not a substitution you can make.",
        "Blitz the soaked (still raw) chickpeas with parsley, cumin, and garlic to a coarse, sandy texture.",
        "Rest the mixture 30 minutes, form into balls, and bake at 400F for 20 minutes or shallow-fry.",
        "Whisk tahini with lemon and cold water — it seizes then loosens — and build the bowl over quinoa.",
      ],
      storageInstructions: "Falafel keep 3 days; tahini sauce keeps a week.",
    },
    {
      name: "Korean Bibimbap Bowl",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "bowl",
      calories: 598,
      proteinG: 36,
      carbsG: 64,
      fatG: 22,
      fiberG: 9,
      prepMinutes: 30,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Cooked white rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Beef sirloin, thinly sliced", quantity: 4, unit: "oz", section: "protein" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Bean sprouts", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Gochujang", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cook and season each vegetable separately with a little sesame oil and salt, keeping them in distinct piles.",
        "The separation is the dish. Everything tossed together is just a rice bowl.",
        "Sear the beef fast in soy and sesame oil.",
        "Arrange in wedges over hot rice with a fried egg in the middle and gochujang alongside, and mix at the table.",
      ],
      storageInstructions: "Components keep 3 days; fry the egg fresh.",
    },
    {
      name: "Buddha Bowl with Roasted Vegetables",
      mealType: "lunch",
      cuisine: "american",
      dishType: "bowl",
      calories: 552,
      proteinG: 20,
      carbsG: 70,
      fatG: 22,
      fiberG: 16,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["sesame"],
      ingredients: [
        { name: "Cooked quinoa", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Sweet potato, cubed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Canned chickpeas, drained", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Kale, shredded", quantity: 2, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Tahini", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Roast the sweet potato and chickpeas on the same tray at 425F for 30 minutes, keeping them in separate halves so neither steams the other.",
        "Massage the kale with lemon and salt for a minute until it darkens.",
        "Thin the tahini with lemon and water until pourable.",
        "Arrange in sections rather than mixing, and dress at the table.",
      ],
      storageInstructions: "Components keep 4 days; excellent meal-prep.",
    },
    {
      name: "Salmon Rice Bowl with Cucumber",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "bowl",
      calories: 590,
      proteinG: 42,
      carbsG: 58,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Salmon fillet", quantity: 6, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Cucumber, thinly sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Season the rice while hot with rice vinegar and a pinch of sugar and salt, folding with a cutting motion rather than stirring.",
        "Quick-pickle the cucumber in the remaining vinegar with salt for 10 minutes.",
        "Sear the salmon skin-side down until crisp, then flake it into large pieces.",
        "Build over the seasoned rice with avocado, cucumber, scallion, and sesame.",
      ],
      storageInstructions: "Keeps 2 days; good cold.",
    },
    {
      name: "Greek Chicken Quinoa Bowl",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "bowl",
      calories: 574,
      proteinG: 44,
      carbsG: 50,
      fatG: 22,
      fiberG: 9,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked quinoa", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Feta cheese, crumbled", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Kalamata olives, halved", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Rinse quinoa thoroughly before cooking — the saponin coating is genuinely bitter and rinsing is not optional.",
        "Marinate the chicken in lemon, oregano, and olive oil, then sear until charred at the edges.",
        "Dress the quinoa while warm so it absorbs the lemon.",
        "Assemble in sections with a spoonful of yogurt.",
      ],
      storageInstructions: "Keeps 4 days; ideal packed lunch.",
    },
    {
      name: "Spicy Tuna Rice Bowl",
      mealType: "lunch",
      cuisine: "japanese",
      dishType: "bowl",
      calories: 546,
      proteinG: 40,
      carbsG: 56,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein", "omega-3"],
      allergens: ["fish", "eggs", "soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Sushi-grade tuna, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 1, unit: "cup", section: "grains" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sriracha", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Nori sheet, shredded", quantity: 0.5, unit: "each", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Use tuna sold explicitly for raw consumption.",
        "Mix mayonnaise and sriracha first, then fold the tuna through gently so the cubes stay intact.",
        "Dress it no more than 10 minutes before eating; the salt starts firming and greying the surface.",
        "Build over warm rice with cucumber, avocado, nori, and scallion.",
      ],
      storageInstructions: "Eat the day it's made.",
    },
    {
      name: "Barbacoa Burrito Bowl",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "bowl",
      calories: 610,
      proteinG: 42,
      carbsG: 60,
      fatG: 22,
      fiberG: 13,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Cooked shredded beef barbacoa", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Canned black beans, drained", quantity: 0.66, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Sour cream", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Salsa", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Fold lime juice and cilantro through the warm rice.",
        "Warm the beans with a little of their liquid rather than draining them bone-dry, so they don't go pasty.",
        "Char the corn in a dry pan.",
        "Layer rice, beans, beef, then the cold toppings last so the lettuce doesn't wilt.",
      ],
      storageInstructions: "Keeps 4 days with toppings stored separately.",
    },
    {
      name: "Chicken Caesar Grain Bowl",
      mealType: "lunch",
      cuisine: "american",
      dishType: "bowl",
      calories: 556,
      proteinG: 42,
      carbsG: 48,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk", "eggs", "fish", "wheat"],
      ingredients: [
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked farro", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Romaine lettuce, chopped", quantity: 2, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Anchovy fillets, minced", quantity: 1, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Cook the farro in salted water until chewy, then cool.",
        "Whisk the dressing with anchovy, Dijon, lemon, mayonnaise, and Parmesan.",
        "Dress the farro first and let it sit — grains absorb dressing in a way lettuce can't, which is what makes this hold up in a lunchbox.",
        "Add the romaine and chicken just before eating.",
      ],
      storageInstructions: "Dressed farro keeps 3 days; add lettuce at serving.",
    },
    {
      name: "Peanut Chicken Rice Bowl",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "bowl",
      calories: 618,
      proteinG: 42,
      carbsG: 58,
      fatG: 24,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["peanuts", "soybeans", "wheat"],
      ingredients: [
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked brown rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Peanut butter", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Napa cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red bell pepper, julienned", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Whisk peanut butter with lime juice and warm water first, then add soy — reversing that order makes it seize into a stiff paste.",
        "Sear the chicken until well browned.",
        "Keep the vegetables raw for crunch against the soft rice.",
        "Assemble and pour the sauce over at the table so nothing goes soggy in transit.",
      ],
      storageInstructions: "Keeps 4 days with sauce stored separately.",
    },
    {
      name: "Steak and Sweet Potato Power Bowl",
      mealType: "dinner",
      cuisine: "american",
      dishType: "bowl",
      calories: 618,
      proteinG: 44,
      carbsG: 56,
      fatG: 24,
      fiberG: 11,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Sirloin steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Sweet potato, cubed", quantity: 1.25, unit: "cup", section: "produce" },
        { name: "Cooked quinoa", quantity: 0.5, unit: "cup", section: "grains" },
        { name: "Baby spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Balsamic vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Roast the sweet potato at 425F for 30 minutes until caramelized.",
        "Sear the steak 4 minutes per side and rest a full 8 minutes before slicing against the grain.",
        "Wilt the spinach in the steak pan using the residual fat and fond.",
        "Assemble over quinoa with avocado and a balsamic drizzle.",
      ],
      storageInstructions: "Keeps 3 days; slice steak cold.",
    },
    {
      name: "Harissa Chickpea and Couscous Bowl",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "bowl",
      calories: 546,
      proteinG: 20,
      carbsG: 76,
      fatG: 18,
      fiberG: 15,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat"],
      ingredients: [
        { name: "Couscous", quantity: 0.66, unit: "cup", section: "grains" },
        { name: "Canned chickpeas, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Harissa paste", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Zucchini, cubed", quantity: 1, unit: "cup", section: "produce" },
        { name: "Red bell pepper, chunked", quantity: 1, unit: "each", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh parsley, chopped", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Toss the chickpeas and vegetables with harissa, cumin, and oil and roast at 425F for 25 minutes.",
        "Pour boiling water over the couscous, cover tightly, and leave 5 minutes off the heat — couscous is steamed, never boiled.",
        "Fluff with a fork immediately, breaking up clumps while it's still hot.",
        "Fold everything together with lemon and parsley.",
      ],
      storageInstructions: "Keeps 4 days; good cold or warm.",
    },
    {
      name: "Turkey Meatball Mediterranean Bowl",
      mealType: "dinner",
      cuisine: "mediterranean",
      dishType: "bowl",
      calories: 584,
      proteinG: 44,
      carbsG: 54,
      fatG: 22,
      fiberG: 9,
      prepMinutes: 20,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Ground turkey (93% lean)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Cooked couscous", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Breadcrumbs", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 0.5, unit: "each", section: "protein" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Mix the turkey with breadcrumbs, egg, oregano, and plenty of salt, handling it as little as possible.",
        "Wet your hands to roll the meatballs — lean turkey sticks to dry hands and you end up compacting them.",
        "Bake at 400F for 18 minutes, or brown in a pan and finish covered.",
        "Assemble over couscous with yogurt, cucumber, tomato, and lemon.",
      ],
      storageInstructions: "Meatballs keep 4 days and freeze 2 months.",
    },
    {
      name: "Crispy Tofu Rice Bowl with Sriracha Mayo",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "bowl",
      calories: 596,
      proteinG: 28,
      carbsG: 62,
      fatG: 26,
      fiberG: 9,
      prepMinutes: 25,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein"],
      allergens: ["soybeans", "wheat", "eggs", "sesame"],
      ingredients: [
        { name: "Extra-firm tofu, cubed", quantity: 7, unit: "oz", section: "protein" },
        { name: "Cooked white rice", quantity: 0.75, unit: "cup", section: "grains" },
        { name: "Cornstarch", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sriracha", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Edamame, shelled", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cucumber, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Press the tofu 20 minutes under something heavy, then toss the cubes in cornstarch until chalky.",
        "Fry in a shallow layer of hot oil, turning only when each face releases on its own.",
        "Toss in soy sauce off the heat, immediately before serving — sauce it early and the crust you just built dissolves.",
        "Mix mayonnaise and sriracha and drizzle over the assembled bowl.",
      ],
      storageInstructions: "Keeps 3 days; re-crisp the tofu in a hot pan.",
    },
  ],
};
