import type { RecipeContentBatch } from "@/domains/recipes/content-spec";

/**
 * Popularity expansion batch 4a of 4 (2026-08-16) — noodles, tacos, wraps.
 *
 * Weighted to weekday-dinner forms rather than snacks: `noodles` held 8,
 * `tacos` 7, and `wrap` 9, while the snack buckets were already the
 * healthiest in the library. These are the three forms someone reaches
 * for on a Tuesday.
 *
 * Corn tortillas are used wherever the dish traditionally calls for them,
 * which also keeps those recipes wheat-free — validate-spec.ts knows
 * "corn tortilla" is exempt from the wheat keyword, so the tagging here
 * is accurate rather than defensively over-broad.
 *
 * Macros satisfy calories = 4p + 4c + 9f exactly.
 */
export const batch: RecipeContentBatch = {
  recipes: [
    // ---------------------------------------------------------------
    // Noodles
    // ---------------------------------------------------------------
    {
      name: "Beef Lo Mein",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 562,
      proteinG: 36,
      carbsG: 64,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "sesame", "shellfish"],
      ingredients: [
        { name: "Lo mein noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Oyster sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Napa cabbage, shredded", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Cornstarch", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Velvet the beef: toss the slices with cornstarch and a splash of soy and let sit 15 minutes. This is the restaurant technique that keeps stir-fried beef tender rather than grey and tough.",
        "Cook the noodles a minute short and rinse in cold water so they don't clump.",
        "Get the wok genuinely smoking before anything goes in, and cook the beef in one layer without stirring for 45 seconds.",
        "Add vegetables, then noodles and sauce, tossing constantly for 2 minutes.",
      ],
      storageInstructions: "Keeps 3 days; refresh with a splash of water in a hot pan.",
    },
    {
      name: "Chicken Chow Mein",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 554,
      proteinG: 38,
      carbsG: 60,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Chow mein noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Bean sprouts", quantity: 1, unit: "cup", section: "produce" },
        { name: "Celery, sliced on the bias", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "The difference between chow mein and lo mein is the noodle treatment: here they're pan-fried until crisp at the edges, not just tossed.",
        "Par-cook and dry the noodles, then press them into a hot oiled pan and leave for 3 minutes to crisp.",
        "Flip, crisp the other side, and set aside.",
        "Stir-fry chicken and vegetables fast over high heat, then fold the noodles back in with the sauce.",
        "Add bean sprouts in the last 30 seconds so they stay squeaky.",
      ],
      storageInstructions: "Keeps 3 days; the noodles soften and won't re-crisp.",
    },
    {
      name: "Dan Dan Noodles",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 592,
      proteinG: 32,
      carbsG: 62,
      fatG: 24,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "sesame", "peanuts"],
      ingredients: [
        { name: "Wheat noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Ground pork", quantity: 4, unit: "oz", section: "protein" },
        { name: "Tahini", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Peanut butter", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Chili oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Sichuan peppercorns, ground", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Preserved mustard greens", quantity: 2, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Fry the pork hard until genuinely crisp and browned, not just cooked — the crumbly texture is the point.",
        "Whisk tahini, peanut butter, soy sauce, chili oil, and a few tablespoons of hot noodle water into a pourable sauce.",
        "Toast and grind the Sichuan peppercorns fresh; the numbing tingle fades fast once ground.",
        "Pool the sauce in the bottom of the bowl, pile noodles on top, then pork and scallion. Toss at the table.",
      ],
      storageInstructions: "Sauce keeps a week; cook noodles fresh.",
    },
    {
      name: "Garlic Sesame Noodles",
      mealType: "lunch",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 474,
      proteinG: 16,
      carbsG: 62,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Wheat noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sesame seeds", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Cucumber, julienned", quantity: 0.5, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Heat the sesame oil until it just shimmers, then pour it over the raw minced garlic in a bowl.",
        "This blooms the garlic without frying it — fried garlic goes bitter and sweet, raw garlic stays harsh, and this middle path is what you want.",
        "Whisk in soy sauce and rice vinegar.",
        "Toss with hot drained noodles, then let them cool to room temperature before adding cucumber and scallion.",
      ],
      storageInstructions: "Keeps 3 days and is designed to be eaten cold.",
    },
    {
      name: "Singapore Curry Noodles",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 522,
      proteinG: 32,
      carbsG: 58,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "wheat", "soybeans", "eggs"],
      ingredients: [
        { name: "Rice vermicelli noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Shrimp, peeled", quantity: 3, unit: "oz", section: "protein" },
        { name: "Char siu pork, sliced", quantity: 2, unit: "oz", section: "protein" },
        { name: "Curry powder", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Egg, beaten", quantity: 1, unit: "each", section: "protein" },
        { name: "Red bell pepper, julienned", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Bean sprouts", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Soak the vermicelli in hot water rather than boiling it; these noodles turn to paste in a pot in about 90 seconds.",
        "Bloom the curry powder in hot oil for 30 seconds before anything else — dumped in later it tastes raw and dusty.",
        "Scramble the egg, remove, then stir-fry the proteins and vegetables over high heat.",
        "Add the drained noodles and toss with tongs, lifting rather than stirring so they don't break up.",
      ],
      storageInstructions: "Keeps 3 days; good cold.",
    },
    {
      name: "Yakisoba with Pork",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 564,
      proteinG: 34,
      carbsG: 62,
      fatG: 20,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans"],
      ingredients: [
        { name: "Yakisoba noodles", quantity: 3.5, unit: "oz", section: "grains" },
        { name: "Pork belly, thinly sliced", quantity: 3, unit: "oz", section: "protein" },
        { name: "Worcestershire sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Green cabbage, chopped", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Pickled red ginger", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Render the pork belly first and cook everything else in its fat.",
        "Yakisoba sauce is essentially Worcestershire-based, not soy-based — the tang is what distinguishes it from every other stir-fried noodle.",
        "Cook the cabbage and onion until just wilted but still with bite.",
        "Add noodles and sauce and toss over high heat until glossy and slightly caramelized in spots.",
        "Top with pickled ginger, which cuts the richness.",
      ],
      storageInstructions: "Keeps 2 days; reheat in a hot pan.",
    },
    {
      name: "Shoyu Ramen with Chashu Pork",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 606,
      proteinG: 40,
      carbsG: 62,
      fatG: 22,
      fiberG: 5,
      prepMinutes: 30,
      cookMinutes: 120,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "eggs"],
      ingredients: [
        { name: "Ramen noodles", quantity: 3.5, unit: "oz", section: "grains" },
        { name: "Pork belly", quantity: 4, unit: "oz", section: "protein" },
        { name: "Soy sauce", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Chicken broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Fresh ginger, sliced", quantity: 1, unit: "inch", section: "produce" },
        { name: "Nori sheet", quantity: 1, unit: "each", section: "pantry" },
        { name: "Mirin", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Roll and tie the pork belly, then braise it in soy sauce, mirin, ginger, and water for 2 hours until a skewer slides through.",
        "Make the jammy egg: exactly 6.5 minutes in boiling water, then straight into ice water, then marinate in the cooled braising liquid for at least an hour.",
        "Build the bowl in order: tare (seasoned soy) in the bottom, then hot broth, then noodles, then toppings. Ramen is assembled, not simmered together.",
        "Cook the noodles for the time on the packet and not a second more — 30 seconds over and the texture is gone.",
      ],
      storageInstructions: "Chashu and eggs keep 4 days in the braising liquid; assemble bowls fresh.",
    },
    {
      name: "Miso Ramen with Corn and Butter",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 582,
      proteinG: 32,
      carbsG: 64,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "milk", "eggs"],
      ingredients: [
        { name: "Ramen noodles", quantity: 3.5, unit: "oz", section: "grains" },
        { name: "White miso paste", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Ground pork", quantity: 3, unit: "oz", section: "protein" },
        { name: "Corn kernels", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Chicken broth", quantity: 2, unit: "cup", section: "pantry" },
        { name: "Bean sprouts", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
      ],
      instructions: [
        "Brown the ground pork, then stir the miso into the pork fat and cook 30 seconds to deepen it.",
        "Add broth and warm through, but never let miso boil — boiling flattens its aroma and makes it grainy.",
        "Cook the noodles separately in plain water; cooking them in the broth clouds it with starch.",
        "Top with corn, bean sprouts, a jammy egg, scallion, and a pat of butter melting into the surface.",
      ],
      storageInstructions: "Broth keeps 4 days; assemble fresh.",
    },
    {
      name: "Cold Soba with Dipping Sauce",
      mealType: "lunch",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 416,
      proteinG: 20,
      carbsG: 66,
      fatG: 8,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: [],
      allergens: ["wheat", "soybeans", "fish"],
      ingredients: [
        { name: "Soba noodles", quantity: 3.5, unit: "oz", section: "grains" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Mirin", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Bonito flakes", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Nori sheet, shredded", quantity: 0.5, unit: "each", section: "pantry" },
        { name: "Wasabi", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tsp", section: "produce" },
      ],
      instructions: [
        "Make the tsuyu by simmering soy, mirin, and water with bonito flakes for 5 minutes, then straining and chilling completely.",
        "Boil the soba and then rinse it under cold running water while rubbing the strands with your hands.",
        "That rinse is essential — it strips the surface starch and is what makes cold soba clean-tasting rather than gummy.",
        "Serve the noodles drained on a rack or basket with the cold sauce alongside for dipping, plus scallion, ginger, and wasabi.",
      ],
      storageInstructions: "Tsuyu keeps 2 weeks refrigerated; cook noodles fresh.",
    },
    {
      name: "Udon Noodle Stir-Fry with Vegetables",
      mealType: "dinner",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 496,
      proteinG: 18,
      carbsG: 70,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Udon noodles", quantity: 5, unit: "oz", section: "grains" },
        { name: "Shiitake mushrooms, sliced", quantity: 1, unit: "cup", section: "produce" },
        { name: "Baby bok choy, halved", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Mirin", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Udon are thick and fragile — separate them gently under warm water and never boil them hard for a stir-fry.",
        "Sear the mushrooms until browned before adding anything wet.",
        "Add the bok choy stems first and the leaves 90 seconds later.",
        "Toss in the udon with soy, mirin, and sesame oil, using tongs and a lifting motion; a spatula will snap them.",
      ],
      storageInstructions: "Keeps 3 days; noodles firm up when cold and soften on reheating.",
    },
    {
      name: "Spicy Peanut Noodles with Chicken",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "noodles",
      calories: 600,
      proteinG: 38,
      carbsG: 58,
      fatG: 24,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["peanuts", "soybeans", "wheat", "fish"],
      ingredients: [
        { name: "Rice noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Peanut butter", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Fish sauce", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Sriracha", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Red bell pepper, julienned", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Whisk the peanut butter with lime juice and hot water first, before adding the salty ingredients — it emulsifies far more easily that way.",
        "Soak rice noodles in hot water until pliable but still firm; they finish in the pan.",
        "Stir-fry the chicken and pepper over high heat.",
        "Add noodles and sauce and toss until coated, thinning with water as it thickens on contact with heat.",
      ],
      storageInstructions: "Keeps 3 days; sauce thickens, so loosen with water.",
    },
    {
      name: "Pad Woon Sen with Glass Noodles",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "noodles",
      calories: 496,
      proteinG: 32,
      carbsG: 56,
      fatG: 16,
      fiberG: 5,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["eggs", "fish", "soybeans", "wheat"],
      ingredients: [
        { name: "Glass noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Ground chicken", quantity: 4, unit: "oz", section: "protein" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Fish sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Napa cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Tomato, wedged", quantity: 1, unit: "each", section: "produce" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "White pepper", quantity: 0.25, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Soak the glass noodles in warm water 10 minutes until flexible — they're mung bean starch and turn to jelly if actually boiled.",
        "Cut them roughly with scissors after soaking, or the dish becomes impossible to eat.",
        "Scramble the egg, push aside, then brown the chicken.",
        "Add noodles, sauces, and vegetables and toss over high heat for 2 minutes until the noodles turn translucent.",
      ],
      storageInstructions: "Keeps 2 days; glass noodles absorb sauce and stiffen.",
    },
    {
      name: "Rice Noodle Stir-Fry with Beef and Basil",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "noodles",
      calories: 546,
      proteinG: 36,
      carbsG: 60,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "soybeans", "wheat", "shellfish"],
      ingredients: [
        { name: "Wide rice noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Fish sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh Thai basil", quantity: 1, unit: "cup", section: "produce" },
        { name: "Thai chili, sliced", quantity: 2, unit: "each", section: "produce" },
        { name: "Garlic, minced", quantity: 4, unit: "clove", section: "produce" },
        { name: "Green beans, cut", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Oyster sauce", quantity: 1, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Fresh wide rice noodles need no soaking; dried ones need 20 minutes in warm water.",
        "Get the pan as hot as it will go. Wok hei — that faintly smoky char — only happens above the temperature most home burners comfortably reach, so work in one small batch.",
        "Sear the beef, remove, then the aromatics and beans.",
        "Return everything with the noodles and sauces, tossing for 90 seconds, and kill the heat before folding in the basil so it wilts rather than blackens.",
      ],
      storageInstructions: "Best fresh; keeps 2 days.",
    },
    {
      name: "Chili Oil Noodles",
      mealType: "lunch",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 500,
      proteinG: 16,
      carbsG: 64,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Wheat noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chili flakes", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Vegetable oil", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Black vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Pile the chili flakes, garlic, scallion whites, and sesame seeds in the bottom of a heatproof bowl.",
        "Heat the oil until it just begins to shimmer and wisp — around 350F. Too cool and nothing happens; too hot and the garlic burns black instantly.",
        "Pour it over the aromatics. It should sizzle violently for several seconds.",
        "Add soy sauce and black vinegar, then toss with hot noodles and the scallion greens.",
      ],
      storageInstructions: "Chili oil keeps a month in a jar; noodles fresh.",
    },
    {
      name: "Japchae Sweet Potato Noodles",
      mealType: "dinner",
      cuisine: "chinese",
      dishType: "noodles",
      calories: 512,
      proteinG: 26,
      carbsG: 66,
      fatG: 16,
      fiberG: 6,
      prepMinutes: 25,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["soybeans", "wheat", "sesame", "eggs"],
      ingredients: [
        { name: "Sweet potato glass noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Beef sirloin, thinly sliced", quantity: 3, unit: "oz", section: "protein" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Spinach", quantity: 2, unit: "cup", section: "produce" },
        { name: "Shiitake mushrooms, sliced", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook each component separately and season each one lightly as you go. This is laborious and it is the entire method — everything thrown in one pan gives you a muddy, uniform dish.",
        "Boil the noodles 6 minutes, rinse, and cut once with scissors.",
        "Blanch and squeeze the spinach, sear the mushrooms, soften the carrot, cook the beef, and make a thin egg crepe to slice into ribbons.",
        "Toss everything together with soy sauce and sesame oil at the end.",
      ],
      storageInstructions: "Keeps 4 days and is traditionally served at room temperature.",
    },
    {
      name: "Curry Laksa Noodles",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "noodles",
      calories: 594,
      proteinG: 32,
      carbsG: 58,
      fatG: 26,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["shellfish", "fish", "soybeans", "wheat"],
      ingredients: [
        { name: "Rice vermicelli noodles", quantity: 2.5, unit: "oz", section: "grains" },
        { name: "Shrimp, peeled", quantity: 4, unit: "oz", section: "protein" },
        { name: "Light coconut milk", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Red curry paste", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Fish sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Extra-firm tofu, cubed", quantity: 2, unit: "oz", section: "protein" },
        { name: "Bean sprouts", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Chicken broth", quantity: 1, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Fry the curry paste in a little oil until the oil separates and turns red — this takes 3-4 minutes and is where the flavour comes from.",
        "Add coconut milk and broth and simmer 10 minutes without boiling hard, which would split the coconut milk.",
        "Poach the shrimp in the broth for 2 minutes at the end.",
        "Soak the vermicelli separately and assemble in the bowl with bean sprouts, tofu, and lime.",
      ],
      storageInstructions: "Broth keeps 3 days; assemble fresh.",
    },
    {
      name: "Sesame Ginger Soba with Chicken",
      mealType: "lunch",
      cuisine: "japanese",
      dishType: "noodles",
      calories: 502,
      proteinG: 36,
      carbsG: 58,
      fatG: 14,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "soybeans", "sesame"],
      ingredients: [
        { name: "Soba noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh ginger, grated", quantity: 1, unit: "tbsp", section: "produce" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Snap peas", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Carrot, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Boil the soba, then rinse thoroughly in cold water — soba sheds a lot of starch and gets slimy without it.",
        "Poach or sear the chicken and slice.",
        "Blanch the snap peas 60 seconds and shock them.",
        "Whisk soy, sesame oil, ginger, and vinegar and toss everything together cold.",
      ],
      storageInstructions: "Keeps 3 days; excellent packed for lunch.",
    },
    {
      name: "Vegetable Pad Thai with Tofu",
      mealType: "dinner",
      cuisine: "thai",
      dishType: "noodles",
      calories: 530,
      proteinG: 24,
      carbsG: 68,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["peanuts", "soybeans", "eggs", "wheat"],
      ingredients: [
        { name: "Rice noodles", quantity: 3, unit: "oz", section: "grains" },
        { name: "Extra-firm tofu, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Egg", quantity: 1, unit: "each", section: "protein" },
        { name: "Tamarind paste", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Peanuts, crushed", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Bean sprouts", quantity: 1, unit: "cup", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Palm sugar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
      ],
      instructions: [
        "Tamarind is not optional — the sour-sweet balance from tamarind, sugar, and soy is what makes pad thai taste like pad thai rather than sweet noodles.",
        "Soak the noodles in warm water until pliable but distinctly underdone.",
        "Press and sear the tofu until golden on at least two sides, then remove.",
        "Scramble the egg, add noodles and sauce, and toss constantly for 2 minutes until the noodles soften and absorb it.",
        "Kill the heat and fold in bean sprouts, peanuts, scallion, and lime.",
      ],
      storageInstructions: "Keeps 3 days; noodles firm up when cold.",
    },

    // ---------------------------------------------------------------
    // Tacos
    // ---------------------------------------------------------------
    {
      name: "Carne Asada Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 516,
      proteinG: 42,
      carbsG: 42,
      fatG: 20,
      fiberG: 8,
      prepMinutes: 20,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Skirt steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 2, unit: "each", section: "produce" },
        { name: "Cotija cheese, crumbled", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Salsa verde", quantity: 3, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Marinate the skirt in lime, cumin, salt, and pepper for 30 minutes.",
        "Grill or sear over the highest heat 2-3 minutes per side, then rest 10 minutes and chop finely across the grain.",
        "Warm the tortillas directly over a flame until they blister and puff. A cold tortilla from the bag is the single biggest difference between home tacos and street tacos.",
        "Double up the tortillas — one alone tears under the filling.",
        "Top with onion, cilantro, cotija, salsa, and lime. Nothing else.",
      ],
      storageInstructions: "Steak keeps 3 days; warm tortillas to order.",
    },
    {
      name: "Al Pastor Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 532,
      proteinG: 40,
      carbsG: 48,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 30,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork shoulder, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Pineapple, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Dried guajillo chiles", quantity: 3, unit: "each", section: "pantry" },
        { name: "Achiote paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Pineapple juice", quantity: 3, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Toast and soak the guajillos, then blend with achiote and pineapple juice into a marinade.",
        "Marinate the sliced pork at least 4 hours, ideally overnight. The bromelain in the pineapple juice tenderizes it, so don't go beyond 24 hours or it turns mushy.",
        "Sear hard in a very hot pan in a single layer to mimic the char of a vertical spit.",
        "Char the pineapple separately and chop it small.",
        "Serve on warmed corn tortillas with onion, cilantro, and lime.",
      ],
      storageInstructions: "Marinated raw pork keeps 2 days; cooked keeps 4.",
    },
    {
      name: "Carnitas Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 534,
      proteinG: 40,
      carbsG: 44,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 180,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Pork shoulder, cubed", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Orange", quantity: 1, unit: "each", section: "produce" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Bay leaf", quantity: 2, unit: "each", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Simmer the pork with orange juice, the spent orange halves, bay, cumin, and salt, barely covered in water, for about 2.5 hours.",
        "Let the liquid cook away completely, then keep going. The pork now fries in its own rendered fat — this is the step that makes carnitas rather than boiled pork.",
        "Shred coarsely and crisp the edges under a broiler or in the pan.",
        "Serve on warm corn tortillas with onion, cilantro, and lime.",
      ],
      storageInstructions: "Keeps 4 days and freezes 3 months; re-crisp before serving.",
    },
    {
      name: "Barbacoa Beef Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 526,
      proteinG: 42,
      carbsG: 40,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 210,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Beef chuck", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Chipotle in adobo", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Dried ancho chile", quantity: 2, unit: "each", section: "pantry" },
        { name: "Ground cloves", quantity: 0.125, unit: "tsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Blend soaked anchos, chipotle, vinegar, cloves, and garlic into a marinade.",
        "Braise the chuck in it, tightly covered, at 300F for 3.5 hours.",
        "The cloves are unusual and load-bearing — a tiny amount gives barbacoa its warm, slightly medicinal note, and too much ruins it.",
        "Shred and moisten with the strained braising liquid.",
        "Serve on warm tortillas with onion, cilantro, and lime.",
      ],
      storageInstructions: "Keeps 4 days in its liquid and freezes 3 months.",
    },
    {
      name: "Baja Fish Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 558,
      proteinG: 34,
      carbsG: 56,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "wheat", "eggs", "milk"],
      ingredients: [
        { name: "Cod fillet, cut into strips", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "All-purpose flour", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Sparkling water", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Vegetable oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Chipotle in adobo, minced", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Make the batter with ice-cold sparkling water and don't overmix; lumps are fine and cold is what makes it crisp.",
        "Dust the dried fish in dry flour first so the batter grips.",
        "Fry at 350F for 3-4 minutes until deep gold and drain on a rack, not paper towel.",
        "Whisk mayonnaise, lime, and chipotle into a crema, and dress the cabbage separately with lime.",
        "Assemble immediately — battered fish goes soft within minutes of hitting a wet topping.",
      ],
      storageInstructions: "Eat immediately; crema keeps 5 days.",
    },
    {
      name: "Shrimp Tacos with Cabbage Slaw",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 464,
      proteinG: 36,
      carbsG: 44,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 8,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["shellfish", "milk"],
      ingredients: [
        { name: "Shrimp, peeled and deveined", quantity: 6, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Green cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Chili powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Toss the shrimp with chili powder and salt and sear 90 seconds per side over high heat.",
        "Dress the cabbage with lime and salt 10 minutes ahead so it softens slightly but stays crunchy.",
        "Thin the yogurt with lime juice for a drizzling crema.",
        "Warm the tortillas over a flame and build with slaw first, shrimp on top, then avocado and crema.",
      ],
      storageInstructions: "Components keep 2 days; assemble at serving.",
    },
    {
      name: "Chicken Fajita Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 488,
      proteinG: 42,
      carbsG: 44,
      fatG: 16,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Red bell pepper, sliced", quantity: 1, unit: "each", section: "produce" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Chili powder", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Sour cream", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Cook the peppers and onion FIRST, in a dry-ish hot pan, until charred at the edges, and remove.",
        "Then cook the chicken. Cooking them together means the vegetables release water and the chicken poaches instead of browning.",
        "Combine at the end with lime juice and the spices.",
        "Warm the tortillas and serve with sour cream.",
      ],
      storageInstructions: "Keeps 3 days; good in bowls or wraps too.",
    },
    {
      name: "Classic Ground Beef Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 518,
      proteinG: 38,
      carbsG: 42,
      fatG: 22,
      fiberG: 7,
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Lean ground beef (90/10)", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Chili powder", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Tomato paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Romaine lettuce, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Tomato, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Beef broth", quantity: 0.25, unit: "cup", section: "pantry" },
      ],
      instructions: [
        "Brown the beef hard and drain the fat.",
        "Add the spices and tomato paste to the dry pan and cook a full minute before any liquid — this is what a seasoning packet does badly.",
        "Add the broth and simmer until it reduces to a glaze that clings to the meat rather than pooling.",
        "Warm the tortillas and build with lettuce, tomato, and cheese.",
      ],
      storageInstructions: "Meat keeps 4 days and freezes 3 months.",
    },
    {
      name: "Birria Tacos with Consomé",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 568,
      proteinG: 42,
      carbsG: 46,
      fatG: 24,
      fiberG: 8,
      prepMinutes: 30,
      cookMinutes: 210,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Beef chuck", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Dried guajillo chiles", quantity: 4, unit: "each", section: "pantry" },
        { name: "Dried ancho chile", quantity: 1, unit: "each", section: "pantry" },
        { name: "Shredded Monterey Jack cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Bay leaf", quantity: 2, unit: "each", section: "pantry" },
      ],
      instructions: [
        "Toast, soak, and blend the chiles, then strain the purée — unstrained, the skins make the consomé gritty.",
        "Braise the beef in the purée with cumin and bay for 3.5 hours until it shreds.",
        "Skim the bright red fat off the surface and RESERVE it. That fat is what you dip the tortillas in.",
        "Dip each tortilla in the reserved fat, griddle it, add beef and cheese, and fold.",
        "Serve with a cup of the strained consomé, onion, and cilantro for dipping.",
      ],
      storageInstructions: "Beef and consomé keep 4 days and freeze 3 months.",
    },
    {
      name: "Sweet Potato and Black Bean Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 470,
      proteinG: 18,
      carbsG: 68,
      fatG: 14,
      fiberG: 16,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Sweet potato, diced", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Canned black beans, drained", quantity: 0.75, unit: "cup", section: "pantry" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Ground cumin", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Roast the sweet potato at 425F for 25-30 minutes until the edges genuinely caramelize. Undercooked, it's the difference between a great vegetable taco and a boring one.",
        "Warm the beans with cumin and smoked paprika and mash a third for texture.",
        "Warm the tortillas over a flame.",
        "Build with beans, sweet potato, avocado, cilantro, and a hard squeeze of lime.",
      ],
      storageInstructions: "Filling keeps 4 days; assemble at serving.",
    },
    {
      name: "Mushroom Barbacoa Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 432,
      proteinG: 16,
      carbsG: 56,
      fatG: 16,
      fiberG: 12,
      prepMinutes: 20,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: [],
      ingredients: [
        { name: "Oyster mushrooms, torn", quantity: 3, unit: "cup", section: "produce" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Chipotle in adobo, minced", quantity: 2, unit: "tsp", section: "pantry" },
        { name: "Canned pinto beans, drained", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Tear the mushrooms by hand into strips rather than slicing — the ragged edges catch and crisp the way shredded meat does.",
        "Roast at 425F for 25 minutes until deeply browned and reduced by half. They must lose their water before any sauce goes on.",
        "Toss the roasted mushrooms with chipotle, cumin, and vinegar and return to the oven 5 minutes.",
        "Serve with warm beans, onion, and lime.",
      ],
      storageInstructions: "Keeps 3 days; re-crisp in a hot pan.",
    },
    {
      name: "Chorizo and Potato Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 554,
      proteinG: 32,
      carbsG: 48,
      fatG: 26,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 25,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["milk"],
      ingredients: [
        { name: "Mexican chorizo", quantity: 3.5, unit: "oz", section: "protein" },
        { name: "Yukon gold potato, diced small", quantity: 1.25, unit: "cup", section: "produce" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Queso fresco, crumbled", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Salsa verde", quantity: 3, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Cook the fresh Mexican chorizo (not the cured Spanish kind, which won't crumble) until it renders its bright orange fat.",
        "Cook the diced potato IN that fat, pressing it flat and leaving it alone to crisp, about 12 minutes.",
        "Fold the chorizo back in.",
        "Serve on warm tortillas with queso fresco, onion, cilantro, and salsa verde.",
      ],
      storageInstructions: "Keeps 3 days; re-crisp in a pan.",
    },
    {
      name: "Grilled Steak Tostadas",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 518,
      proteinG: 40,
      carbsG: 40,
      fatG: 22,
      fiberG: 9,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Flank steak", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Refried pinto beans", quantity: 0.5, unit: "cup", section: "pantry" },
        { name: "Romaine lettuce, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Cotija cheese, crumbled", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Sour cream", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Salsa", quantity: 3, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Bake the tortillas at 400F for 10 minutes, flipping once, until rigid and snapping-crisp. Frying works too, but baking is cleaner and just as good here.",
        "Grill the steak, rest 10 minutes, and slice thin against the grain.",
        "Spread warm refried beans on each tostada first — they act as glue and stop everything sliding off.",
        "Layer lettuce, steak, salsa, cotija, and sour cream.",
      ],
      storageInstructions: "Tostada shells keep a week in a sealed container.",
    },
    {
      name: "Pollo Asado Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 498,
      proteinG: 44,
      carbsG: 40,
      fatG: 18,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 20,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: [],
      ingredients: [
        { name: "Chicken thighs, boneless", quantity: 6, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Orange", quantity: 1, unit: "each", section: "produce" },
        { name: "Achiote paste", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Garlic, minced", quantity: 3, unit: "clove", section: "produce" },
        { name: "White onion, minced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 4, unit: "tbsp", section: "produce" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Whisk achiote with orange juice, lime, garlic, and oregano and marinate the thighs 2-4 hours.",
        "Achiote is what gives pollo asado its brick-red colour; paprika is not a substitute for the flavour, only the colour.",
        "Grill over medium-high 8 minutes per side until charred at the edges and 175F.",
        "Rest, chop, and serve on warm tortillas with onion, cilantro, and lime.",
      ],
      storageInstructions: "Keeps 4 days; excellent in bowls the next day.",
    },
    {
      name: "Roasted Cauliflower Tacos with Chipotle Crema",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 458,
      proteinG: 16,
      carbsG: 58,
      fatG: 18,
      fiberG: 13,
      prepMinutes: 15,
      cookMinutes: 30,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["milk"],
      ingredients: [
        { name: "Cauliflower florets", quantity: 3, unit: "cup", section: "produce" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Chipotle in adobo, minced", quantity: 1.5, unit: "tsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Smoked paprika", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Olive oil", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Lime", quantity: 1.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cut the cauliflower into flat-sided pieces rather than round florets — flat faces make contact with the pan and brown.",
        "Toss with oil and spices and roast at 450F for 25-30 minutes without stirring for the first 20.",
        "You want dark brown, almost-burnt edges. Pale cauliflower tastes of nothing and is why most versions of this taco disappoint.",
        "Whisk yogurt with chipotle and lime and serve with shredded cabbage.",
      ],
      storageInstructions: "Roasted cauliflower keeps 3 days; re-crisp in a hot oven.",
    },
    {
      name: "Korean Beef Bulgogi Tacos",
      mealType: "dinner",
      cuisine: "mexican",
      dishType: "tacos",
      calories: 524,
      proteinG: 40,
      carbsG: 46,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 25,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["soybeans", "wheat", "sesame"],
      ingredients: [
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Corn tortilla", quantity: 3, unit: "each", section: "bakery" },
        { name: "Soy sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Asian pear, grated", quantity: 0.25, unit: "each", section: "produce" },
        { name: "Toasted sesame oil", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Green cabbage, shredded", quantity: 0.75, unit: "cup", section: "produce" },
        { name: "Scallion, sliced", quantity: 3, unit: "each", section: "produce" },
        { name: "Rice vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Sesame seeds", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Grate the Asian pear into the marinade — its enzymes tenderize the beef and it's the traditional ingredient, not a garnish.",
        "Marinate the sliced sirloin in soy, pear, sesame oil, and garlic for 1-4 hours.",
        "Sear in a screaming-hot pan in a single thin layer so it caramelizes rather than stews.",
        "Dress the cabbage with rice vinegar for a sharp, quick slaw, and build on warm corn tortillas.",
      ],
      storageInstructions: "Marinated raw beef keeps 2 days; cooked keeps 3.",
    },

    // ---------------------------------------------------------------
    // Wraps
    // ---------------------------------------------------------------
    {
      name: "Chicken Caesar Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 534,
      proteinG: 40,
      carbsG: 44,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs", "fish"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Romaine lettuce, chopped", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Grated Parmesan", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Anchovy fillets, minced", quantity: 1, unit: "each", section: "protein" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Sear and slice the chicken, then let it cool. Hot filling steams a wrap from the inside and makes the tortilla gummy.",
        "Whisk mayonnaise, anchovy, Dijon, lemon, and Parmesan into a dressing.",
        "Warm the tortilla for 10 seconds to make it pliable, then lay filling in a band across the lower third.",
        "Fold the sides in first, then roll tightly from the bottom, and cut on the diagonal.",
      ],
      storageInstructions: "Wrap tightly in foil; keeps half a day before the lettuce wilts.",
    },
    {
      name: "Buffalo Chicken Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 508,
      proteinG: 40,
      carbsG: 42,
      fatG: 20,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Buffalo hot sauce", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Blue cheese dressing", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Celery, thinly sliced", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.25, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Cook and slice the chicken, then toss in buffalo sauce off the heat.",
        "Spread the dressing on the tortilla first — it's a moisture barrier between the sauce and the bread.",
        "Add lettuce next, then chicken, so the sauce never touches the tortilla directly.",
        "Roll tightly and toast seam-side down in a dry pan for 2 minutes to seal it.",
      ],
      storageInstructions: "Best fresh; components keep 3 days.",
    },
    {
      name: "Mediterranean Veggie Wrap",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "wrap",
      calories: 466,
      proteinG: 18,
      carbsG: 58,
      fatG: 18,
      fiberG: 11,
      prepMinutes: 15,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegetarian", "high-fiber"],
      allergens: ["wheat", "milk", "sesame"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Hummus", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Feta cheese, crumbled", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Cucumber, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cherry tomatoes, halved", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Kalamata olives, sliced", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Baby spinach", quantity: 1, unit: "cup", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Salt the diced cucumber and tomato and drain them 10 minutes — this is the difference between a wrap and a soggy tube.",
        "Spread hummus edge to edge as the moisture barrier.",
        "Layer spinach, then the drained vegetables, feta, and olives.",
        "Roll tightly and cut on the diagonal.",
      ],
      storageInstructions: "Keeps half a day wrapped tightly; components keep 3 days.",
    },
    {
      name: "Chicken Shawarma Wrap",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "wrap",
      calories: 532,
      proteinG: 40,
      carbsG: 48,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 20,
      cookMinutes: 18,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "sesame"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Greek yogurt", quantity: 2, unit: "tbsp", section: "dairy" },
        { name: "Tahini", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Ground coriander", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Turmeric", quantity: 0.5, unit: "tsp", section: "pantry" },
        { name: "Tomato, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
        { name: "Pickled turnips", quantity: 2, unit: "tbsp", section: "pantry" },
      ],
      instructions: [
        "Marinate the thighs in half the yogurt with cumin, coriander, and turmeric for at least 2 hours.",
        "Sear hard until charred at the edges, then rest and slice thin.",
        "Thin the remaining yogurt with tahini and lemon into a sauce.",
        "The pickles are not optional — shawarma is rich and needs something sharp, which is why every shop includes them.",
      ],
      storageInstructions: "Chicken keeps 4 days; sauce keeps 5.",
    },
    {
      name: "BLT Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 446,
      proteinG: 22,
      carbsG: 40,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: [],
      allergens: ["wheat", "eggs"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Bacon", quantity: 3, unit: "slice", section: "protein" },
        { name: "Romaine lettuce, shredded", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Tomato, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Mayonnaise", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cook the bacon crisp and drain it well — limp bacon in a wrap is unpleasant to bite through.",
        "Salt and drain the diced tomato 10 minutes.",
        "Spread mayonnaise across the whole tortilla, then mash avocado over the center.",
        "Layer lettuce, tomato, bacon, and roll tightly.",
      ],
      storageInstructions: "Assemble to order.",
    },
    {
      name: "Southwest Chicken Wrap",
      mealType: "lunch",
      cuisine: "mexican",
      dishType: "wrap",
      calories: 524,
      proteinG: 40,
      carbsG: 46,
      fatG: 20,
      fiberG: 10,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein", "high-fiber"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Canned black beans, drained", quantity: 0.33, unit: "cup", section: "pantry" },
        { name: "Corn kernels", quantity: 0.25, unit: "cup", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.75, unit: "oz", section: "dairy" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Salsa", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Ground cumin", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lime", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Char the corn in a dry pan before it goes in — 2 minutes changes it completely.",
        "Cook the chicken with cumin and let it cool slightly.",
        "Drain the salsa in a sieve before using it, or the wrap leaks.",
        "Build, roll tightly, and griddle seam-side down for 2 minutes per side to seal and crisp.",
      ],
      storageInstructions: "Keeps a day wrapped in foil; griddle to refresh.",
    },
    {
      name: "Greek Chicken Gyro Wrap",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "wrap",
      calories: 542,
      proteinG: 40,
      carbsG: 46,
      fatG: 22,
      fiberG: 6,
      prepMinutes: 20,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Pita bread", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken thighs, boneless", quantity: 5, unit: "oz", section: "protein" },
        { name: "Greek yogurt", quantity: 3, unit: "tbsp", section: "dairy" },
        { name: "Cucumber, grated", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Garlic, minced", quantity: 2, unit: "clove", section: "produce" },
        { name: "Tomato, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red onion, thinly sliced", quantity: 2, unit: "tbsp", section: "produce" },
        { name: "Dried oregano", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Lemon", quantity: 1, unit: "each", section: "produce" },
      ],
      instructions: [
        "Squeeze the grated cucumber dry in a towel before mixing it into the yogurt with garlic — wet cucumber makes watery tzatziki that runs straight out of the wrap.",
        "Marinate the chicken in lemon, oregano, and olive oil, then sear until well charred.",
        "Warm the pita so it folds without cracking.",
        "Build with tzatziki, chicken, tomato, and onion.",
      ],
      storageInstructions: "Tzatziki keeps 4 days and improves overnight.",
    },
    {
      name: "Veggie Hummus Wrap",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "wrap",
      calories: 432,
      proteinG: 16,
      carbsG: 56,
      fatG: 16,
      fiberG: 12,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["vegetarian", "vegan", "high-fiber"],
      allergens: ["wheat", "sesame"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Hummus", quantity: 0.4, unit: "cup", section: "pantry" },
        { name: "Carrot, shredded", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Cucumber, julienned", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Red bell pepper, julienned", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Baby spinach", quantity: 1.5, unit: "cup", section: "produce" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Lemon", quantity: 0.5, unit: "each", section: "produce" },
      ],
      instructions: [
        "Cut everything into matchsticks running the length of the wrap, not across it — long strips roll tightly and slice cleanly.",
        "Spread hummus edge to edge.",
        "Layer spinach first as a barrier, then the vegetables and avocado.",
        "Squeeze lemon over, season well with salt, and roll tightly.",
      ],
      storageInstructions: "Keeps half a day wrapped tightly.",
    },
    {
      name: "Turkey Ranch Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 490,
      proteinG: 40,
      carbsG: 42,
      fatG: 18,
      fiberG: 6,
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Roasted turkey breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Ranch dressing", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Tomato, diced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Red onion, thinly sliced", quantity: 1, unit: "tbsp", section: "produce" },
      ],
      instructions: [
        "Spread the ranch across the tortilla, keeping an inch clear at the top edge so it seals rather than squeezes out.",
        "Shingle the turkey rather than stacking it in one lump.",
        "Salt and drain the tomato first.",
        "Roll tightly, wrap in foil, and rest 5 minutes before cutting so it holds together.",
      ],
      storageInstructions: "Keeps a day refrigerated in foil.",
    },
    {
      name: "Steak and Cheese Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 560,
      proteinG: 42,
      carbsG: 44,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 15,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Beef sirloin, thinly sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Provolone cheese", quantity: 1, unit: "oz", section: "dairy" },
        { name: "Yellow onion, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Green bell pepper, sliced", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Cremini mushrooms, sliced", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Freeze the sirloin 20 minutes to slice it thinly.",
        "Cook the vegetables until browned and remove.",
        "Sear the beef fast over high heat, chopping it with the spatula edge, then return the vegetables and lay the provolone over to melt.",
        "Roll into a warmed tortilla and griddle the seam to seal.",
      ],
      storageInstructions: "Filling keeps 3 days; assemble fresh.",
    },
    {
      name: "Egg and Avocado Breakfast Wrap",
      mealType: "breakfast",
      cuisine: "american",
      dishType: "wrap",
      calories: 480,
      proteinG: 26,
      carbsG: 40,
      fatG: 24,
      fiberG: 9,
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["vegetarian", "high-protein", "high-fiber"],
      allergens: ["wheat", "eggs", "milk"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Eggs", quantity: 3, unit: "each", section: "protein" },
        { name: "Avocado", quantity: 0.5, unit: "each", section: "produce" },
        { name: "Shredded cheddar cheese", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Baby spinach", quantity: 1, unit: "cup", section: "produce" },
        { name: "Salsa", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Butter", quantity: 1, unit: "tsp", section: "dairy" },
      ],
      instructions: [
        "Wilt the spinach and drain it.",
        "Scramble the eggs low and slow, pulling them while still slightly wet — they keep cooking in the wrap.",
        "Warm the tortilla, add cheese first so it melts against the hot eggs.",
        "Add avocado and drained salsa, roll tightly, and griddle the seam.",
      ],
      storageInstructions: "Wrap in foil and refrigerate 2 days; reheat in a pan.",
    },
    {
      name: "Thai Peanut Chicken Wrap",
      mealType: "lunch",
      cuisine: "thai",
      dishType: "wrap",
      calories: 542,
      proteinG: 38,
      carbsG: 48,
      fatG: 22,
      fiberG: 8,
      prepMinutes: 15,
      cookMinutes: 12,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "peanuts", "soybeans"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken breast, sliced", quantity: 5, unit: "oz", section: "protein" },
        { name: "Peanut butter", quantity: 1.5, unit: "tbsp", section: "pantry" },
        { name: "Soy sauce", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Lime", quantity: 1, unit: "each", section: "produce" },
        { name: "Napa cabbage, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Carrot, shredded", quantity: 0.33, unit: "cup", section: "produce" },
        { name: "Fresh cilantro", quantity: 3, unit: "tbsp", section: "produce" },
        { name: "Sriracha", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Whisk peanut butter with lime juice and warm water first, then add soy and sriracha — adding salt before it's emulsified makes it seize.",
        "Cook and slice the chicken.",
        "Toss the cabbage and carrot with a little of the sauce so it clings.",
        "Build with a stripe of sauce, the slaw, chicken, and cilantro, then roll tightly.",
      ],
      storageInstructions: "Sauce keeps a week; assemble fresh.",
    },
    {
      name: "Tuna Nicoise Wrap",
      mealType: "lunch",
      cuisine: "mediterranean",
      dishType: "wrap",
      calories: 492,
      proteinG: 36,
      carbsG: 42,
      fatG: 20,
      fiberG: 7,
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["fish", "wheat", "eggs"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Canned tuna in olive oil, drained", quantity: 5, unit: "oz", section: "protein" },
        { name: "Hard-boiled egg, sliced", quantity: 1, unit: "each", section: "protein" },
        { name: "Green beans, blanched", quantity: 0.5, unit: "cup", section: "produce" },
        { name: "Nicoise olives, halved", quantity: 2, unit: "tbsp", section: "pantry" },
        { name: "Dijon mustard", quantity: 1, unit: "tsp", section: "pantry" },
        { name: "Red wine vinegar", quantity: 1, unit: "tbsp", section: "pantry" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Olive oil", quantity: 1, unit: "tsp", section: "pantry" },
      ],
      instructions: [
        "Use oil-packed tuna and drain it well; water-packed goes dry and stringy in a cold wrap.",
        "Whisk Dijon, vinegar, and olive oil and toss with the tuna and green beans.",
        "Layer lettuce first as a moisture barrier, then the dressed filling, egg, and olives.",
        "Roll tightly and let it rest 5 minutes before cutting.",
      ],
      storageInstructions: "Filling keeps 2 days; assemble at serving.",
    },
    {
      name: "Chicken Bacon Ranch Wrap",
      mealType: "lunch",
      cuisine: "american",
      dishType: "wrap",
      calories: 552,
      proteinG: 42,
      carbsG: 42,
      fatG: 24,
      fiberG: 5,
      prepMinutes: 10,
      cookMinutes: 15,
      servings: 1,
      dietaryTags: ["high-protein"],
      allergens: ["wheat", "milk", "eggs"],
      ingredients: [
        { name: "Large flour tortilla", quantity: 1, unit: "each", section: "bakery" },
        { name: "Chicken breast", quantity: 5, unit: "oz", section: "protein" },
        { name: "Bacon", quantity: 2, unit: "slice", section: "protein" },
        { name: "Ranch dressing", quantity: 1.5, unit: "tbsp", section: "dairy" },
        { name: "Shredded cheddar cheese", quantity: 0.5, unit: "oz", section: "dairy" },
        { name: "Romaine lettuce, shredded", quantity: 1, unit: "cup", section: "produce" },
        { name: "Tomato, diced", quantity: 0.33, unit: "cup", section: "produce" },
      ],
      instructions: [
        "Cook the bacon crisp and the chicken through, then let both cool to warm before assembling.",
        "Spread ranch across the tortilla, add cheese, then the warm chicken so the cheese just softens.",
        "Add bacon, lettuce, and drained tomato.",
        "Roll tight, then griddle seam-side down 2 minutes per side — a toasted wrap holds together far better in a lunchbox.",
      ],
      storageInstructions: "Keeps a day in foil; re-toast to serve.",
    },
  ],
};
