import { NextResponse, type NextRequest } from "next/server";
import { getServerEnv } from "@/platform/env.server";
import { createAdminClient } from "@/platform/supabase/admin";
import { sendOpsAlert } from "@/platform/alerts/notify";
import { ensureMealPlanWeeksAhead } from "@/domains/mealplan/approve-flow";

/**
 * Keeps a meal plan in front of everyone who wants one.
 *
 * RE-ENABLED 2026-09-19, having been disabled on 2026-08-16. The original
 * objection was real and specific: the cron filled days people had no
 * intention of cooking — weekends spent eating out — and there was no way
 * to delete a planned meal, so the only recourse was a grocery list that
 * did not match how they actually eat.
 *
 * Every part of that has since been answered. `plannedMealDays` is asked
 * during onboarding and editable in Settings, and the generator only
 * fills those days. `meal_planning_enabled` turns the whole thing off.
 * `shopping_horizon_weeks` decides how far ahead to build. And as of
 * today a single meal can be declined outright (`skipped_at`). The
 * behaviour people rejected cannot recur.
 *
 * What the absence cost, meanwhile: meals were only ever generated by
 * onboarding or by approving a weekly brief. When brief generation broke
 * on 2026-08-23 that chain broke with it, and the developer's own account
 * went 17 days with no meal plan at all — meal planning switched on, the
 * Today screen simply showing no food, and nothing anywhere saying why.
 * A promise this central should not rest on another feature working.
 *
 * Daily rather than weekly, and safe to run daily because
 * ensureMealPlanWeeksAhead skips any week that already has a plan. That
 * makes it self-healing: a gap closes the next morning instead of waiting
 * for Sunday. It also never overwrites a week in progress, so meals
 * someone already ticked are never destroyed.
 */
export async function GET(request: NextRequest) {
  const { CRON_SECRET } = getServerEnv();
  const authHeader = request.headers.get("authorization");
  if (!CRON_SECRET || authHeader !== `Bearer ${CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supabase = createAdminClient();

  const [{ data: profiles, error: profileError }, { data: assignmentRows, error: assignmentError }] =
    await Promise.all([
      supabase
        .from("profiles")
        .select("id, shopping_horizon_weeks")
        .not("onboarding_completed_at", "is", null)
        .neq("meal_planning_enabled", false),
      // Trainer-assigned clients are driven by their trainer's program,
      // never by the library generator. generateAndSaveMealPlan refuses
      // them anyway; excluding them here keeps them out of the failure
      // count rather than manufacturing one per run.
      supabase.from("trainer_meal_program_assignments").select("client_id").eq("status", "active"),
    ]);

  if (profileError || assignmentError) {
    const detail = profileError?.message ?? assignmentError?.message ?? "unknown error";
    await sendOpsAlert({ subject: "Meal plan regeneration could not run", detail });
    return NextResponse.json({ error: detail }, { status: 500 });
  }

  const trainerAssigned = new Set((assignmentRows ?? []).map((r) => r.client_id));
  const candidates = (profiles ?? []).filter((p) => !trainerAssigned.has(p.id));

  const results = await Promise.allSettled(
    candidates.map((p) => ensureMealPlanWeeksAhead(p.id, Math.max(1, p.shopping_horizon_weeks ?? 1), supabase))
  );

  const weeksGenerated = results.reduce(
    (sum, r) => sum + (r.status === "fulfilled" && r.value.ok ? r.value.data.generatedWeeks.length : 0),
    0
  );
  const failures = results.flatMap((r, i) =>
    r.status === "rejected"
      ? [{ userId: candidates[i].id, error: String(r.reason) }]
      : r.value.ok
        ? []
        : [{ userId: candidates[i].id, error: r.value.error }]
  );

  // Same posture as the weekly review cron: a run where nobody could be
  // served is a failure worth seeing, not a green 200 with the detail
  // buried in a body nobody reads.
  if (failures.length > 0) {
    await sendOpsAlert({
      subject: `Meal plan regeneration failed for ${failures.length} of ${candidates.length} user(s)`,
      detail: `Sample error: ${failures[0].error}`,
    });
  }

  return NextResponse.json(
    { checked: candidates.length, weeksGenerated, failures },
    { status: weeksGenerated === 0 && failures.length > 0 ? 500 : 200 }
  );
}
