/**
 * Turns a validated RecipeContentBatch into a real SQL migration file --
 * programmatically, from typed objects, never from hand-typed tuples.
 * Mirrors scripts/training-content/generate-migration.ts's own reasoning
 * (see that file's comment for the arity-mismatch bug class this avoids).
 *
 * Every recipe gets its own single-row INSERT with status forced to
 * 'active' -- this pipeline has no manual review gate (see
 * domains/recipes/content-spec.ts's comment), so a recipe that passes
 * validate-spec.ts is immediately eligible for real meal-plan generation.
 *
 * Writes a file for review + `supabase db push` (same as every other
 * migration in this repo) -- does NOT apply directly.
 *
 * Invoke standalone: pnpm dlx tsx scripts/recipe-content/generate-migration.ts --spec <path-to-batch-module> [--label <label>]
 */
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { recipeContentBatchSchema, type RecipeContentBatch, type NewRecipeSpec } from "@/domains/recipes/content-spec";

const MIGRATIONS_DIR = path.resolve(fileURLToPath(import.meta.url), "../../../supabase/migrations");

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  return value === null || value === undefined ? "null" : String(value);
}

function sqlStringArray(values: string[]): string {
  if (values.length === 0) return "array[]::text[]";
  return `array[${values.map((v) => sqlString(v)).join(", ")}]`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function nextMigrationNumber(): string {
  const files = fs.readdirSync(MIGRATIONS_DIR).filter((f) => /^\d{4}_/.test(f));
  const max = files.reduce((acc, f) => Math.max(acc, parseInt(f.slice(0, 4), 10)), 0);
  return String(max + 1).padStart(4, "0");
}

function batchLabel(batch: RecipeContentBatch, override?: string): string {
  if (override) return override;
  const cuisines = Array.from(new Set(batch.recipes.map((r) => r.cuisine))).sort();
  return cuisines.length === 1 ? cuisines[0] : cuisines.join("_");
}

function yearMonth(): string {
  const now = new Date();
  return `${now.getFullYear()}_${String(now.getMonth() + 1).padStart(2, "0")}`;
}

function emitRecipe(recipe: NewRecipeSpec): string {
  return (
    `(${sqlString(recipe.name)}, ${sqlString(recipe.mealType)}, ${sqlString(recipe.cuisine)}, ${sqlString(recipe.dishType)}, ${sqlStringArray(recipe.alsoSuitableFor ?? [])}, ` +
    `${sqlNumber(recipe.calories)}, ${sqlNumber(recipe.proteinG)}, ${sqlNumber(recipe.carbsG)}, ${sqlNumber(recipe.fatG)}, ${sqlNumber(recipe.fiberG ?? null)}, ` +
    `${sqlNumber(recipe.prepMinutes)}, ${sqlNumber(recipe.cookMinutes)}, ${sqlNumber(recipe.servings)}, ` +
    `${sqlStringArray(recipe.dietaryTags)}, ${sqlStringArray(recipe.allergens)}, ${sqlJsonb(recipe.ingredients)}, ${sqlStringArray(recipe.instructions)}, ` +
    `${sqlString(recipe.storageInstructions ?? null)}, ${sqlString(recipe.photoUrl ?? null)}, 'active')`
  );
}

/** Pure -- builds the full migration SQL text from a validated batch. */
export function buildMigrationSql(batch: RecipeContentBatch): string {
  const header =
    `-- Generated by scripts/recipe-content/generate-migration.ts from a\n` +
    `-- validated RecipeContentBatch (see docs/recipe-content-pipeline.md).\n` +
    `-- Purely additive: adds new recipes only, never modifies or\n` +
    `-- deactivates existing rows. Every row lands as status = 'active' --\n` +
    `-- this pipeline has no manual review gate; validate-spec.ts's\n` +
    `-- computed checks are the safety net.\n\n`;

  const rows = batch.recipes.map(emitRecipe).join(",\n");

  const insert =
    `insert into public.recipes\n` +
    `  (name, meal_type, cuisine, dish_type, also_suitable_for, calories, protein_g, carbs_g, fat_g, fiber_g, prep_minutes, cook_minutes, servings, dietary_tags, allergens, ingredients, instructions, storage_instructions, photo_url, status)\n` +
    `values\n` +
    rows +
    `;\n`;

  return header + insert;
}

export function generateMigrationFile(batch: RecipeContentBatch, label?: string): string {
  const number = nextMigrationNumber();
  const filename = `${number}_recipes_${batchLabel(batch, label)}_${yearMonth()}.sql`;
  const filePath = path.join(MIGRATIONS_DIR, filename);
  fs.writeFileSync(filePath, buildMigrationSql(batch));
  return filePath;
}

async function loadBatchModule(specPath: string): Promise<unknown> {
  const absolute = path.resolve(process.cwd(), specPath);
  const mod = (await import(pathToFileURL(absolute).href)) as { batch?: unknown };
  if (!mod.batch) {
    throw new Error(`${specPath} must have a named export \`batch\` (a RecipeContentBatch object).`);
  }
  return mod.batch;
}

async function main() {
  const specArgIndex = process.argv.indexOf("--spec");
  const specPath = specArgIndex !== -1 ? process.argv[specArgIndex + 1] : undefined;
  if (!specPath) {
    console.error("Usage: tsx scripts/recipe-content/generate-migration.ts --spec <path-to-batch-module> [--label <label>]");
    process.exit(1);
  }
  const labelArgIndex = process.argv.indexOf("--label");
  const label = labelArgIndex !== -1 ? process.argv[labelArgIndex + 1] : undefined;

  const rawBatch = await loadBatchModule(specPath);
  const batch = recipeContentBatchSchema.parse(rawBatch);
  const filePath = generateMigrationFile(batch, label);
  console.log(`Wrote ${filePath}`);
  console.log("Review it, then run: pnpm dlx supabase db push --linked");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
