-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: Full-Coverage Concurrent Training (hybrid-full-coverage-concurrent)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('hybrid_athlete', 'hybrid-full-coverage-concurrent', 'Full-Coverage Concurrent Training', 'Rotates heavy strength, light strength, and conditioning-priority days like the other hybrid_athlete programs, but gives every strength day full major-movement-pattern coverage (squat, hinge, horizontal push, horizontal or vertical pull, core) rather than one or two isolated lifts -- while keeping conditioning-priority and aerobic days single-modality so they don''t dilute the quality they''re meant to develop.',
     'Strength-day structure follows standard full-session movement-pattern coverage (as used in this app''s hypertrophy/powerlifter/general_fitness programs). Conditioning/aerobic days stay single-modality per Alex Viada''s guidance to consolidate stressors around the week''s priority driver rather than overload any one energy system on a given day.', 'intermediate', 5, 6,
     array['Barbell', 'Dumbbells', 'Full gym access'], 4)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Alex Viada / Complete Human Performance', 'Programming For The Obligate Hybrid Athlete (Combat Sports)', 'https://www.completehumanperformance.com/blog/programming-for-the-obligate-hybrid-athlete-combat-sports', '2026-08-04'),
    (v_program_id, 'NIH / NCBI', 'The Role of Intra-Session Exercise Sequence in the Interference Effect: A Systematic Review with Meta-Analysis', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5752732/', '2026-08-04');

  -- Phase 1: Foundation
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Foundation', 'Learn full-coverage strength days at moderate effort alongside dedicated conditioning and aerobic work.', 4, 'RPE 6-7', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Heavy Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 4, 4, 6, 'rpe', '7', 'Squat pattern -- heavy day of the rotation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell bench press'), 4, 4, 6, 'rpe', '7', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell row'), 3, 6, 8, 'rpe', '7', 'Horizontal pull pattern -- balances the pressing volume above.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, 'Core stability, 30-45 second holds.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Conditioning Priority', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Rowing intervals'), 6, 3, '6 x 3 min hard, 2 min easy', 'Conditioning-priority day -- kept single-modality so it isn''t diluted by unrelated strength work.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Light Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Goblet squat'), 3, 10, 12, 'rpe', '6', 'Squat pattern -- light day, higher reps, lower loads.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Dumbbell Romanian deadlift'), 3, 10, 12, 'rpe', '6', 'Hinge pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Push-up'), 3, 10, 15, 'rpe', '6', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Dumbbell row'), 3, 10, 12, 'rpe', '6', 'Horizontal pull pattern.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Easy Aerobic', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 30, 'conversational pace', 'True recovery day within the rotation -- kept single-modality on purpose.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Heavy Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell deadlift'), 3, 3, 5, 'rpe', '7', 'Hinge pattern -- second heavy day of the week.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Pull-up'), 3, 6, 8, 'rpe', '7', 'Vertical pull pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Dumbbell bench press'), 3, 8, 10, 'rpe', '7', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Hanging leg raise'), 3, 10, 12, 'rpe', '7', 'Core pattern.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 6, 'Conditioning Priority', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Kettlebell clean and press'), 4, 15, 15, 'rpe', '7', 'Second conditioning-priority day, full-body focus -- kept single-modality.', null)
  returning id into v_primary_id;


  -- Phase 2: Progression
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Progression', 'Heavier heavy days and harder conditioning days, same full-coverage strength structure.', 4, 'RPE 8', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Heavy Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 4, 3, 5, 'rpe', '8', 'Squat pattern -- heavier than the Foundation phase.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell bench press'), 4, 3, 5, 'rpe', '8', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell row'), 3, 5, 8, 'rpe', '8', 'Horizontal pull pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, 'Core stability, 45-60 second holds.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Conditioning Priority', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Rowing intervals'), 8, 3, '8 x 3 min hard, 2 min easy', 'Two more rounds than the Foundation phase -- kept single-modality.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Light Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Goblet squat'), 3, 8, 10, 'rpe', '7', 'Squat pattern -- slightly heavier than the Foundation phase.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Dumbbell Romanian deadlift'), 3, 8, 10, 'rpe', '7', 'Hinge pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Push-up'), 3, 12, 15, 'rpe', '7', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Dumbbell row'), 3, 8, 10, 'rpe', '7', 'Horizontal pull pattern.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Easy Aerobic', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 35, 'conversational pace', 'Kept easy even as other days intensify -- single-modality on purpose.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Heavy Strength', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell deadlift'), 3, 2, 4, 'rpe', '8', 'Hinge pattern -- heavier than the Foundation phase.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Pull-up'), 3, 5, 7, 'rpe', '8', 'Vertical pull pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Dumbbell bench press'), 3, 6, 8, 'rpe', '8', 'Horizontal push pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Hanging leg raise'), 3, 12, 15, 'rpe', '8', 'Core pattern.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 6, 'Conditioning Priority', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Kettlebell clean and press'), 5, 8, 10, 'rpe', '8', 'Harder full-body conditioning than the Foundation phase -- kept single-modality.', null)
  returning id into v_primary_id;


end $$;
