-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: Conjugate Method: Full Coverage (powerlifter-conjugate-full-coverage)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('powerlifter', 'powerlifter-conjugate-full-coverage', 'Conjugate Method: Full Coverage', 'Westside Barbell''s Conjugate Method: Max Effort days build near-max strength on a rotating main lift, Dynamic Effort days build speed-strength with submaximal, explosive reps -- both paired with real repeated-effort accessory volume (not just the one main lift), per Westside''s own emphasis that accessories, not the main lift, drive most of a lifter''s progress.',
     'Westside Barbell / Louie Simmons'' Conjugate Method: Max Effort (near-maximal loads) and Dynamic Effort (submaximal loads at maximal speed) days, each built around one primary lift plus repeated-effort accessory work -- the source states main lifts are roughly 20% of total training volume, with repeated-effort accessories comprising the remaining 80%, which is why every session here includes real accessory coverage rather than just the main lift.', 'intermediate', 4, 4,
     array['Barbell', 'Dumbbells', 'Full gym access'], 1)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Louie Simmons / Westside Barbell', 'The Conjugate Method: Westside Barbell Conjugate Training', 'https://www.westside-barbell.com/pages/conjugate-method', '2026-08-05');

  -- Phase 1: Foundation
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Foundation', 'Learn the Max Effort / Dynamic Effort rhythm and build accessory work capacity at moderate intensity.', 4, 'RPE 6-8', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Max Effort Lower', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 1, 1, 3, 'rpe', '8', 'Work up to a heavy but clean triple for the week -- this is the Max Effort lift.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Front squat'), 3, 6, 8, 'rpe', '7', 'Quad-biased repeated-effort accessory -- upright torso position also carries over to the ME lift.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Good morning'), 3, 8, 10, 'rpe', '6', 'Posterior-chain repeated-effort work -- keep the back flat, hinge from the hips.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Reverse hyper'), 3, 10, 12, 'rpe', '6', 'Low back / glute recovery work Westside uses heavily between max-effort sessions.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '30-45 second holds -- core bracing carries directly into squat/deadlift stability.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Max Effort Upper', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell bench press'), 1, 1, 3, 'rpe', '8', 'Work up to a heavy but clean triple -- the Max Effort lift for upper body.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Close-grip bench press'), 3, 6, 8, 'rpe', '7', 'Triceps/lockout-biased repeated-effort accessory.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell row'), 4, 8, 10, 'rpe', '7', 'Back volume to balance pressing -- Westside trains pulling at least as hard as pressing.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Dumbbell lateral raise'), 3, 12, 15, 'rpe', '6', 'Shoulder health/accessory volume.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Triceps pushdown'), 3, 10, 12, 'rpe', '6-7', 'Extra triceps volume for lockout strength.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Dynamic Effort Lower', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 8, 2, 2, 'percent_1rm', '50-60', 'Speed work -- move the bar as explosively as possible, rest ~60s between sets.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell deadlift'), 6, 1, 1, 'percent_1rm', '60', 'Speed pulls off the floor -- Dynamic Effort for the hinge pattern.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Bulgarian split squat'), 3, 8, 10, 'rpe', '7', 'Per leg -- unilateral repeated-effort accessory.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Back extension'), 3, 10, 12, 'rpe', '6', 'Posterior-chain accessory volume.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Hanging leg raise'), 3, 10, 12, 'rpe', '7', 'Core work to close the session.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Dynamic Effort Upper', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell bench press'), 9, 3, 3, 'percent_1rm', '50-60', 'Speed bench -- explosive reps off the chest, rest ~45-60s between sets.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell overhead press'), 3, 6, 8, 'rpe', '7', 'Secondary press accessory.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Pull-up'), 4, 6, 10, 'rpe', '7', 'Back/grip volume -- use an assisted variation if a clean set of 6 isn''t there yet.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Face pull'), 3, 12, 15, 'rpe', '6', 'Rear delt/shoulder health -- Westside''s accessory work leans heavily on shoulder health for pressing longevity.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Dumbbell curl'), 3, 10, 12, 'rpe', '6', 'Arm accessory volume.', null)
  returning id into v_primary_id;


  -- Phase 2: Intensification
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Intensification', 'Rotate the Max Effort lifts, push Dynamic Effort loading percentages up, and raise accessory intensity.', 5, 'RPE 7-9', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Max Effort Lower', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell deadlift'), 1, 1, 2, 'rpe', '9', 'Rotated ME lift from the Foundation phase''s squat -- Westside rotates the ME movement roughly every 1-3 weeks; simplified here to a phase-level rotation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Front squat'), 3, 5, 6, 'rpe', '8', 'Heavier than the Foundation phase.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Good morning'), 3, 6, 8, 'rpe', '7', 'Heavier posterior-chain loading than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Reverse hyper'), 3, 10, 12, 'rpe', '7', 'Kept in the same rep range -- this is recovery/health work, not a max-effort movement.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '45-60 second holds.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Max Effort Upper', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell bench press'), 1, 1, 2, 'rpe', '9', 'Heavier top double than the Foundation phase''s triple.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Close-grip bench press'), 3, 5, 6, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell row'), 4, 6, 8, 'rpe', '8', 'Heavier pulling volume than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Dumbbell lateral raise'), 3, 10, 12, 'rpe', '7', 'Slightly heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Triceps pushdown'), 3, 8, 10, 'rpe', '7-8', 'Heavier lockout accessory work.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Dynamic Effort Lower', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 10, 2, 2, 'percent_1rm', '60-70', 'Higher percentage and two more sets than Foundation -- the DE wave rolls upward.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell deadlift'), 8, 1, 1, 'percent_1rm', '70', 'Heavier speed pulls than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Bulgarian split squat'), 3, 6, 8, 'rpe', '8', 'Heavier per-leg loading than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Back extension'), 3, 8, 10, 'rpe', '7', 'Slightly heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Hanging leg raise'), 4, 10, 12, 'rpe', '7-8', 'Added a set from Foundation.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Dynamic Effort Upper', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell bench press'), 9, 3, 3, 'percent_1rm', '60-70', 'Higher percentage than Foundation -- same wave logic as the lower-body DE day.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell overhead press'), 3, 5, 6, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Pull-up'), 4, 5, 8, 'rpe', '8', 'Add weight if bodyweight reps are no longer challenging in this range.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Face pull'), 3, 12, 15, 'rpe', '7', 'Kept high-rep even as other lifts intensify -- shoulder health work stays submaximal by design.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Dumbbell curl'), 3, 8, 10, 'rpe', '7', 'Heavier than Foundation.', null)
  returning id into v_primary_id;


end $$;
