-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

-- New exercises this batch's programs need, seeded before the
-- programs that reference them so the exercise_id subqueries below
-- resolve within the same migration.
insert into public.exercises
  (name, movement_pattern, equipment_required, archetype_tags, difficulty, primary_muscle_groups, instructions, canonical_name, movement_patterns)
select name, movement_pattern, equipment_required, archetype_tags, difficulty, primary_muscle_groups, instructions, name, array[movement_pattern]
from (values
  ('Track interval repeats', 'aerobic / conditioning', array['Bodyweight only'], array['long_distance_runner'], 'intermediate', array['legs', 'cardio'], 'Hard, sustained repeats at interval pace (roughly 97-100% VO2max, 3-5 minutes each) with an easy jog recovery between reps -- stresses aerobic power without excessive lactate buildup.'),
  ('Track speed repetitions', 'anaerobic / speed', array['Bodyweight only'], array['long_distance_runner'], 'intermediate', array['legs', 'cardio'], 'Short, fast repeats at repetition pace with long recoveries between reps, so each one feels controlled rather than exhausting -- builds running economy and speed without accumulating fatigue.')
) as t(name, movement_pattern, equipment_required, archetype_tags, difficulty, primary_muscle_groups, instructions);

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: Daniels' Five-Pace Formula: Full Coverage (runner-daniels-five-pace-full-coverage)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('long_distance_runner', 'runner-daniels-five-pace-full-coverage', 'Daniels'' Five-Pace Formula: Full Coverage', 'Jack Daniels'' (Daniels'' Running Formula, VDOT) five-training-pace framework -- Easy, Threshold, Interval, and Repetition runs across the week, each mapped to a specific physiological target -- paired with a real multi-exercise strength support day instead of just 1-2 accessory lifts.',
     'Jack Daniels'' VDOT system prescribes training paces by physiological target: Easy (59-74% VO2max) builds aerobic base; Threshold (83-88% VO2max, sustained 5-15 minute efforts) improves lactate clearance; Interval (97-100% VO2max, 3-5 minute efforts) maximizes aerobic power; Repetition pace (short, fast, long recoveries) builds speed and running economy without accumulating fatigue. The strength support day is not part of Daniels'' own published system -- built separately per this app''s own >=4-exercise-per-strength-session standard, using running-relevant injury-prevention and hip/hamstring/core work.', 'intermediate', 5, 5,
     array['Barbell', 'Dumbbells', 'Full gym access', 'Bodyweight only'], 1)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Dr. Jack Daniels / V.O2', 'V.O2 Running Calculator -- Jack Daniels'' Five Training Paces', 'https://vdoto2.com/calculator', '2026-08-05');

  -- Phase 1: Base Building
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Base Building', 'Build aerobic base with easy mileage, introduce threshold and interval work, and support the added volume with real strength work.', 4, 'Easy effort throughout except threshold/interval days', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Easy Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 30, 'conversational, easy effort (59-74% VO2max) -- builds the aerobic base everything else depends on.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Long Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 60, 'conversational, easy effort -- the week''s longest continuous run.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Threshold Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Tempo run'), 3, 10, '3 x 10 min at threshold pace (83-88% VO2max), 2 min easy jog recovery.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Interval Day', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Track interval repeats'), 5, 4, '5 x 4 min at interval pace (97-100% VO2max), 3 min easy jog recovery.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Strength Support', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Single-leg Romanian deadlift'), 3, 8, 10, 'rpe', '6', 'Per leg -- balance and hamstring resilience for the added mileage.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Nordic curl'), 3, 6, 8, 'rpe', '6', 'Eccentric hamstring strength -- well-supported injury-prevention work for runners.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell hip thrust'), 3, 10, 12, 'rpe', '6', 'Glute strength to support hip drive.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '30-45 second holds -- core stability for running posture.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Standing calf raise'), 3, 12, 15, 'rpe', '6', 'Calf/Achilles resilience for the mileage load.', null)
  returning id into v_primary_id;


  -- Phase 2: Quality Development
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Quality Development', 'Extend the long run, add threshold volume, and shift interval work to repetition-pace speed as the program peaks.', 5, 'Easy effort throughout except threshold/repetition days', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Easy Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 35, 'conversational, easy effort -- kept easy even as other days intensify.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Long Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Easy-pace run'), null, 75, 'conversational, easy effort -- the longest run of the program.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Threshold Run', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Tempo run'), 4, 8, '4 x 8 min at threshold pace, 90 sec easy jog recovery -- more total threshold volume than Base Building.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Repetition Day', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Track speed repetitions'), 8, 2, '8 x 2 min at repetition pace with full recovery jogs between reps -- speed/economy work as the program peaks.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Strength Support', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Single-leg Romanian deadlift'), 3, 6, 8, 'rpe', '7', 'Heavier than Base Building.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Nordic curl'), 3, 8, 10, 'rpe', '7', 'Added reps from Base Building.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell hip thrust'), 3, 8, 10, 'rpe', '7', 'Heavier than Base Building.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '45-60 second holds.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Standing calf raise'), 3, 15, 20, 'rpe', '7', 'Heavier than Base Building.', null)
  returning id into v_primary_id;


end $$;
