-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: Coggan Power Zones: Full Coverage (cyclist-coggan-power-zones-full-coverage)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('cyclist', 'cyclist-coggan-power-zones-full-coverage', 'Coggan Power Zones: Full Coverage', 'Andrew Coggan''s 7-zone power-based training system (as % of FTP) -- Endurance, Tempo, Threshold, and VO2max/hill-repeat rides across the week -- paired with a real multi-exercise strength support day for pedaling asymmetry, core, and posterior-chain resilience instead of just 1-2 accessory lifts.',
     'Andrew Coggan''s power training zones (documented by Hunter Allen, his co-author on Training and Racing with a Power Meter) define seven zones as % of FTP: Endurance (56-75%) for long steady rides, Tempo (76-90%) for moderate sustained efforts, Threshold (91-105%, intervals at least 10 minutes long) for lactate-threshold work, and VO2max (106-120%, ~3-8 minute efforts) for aerobic power -- directly mapped here onto this app''s existing cycling-specific cardio exercises. The strength support day is not part of Coggan''s own system -- built separately per this app''s own >=4-exercise-per-strength-session standard, using bike-relevant unilateral, core, and posterior-chain work.', 'intermediate', 5, 5,
     array['Cardio machine', 'Full gym access', 'Dumbbells', 'Bodyweight only'], 1)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Hunter Allen (co-author with Andrew Coggan, Training and Racing with a Power Meter)', 'Power Training Zones 101', 'https://www.hunterallenpowerblog.com/2015/05/power-training-zones-101.html', '2026-08-05');

  -- Phase 1: Base Building
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Base Building', 'Build aerobic endurance, introduce tempo and threshold work, and support the added volume with real strength work.', 4, 'Zone 2 effort throughout except tempo/threshold days', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Endurance Ride', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Long endurance ride'), null, 90, 'Zone 2 Endurance (56-75% FTP), conversational effort -- the week''s aerobic foundation.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Tempo Ride', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Stationary bike steady-state'), null, 60, 'Zone 3 Tempo (76-90% FTP), sustained moderate effort.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Threshold Intervals', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Cycling threshold intervals'), 3, 12, 'Zone 4 Threshold (91-105% FTP), 3 x 12 min, 5 min easy spin recovery -- per Coggan''s guidance that threshold intervals need at least 10 minutes to trigger adaptation.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'VO2max Hill Repeats', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Cycling hill repeats'), 5, 4, 'Zone 5 VO2max (106-120% FTP), 5 x 4 min climbing effort, full recovery spin down between reps.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Strength Support', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Bulgarian split squat'), 3, 8, 10, 'rpe', '6', 'Per leg -- addresses side-to-side power imbalances pedaling alone doesn''t correct.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Single-leg Romanian deadlift'), 3, 8, 10, 'rpe', '6', 'Per leg -- posterior-chain and hip stability.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '30-45 second holds -- core endurance for maintaining an aero position.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Side plank'), 3, 1, 1, 'none', null, '20-30 second holds per side -- lateral hip stability, addresses hip drop on the bike.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Standing calf raise'), 3, 15, 20, 'rpe', '6', 'Lower-leg endurance work.', null)
  returning id into v_primary_id;


  -- Phase 2: Build
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Build', 'More threshold and VO2max volume, plus anaerobic sprint work, alongside heavier strength support.', 5, 'Zone 2 effort throughout except tempo/threshold/VO2max days', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Endurance Ride', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Long endurance ride'), null, 120, 'Zone 2 Endurance -- longer than Base Building.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Tempo Ride', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Stationary bike steady-state'), null, 75, 'Zone 3 Tempo -- longer than Base Building.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Threshold Intervals', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Cycling threshold intervals'), 4, 12, 'Zone 4 Threshold, 4 x 12 min, 5 min easy spin recovery -- one more interval than Base Building.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Sprint & VO2max', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, duration_minutes, cardio_intensity, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Standing bike sprints'), 6, 1, 'Zone 6-7 Anaerobic/Neuromuscular, 6 x ~30 sec all-out standing sprints, full recovery between -- added on top of the VO2max work as the program peaks.', null, null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 5, 'Strength Support', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Bulgarian split squat'), 3, 6, 8, 'rpe', '7', 'Heavier than Base Building.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Single-leg Romanian deadlift'), 3, 6, 8, 'rpe', '7', 'Heavier than Base Building.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '45-60 second holds.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Side plank'), 3, 1, 1, 'none', null, '30-45 second holds per side.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Standing calf raise'), 4, 15, 20, 'rpe', '7', 'Added a set from Base Building.', null)
  returning id into v_primary_id;


end $$;
