-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: Catalyst Athletics Classic Lifts: Full Coverage (oly-catalyst-full-coverage)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('olympic_weightlifter', 'oly-catalyst-full-coverage', 'Catalyst Athletics Classic Lifts: Full Coverage', 'A 4-day Olympic weightlifting split (Snatch, Clean & Jerk, Squat/Strength, Pulling & Technique) -- each day pairs the classic lift or its technique variations with real pulling, squatting, and accessory strength work, not the lift in isolation.',
     'Greg Everett / Catalyst Athletics'' publicly documented programming structure: 3-5 sessions per week organized around the classic lifts (snatch, clean & jerk), with dedicated squat/pulling strength work and -- per his own guidance that programs vary in whether they include ''accessory work (e.g. back and ab work and similar)'' -- this program deliberately includes it throughout, rather than leaving each session as a single lift.', 'intermediate', 4, 4,
     array['Barbell', 'Full gym access'], 1)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Greg Everett / Catalyst Athletics', 'Guide to Catalyst Athletics Training Program Selection', 'https://www.catalystathletics.com/article/2252/Guide-to-Training-Program-Selection/', '2026-08-05');

  -- Phase 1: Technique & Strength Foundation
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Technique & Strength Foundation', 'Build technical consistency in the classic lifts alongside real pulling, squatting, and accessory strength.', 4, 'RPE 6-7 / 70-75% for classic lifts', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Snatch Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Snatch'), 5, 2, 2, 'percent_1rm', '70-75', 'Technical work at a manageable percentage -- the day''s classic lift.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Snatch pull'), 4, 3, 3, 'rpe', '7', 'Pulling strength support for the snatch.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Snatch balance'), 4, 2, 2, 'rpe', '7', 'Speed-under-the-bar drill to sharpen the receiving position.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Overhead squat'), 3, 3, 3, 'rpe', '7', 'Overhead stability the snatch receiving position demands.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Front squat'), 3, 3, 3, 'rpe', '7', 'General squat strength underpins both competition lifts.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Clean & Jerk Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Clean and jerk'), 5, 2, 2, 'percent_1rm', '70-75', 'Technical work at a manageable percentage -- the day''s classic lift.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Clean pull'), 4, 3, 3, 'rpe', '7', 'Pulling strength support for the clean.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Push press'), 4, 3, 3, 'rpe', '7', 'Overhead pressing strength the jerk relies on.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Front squat'), 4, 3, 3, 'rpe', '7', 'Front-rack strength for the clean''s receiving position.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Squat & Strength Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 5, 3, 3, 'rpe', '7', 'General squat strength -- underpins both classic lifts.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Good morning'), 3, 8, 8, 'rpe', '6', 'Posterior-chain accessory work.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell overhead press'), 3, 5, 5, 'rpe', '7', 'Overhead pressing strength accessory.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Barbell row'), 3, 8, 8, 'rpe', '6-7', 'Upper-back/pulling accessory volume.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '30-45 second holds -- core bracing carries into both lifts.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Pulling & Technique Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Hang clean'), 4, 2, 2, 'rpe', '7', 'Technique variation, starting from the hang.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Hang snatch'), 4, 2, 2, 'rpe', '7', 'Technique variation, starting from the hang.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Clean pull'), 3, 3, 3, 'rpe', '7', 'Additional pulling strength volume.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Snatch pull'), 3, 3, 3, 'rpe', '7', 'Additional pulling strength volume.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Barbell row'), 3, 8, 8, 'rpe', '6', 'General back/grip work between speed sets.', null)
  returning id into v_primary_id;


  -- Phase 2: Intensification & Peaking
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Intensification & Peaking', 'Heavier classic-lift percentages and squat/pulling loads as the cycle peaks.', 5, 'RPE 8-9 / 80-85% for classic lifts', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Snatch Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Snatch'), 5, 1, 2, 'percent_1rm', '80-85', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Snatch pull'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Snatch balance'), 3, 2, 2, 'rpe', '8', 'Kept sharp, not necessarily heavier -- this is a speed/position drill.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Overhead squat'), 3, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Front squat'), 3, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Clean & Jerk Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Clean and jerk'), 5, 1, 2, 'percent_1rm', '80-85', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Clean pull'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Push press'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Front squat'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Squat & Strength Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 5, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Good morning'), 3, 6, 6, 'rpe', '7', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell overhead press'), 3, 4, 4, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Barbell row'), 3, 6, 6, 'rpe', '7-8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '45-60 second holds.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Pulling & Technique Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Hang clean'), 4, 1, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Hang snatch'), 4, 1, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Clean pull'), 3, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Snatch pull'), 3, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Barbell row'), 3, 6, 6, 'rpe', '7', 'Heavier than Foundation.', null)
  returning id into v_primary_id;


end $$;
