-- Generated by scripts/training-content/generate-migration.ts from a
-- validated ContentBatch (see docs/training-content-pipeline.md).
-- Purely additive: adds new programs/exercises and their source
-- citations, never modifies or deactivates existing rows.

do $$
declare
  v_program_id uuid;
  v_phase_id uuid;
  v_session_id uuid;
  v_primary_id uuid;
begin

  -- Program 1: CompTrain Strength/Skills/Conditioning: Full Coverage (functional-fitness-comptrain-full-coverage)
  insert into training_programs
    (archetype, slug, name, description, methodology_note, experience_level,
     sessions_per_week_min, sessions_per_week_max, equipment_required, display_order)
  values
    ('functional_fitness', 'functional-fitness-comptrain-full-coverage', 'CompTrain Strength/Skills/Conditioning: Full Coverage', 'A 4-day functional fitness split -- Strength, Gymnastics Skills, Olympic Lifting, and a genuine multi-movement Conditioning chipper -- each strength-type day with real supporting exercises instead of just 1-2 movements, and Conditioning built as an actual chipper (5 movements) instead of a single exercise.',
     'Ben Bergeron / CompTrain -- coach of 6 CrossFit Games/World Champions -- programs by combining strength, conditioning, and mobility into one unified system (per comptrain.com) rather than training any one in isolation. Applied here as 3 distinct strength-type days (barbell strength, gymnastics skill work, Olympic lifting) each with real supporting exercises, plus a Conditioning day built as an actual multi-movement chipper -- the format that actually defines competitive functional fitness -- rather than a single exercise standing in for the whole session.', 'intermediate', 4, 4,
     array['Barbell', 'Dumbbells', 'Kettlebells', 'Pull-up bar', 'Full gym access'], 4)
  returning id into v_program_id;

  insert into program_sources (program_id, organization, title, url, retrieved_at) values
    (v_program_id, 'Ben Bergeron / CompTrain', 'CompTrain -- Become Formidable', 'https://www.comptrain.com/', '2026-08-05');

  -- Phase 1: Foundation
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 1, 'Foundation', 'Build strength, gymnastics skill capacity, and Olympic lift technique, and introduce real multi-movement conditioning.', 4, 'RPE 6-7', false)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Strength Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 4, 5, 5, 'rpe', '7', 'Main lower-body strength work for the week.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell deadlift'), 3, 5, 5, 'rpe', '7', 'Posterior-chain strength.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell bench press'), 4, 6, 6, 'rpe', '7', 'Main upper-body pressing work.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Barbell overhead press'), 3, 6, 6, 'rpe', '7', 'Overhead pressing strength, supports jerks and handstand work.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '30-45 second holds -- core bracing for all the barbell work above.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Gymnastics Skill Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Pull-up'), 4, 6, 8, 'rpe', '7', 'Strict pulling strength -- the foundation for kipping/butterfly work later.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Handstand push-up'), 4, 5, 8, 'rpe', '7', 'Scale to a box or pike variation if strict reps aren''t there yet.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Toes-to-bar'), 4, 8, 10, 'rpe', '7', 'Core/grip gymnastics skill work.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Muscle-up'), 3, 3, 5, 'rpe', '7', 'Scale to banded or jumping muscle-ups if unbroken reps aren''t there yet.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Rope climb'), 3, 2, 3, 'rpe', '7', 'Grip/pulling conditioning to close the session.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Olympic Lift Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Power clean'), 5, 3, 3, 'rpe', '7', 'Main Olympic-lift work for the week.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Push press'), 4, 3, 3, 'rpe', '7', 'Overhead strength/speed, supports the jerk.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Front squat'), 3, 5, 5, 'rpe', '7', 'Front-rack strength for the clean''s receiving position.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Power snatch'), 4, 3, 3, 'rpe', '7', 'Second classic lift of the day.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Box jump'), 3, 5, 5, 'rpe', '7', 'Lower-body power work to close the session.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Conditioning', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Wall ball shot'), 1, 50, 50, 'rpe', '9', 'For time chipper: 50 wall ball shots, 40 kettlebell swings, 30 box jumps, 20 devil press, 10 burpees -- pace to finish strong, not just survive the first movement.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Kettlebell swing'), 1, 40, 40, 'rpe', '9', 'Second movement of the chipper -- see wall ball shot for the full workout.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Box jump'), 1, 30, 30, 'rpe', '9', 'Third movement of the chipper.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Devil press'), 1, 20, 20, 'rpe', '9', 'Fourth movement of the chipper -- the grinder.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Burpee'), 1, 10, 10, 'rpe', '9', 'Final movement of the chipper -- empty the tank.', null)
  returning id into v_primary_id;


  -- Phase 2: Peak
  insert into training_program_phases (program_id, phase_order, name, focus, length_weeks, intensity_style, is_final)
  values (v_program_id, 2, 'Peak', 'Heavier strength and Olympic lift loading, harder gymnastics volume, and a longer conditioning chipper.', 5, 'RPE 8-9', true)
  returning id into v_phase_id;

  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 1, 'Strength Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Barbell back squat'), 4, 4, 4, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Barbell deadlift'), 3, 4, 4, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Barbell bench press'), 4, 5, 5, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Barbell overhead press'), 3, 5, 5, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Plank'), 3, 1, 1, 'none', null, '45-60 second holds.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 2, 'Gymnastics Skill Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Pull-up'), 4, 8, 10, 'rpe', '8', 'Add weight if bodyweight reps are no longer challenging in this range.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Handstand push-up'), 4, 8, 10, 'rpe', '8', 'More reps than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Toes-to-bar'), 4, 10, 12, 'rpe', '8', 'More reps than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Muscle-up'), 4, 4, 6, 'rpe', '8', 'Added a set from Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Rope climb'), 4, 2, 3, 'rpe', '8', 'Added a set from Foundation.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 3, 'Olympic Lift Day', 'strength') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Power clean'), 5, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Push press'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Front squat'), 3, 4, 4, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Power snatch'), 4, 2, 2, 'rpe', '8', 'Heavier than Foundation.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Box jump'), 4, 5, 5, 'rpe', '8', 'Added a set from Foundation.', null)
  returning id into v_primary_id;


  insert into program_sessions (phase_id, session_index, name, session_type) values (v_phase_id, 4, 'Conditioning', 'conditioning') returning id into v_session_id;
  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 1, (select id from exercises where name = 'Wall ball shot'), 1, 60, 60, 'rpe', '9', 'Longer for-time chipper than Foundation: 60 wall ball shots, 50 kettlebell swings, 40 box jumps, 30 devil press, 20 burpees.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 2, (select id from exercises where name = 'Kettlebell swing'), 1, 50, 50, 'rpe', '9', 'Second movement of the chipper -- see wall ball shot for the full workout.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 3, (select id from exercises where name = 'Box jump'), 1, 40, 40, 'rpe', '9', 'Third movement of the chipper.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 4, (select id from exercises where name = 'Devil press'), 1, 30, 30, 'rpe', '9', 'Fourth movement of the chipper -- the grinder.', null)
  returning id into v_primary_id;

  insert into program_session_exercises (session_id, exercise_order, exercise_id, sets, reps_min, reps_max, intensity_type, intensity_value, coaching_notes, primary_exercise_id) values
    (v_session_id, 5, (select id from exercises where name = 'Burpee'), 1, 20, 20, 'rpe', '9', 'Final movement of the chipper -- empty the tank.', null)
  returning id into v_primary_id;


end $$;
