-- Recipe dish_type: the "what form is it" browse axis (soup / salad /
-- sandwich / burger ...), independent of `cuisine`. Added because cuisine
-- alone can't answer the question people actually ask when deciding what
-- to eat -- they want a soup, not necessarily a Thai one. See
-- RECIPE_DISH_TYPES in domains/recipes/schema.ts for the vocabulary and
-- the "exactly one, dominant form wins" rule.
--
-- Three steps, in order, so the column can end up NOT NULL without a
-- window where existing rows violate it:
--   1. add nullable + CHECK constraint
--   2. backfill all 270 existing recipes from an explicit name->type map
--   3. set NOT NULL
--
-- The backfill is an explicit per-recipe VALUES list rather than keyword
-- rules on the name. Keyword rules looked tempting but misfile exactly
-- the dishes that matter: "Chicken Tortilla Soup" is a soup not a wrap,
-- "Taco Salad" is a salad not a taco, "Shrimp Scampi with Zucchini
-- Noodles" is pasta not noodles. A literal list is longer but every call
-- is visible in review, which is the point of a migration.

alter table public.recipes
  add column dish_type text;

alter table public.recipes
  add constraint recipes_dish_type_check check (dish_type in (
    'soup','stew','chili','curry',
    'salad',
    'sandwich','burger','wrap','burrito','tacos','pizza',
    'pasta','noodles','rice','bowl',
    'stir_fry','grilled','bbq','casserole','seafood',
    'eggs','pancakes','oatmeal','toast',
    'baked','smoothie','dip','snack_bite'
  ));

update public.recipes as r
set dish_type = m.dish_type
from (values
  ('Baked Eggs in Tomato Sauce (Uova in Purgatorio)', 'eggs'),
  ('Besan Chilla (Chickpea Flour Pancake)', 'pancakes'),
  ('Black Bean Breakfast Tostadas', 'tacos'),
  ('Blueberry Protein Pancakes', 'pancakes'),
  ('Breakfast Chilaquiles Verdes', 'eggs'),
  ('Caprese Egg Scramble', 'eggs'),
  ('Chia Berry Coconut Bowl', 'bowl'),
  ('Chinese Five-Spice Turkey Sausage and Rice Bowl', 'rice'),
  ('Chorizo and Egg Breakfast Tacos', 'tacos'),
  ('Coconut Chia Pudding with Thai Basil', 'bowl'),
  ('Congee with Chicken', 'oatmeal'),
  ('Congee with Scallion and Egg', 'oatmeal'),
  ('Cottage Cheese Toast', 'toast'),
  ('Egg Drop Miso Soup', 'soup'),
  ('Egg Fried Rice Breakfast Bowl', 'rice'),
  ('Espresso Protein Overnight Oats', 'oatmeal'),
  ('Fig and Ricotta Toast', 'toast'),
  ('Frittata with Spinach and Parmesan', 'eggs'),
  ('Furikake Rice Bowl with Egg', 'rice'),
  ('Greek Yogurt Parfait', 'bowl'),
  ('Greek Yogurt with Honey and Walnuts', 'bowl'),
  ('Huevos Rancheros', 'eggs'),
  ('Japanese Breakfast Set with Grilled Mackerel', 'grilled'),
  ('Masala Chai Overnight Oats', 'oatmeal'),
  ('Masala Omelette', 'eggs'),
  ('Matcha Overnight Oats', 'oatmeal'),
  ('Mediterranean Breakfast Bowl with Hummus and Egg', 'bowl'),
  ('Mediterranean Veggie Omelette', 'eggs'),
  ('Mexican Chocolate Protein Oats', 'oatmeal'),
  ('Mexican Chorizo Breakfast Bowl', 'bowl'),
  ('Migas with Peppers and Onion', 'eggs'),
  ('Miso Soup with Tofu', 'soup'),
  ('Moong Dal Chilla with Vegetables', 'pancakes'),
  ('Natto Rice Bowl', 'rice'),
  ('Olive Oil Granola with Yogurt', 'bowl'),
  ('Overnight Oats with Peanut Butter', 'oatmeal'),
  ('Paneer Paratha', 'pancakes'),
  ('Peanut Butter Banana Overnight Oats', 'oatmeal'),
  ('Poha (Flattened Rice) with Peanuts', 'rice'),
  ('Prosciutto & Melon Breakfast Plate', 'snack_bite'),
  ('Protein Smoothie', 'smoothie'),
  ('Refried Bean and Cheese Breakfast Quesadilla', 'burrito'),
  ('Ricotta & Berry Toast', 'toast'),
  ('Salmon Onigiri', 'rice'),
  ('Scallion Pancakes with Soy Dipping Sauce', 'pancakes'),
  ('Shakshuka', 'eggs'),
  ('Shrimp and Egg Fried Rice Thai-Style', 'rice'),
  ('Soy Milk and Red Bean Breakfast Bowl', 'bowl'),
  ('Spanakopita Egg Muffins', 'eggs'),
  ('Steamed Egg with Shrimp', 'eggs'),
  ('Sticky Rice with Mango', 'rice'),
  ('Tamagoyaki with Rice', 'eggs'),
  ('Thai Basil Chicken and Egg Breakfast Bowl', 'bowl'),
  ('Thai Iced Tea Overnight Oats', 'oatmeal'),
  ('Thai Omelette (Kai Jeow) with Rice', 'eggs'),
  ('Thai Peanut Rice Bowl with Egg', 'rice'),
  ('Thai Rice Porridge with Pork', 'oatmeal'),
  ('Tofu and Vegetable Stir-Fry Breakfast Bowl', 'stir_fry'),
  ('Tofu Veggie Scramble', 'eggs'),
  ('Turkey Sausage Breakfast Bowl', 'bowl'),
  ('Vegetable Upma', 'oatmeal'),
  ('Veggie Breakfast Burrito', 'burrito'),
  ('Veggie Egg Scramble', 'eggs'),
  ('Whole Wheat Ricotta Pancakes', 'pancakes'),
  ('Yogurt with Mango and Cardamom', 'bowl'),
  ('Za''atar Flatbread with Labneh', 'pizza'),
  ('Baingan Bharta (Roasted Eggplant Curry)', 'curry'),
  ('Baked Chicken Parmesan', 'casserole'),
  ('Baked Cod with Olives and Tomatoes', 'seafood'),
  ('Baked Cod with Quinoa', 'seafood'),
  ('Baked Cod with Sweet Potato Mash', 'seafood'),
  ('Baked Salmon with Lemon and Capers', 'seafood'),
  ('Baked Salmon with Roasted Vegetables', 'seafood'),
  ('BBQ Turkey Meatballs with Green Beans', 'bbq'),
  ('Beef and Broccoli', 'stir_fry'),
  ('Beef Fajitas with Peppers', 'tacos'),
  ('Beef Sukiyaki', 'stew'),
  ('Black Bean Sweet Potato Bowl', 'bowl'),
  ('Black Bean Tacos', 'tacos'),
  ('Butter Chicken with Naan', 'curry'),
  ('Caprese Baked Gnocchi', 'pasta'),
  ('Cashew Chicken Thai-Style', 'stir_fry'),
  ('Chicken Cacciatore', 'stew'),
  ('Chicken Enchiladas Verdes', 'casserole'),
  ('Chicken Katsu Curry', 'curry'),
  ('Chicken Mole Bowl', 'curry'),
  ('Chicken Souvlaki with Greek Salad', 'grilled'),
  ('Chicken Stir Fry', 'stir_fry'),
  ('Chicken Thighs with Sun-Dried Tomatoes and Olives', 'grilled'),
  ('Chicken Vindaloo', 'curry'),
  ('Chicken Yakitori Skewers with Rice', 'grilled'),
  ('Chickpea Coconut Curry', 'curry'),
  ('Drunken Noodles (Pad Kee Mao) with Beef', 'noodles'),
  ('Eggplant Parmesan', 'casserole'),
  ('Fish Curry with Coconut', 'curry'),
  ('Garlic Shrimp and Bok Choy', 'stir_fry'),
  ('General Tso''s Chicken Bowl', 'stir_fry'),
  ('Grilled Branzino with Lemon', 'seafood'),
  ('Grilled Fish Tacos with Cabbage Slaw', 'tacos'),
  ('Grilled Pork Skewers (Moo Ping) with Sticky Rice', 'grilled'),
  ('Grilled Steak with Roasted Broccoli', 'grilled'),
  ('Herb-Roasted Pork Tenderloin with Sweet Potato', 'grilled'),
  ('Lamb Kofta with Tzatziki', 'grilled'),
  ('Lamb Rogan Josh', 'curry'),
  ('Lentil Bolognese with Spaghetti', 'pasta'),
  ('Meatloaf with Mashed Cauliflower', 'casserole'),
  ('Miso Glazed Black Cod', 'seafood'),
  ('Mongolian Beef with Scallions', 'stir_fry'),
  ('Moussaka', 'casserole'),
  ('Orange Chicken with Broccoli', 'stir_fry'),
  ('Palak Paneer', 'curry'),
  ('Panang Curry Chicken', 'curry'),
  ('Paneer Tikka Bowl', 'bowl'),
  ('Pineapple Fried Rice with Shrimp', 'rice'),
  ('Pork Chile Verde', 'stew'),
  ('Rajma (Kidney Bean Curry) with Rice', 'curry'),
  ('Red Curry Salmon', 'curry'),
  ('Sausage and White Bean Stew', 'stew'),
  ('Shrimp and Orzo with Feta', 'pasta'),
  ('Shrimp and Vegetable Tempura', 'seafood'),
  ('Shrimp Curry (Goan-Style)', 'curry'),
  ('Shrimp Fajita Bowl', 'bowl'),
  ('Shrimp Scampi with Zucchini Noodles', 'pasta'),
  ('Steamed Fish with Ginger and Scallion', 'seafood'),
  ('Stuffed Grape Leaves (Dolmas) with Rice', 'rice'),
  ('Sweet and Sour Pork', 'stir_fry'),
  ('Teriyaki Salmon with Steamed Broccoli', 'seafood'),
  ('Teriyaki Tempeh Stir-fry', 'stir_fry'),
  ('Thai Basil Eggplant with Tofu', 'stir_fry'),
  ('Tofu Green Curry with Brown Rice', 'curry'),
  ('Tom Kha Gai (Coconut Chicken Soup)', 'soup'),
  ('Turkey Bolognese over Spaghetti Squash', 'pasta'),
  ('Turkey Chili', 'chili'),
  ('Unagi Don (Grilled Eel Rice Bowl)', 'rice'),
  ('Vegetable and Tofu Stir-Fry with Ginger', 'stir_fry'),
  ('Vegetarian Enchiladas with Black Beans', 'casserole'),
  ('Veggie Egg Fried Rice', 'rice'),
  ('White Bean Mushroom Ragout with Polenta', 'stew'),
  ('Whole Wheat Penne with Turkey Meatballs', 'pasta'),
  ('BBQ Chicken Salad', 'salad'),
  ('Beef and Broccoli Lettuce Wraps', 'wrap'),
  ('Beef Yakiniku Bowl', 'bowl'),
  ('Black Bean and Rice Bowl', 'rice'),
  ('Buffalo Chicken Lettuce Wraps', 'wrap'),
  ('Caprese Panini', 'sandwich'),
  ('Carne Asada Salad', 'salad'),
  ('Chana Masala (Chickpea Curry)', 'curry'),
  ('Cheese Tortellini Soup with Spinach', 'soup'),
  ('Chicken and Snow Pea Stir-Fry', 'stir_fry'),
  ('Chicken Burrito Bowl', 'bowl'),
  ('Chicken Katsu with Cabbage Slaw', 'grilled'),
  ('Chicken Piccata Lettuce Wraps', 'wrap'),
  ('Chicken Shawarma Bowl', 'bowl'),
  ('Chicken Teriyaki Rice Bowl', 'rice'),
  ('Chicken Tikka Masala Bowl', 'curry'),
  ('Chicken Tinga Tacos', 'tacos'),
  ('Chicken Tortilla Soup', 'soup'),
  ('Chickpea and Spinach Curry (Saag Chana)', 'curry'),
  ('Chickpea and Spinach Salad with Feta', 'salad'),
  ('Chickpea and Tuna Salad', 'salad'),
  ('Dal Makhani with Rice', 'curry'),
  ('Falafel Pita Wrap', 'wrap'),
  ('Greek Salad with Grilled Chicken', 'salad'),
  ('Green Curry Chicken Bowl', 'curry'),
  ('Grilled Chicken Salad', 'salad'),
  ('Grilled Shrimp Souvlaki Bowl', 'bowl'),
  ('Hot and Sour Soup with Tofu', 'soup'),
  ('Italian Wedding Soup', 'soup'),
  ('Kung Pao Chicken Bowl', 'stir_fry'),
  ('Lamb Curry with Basmati Rice', 'curry'),
  ('Larb Gai (Chicken Larb)', 'salad'),
  ('Lentil Soup', 'soup'),
  ('Lentil Soup (Mediterranean-Style)', 'soup'),
  ('Massaman Beef Curry Bowl', 'curry'),
  ('Mediterranean Quinoa Salad', 'salad'),
  ('Mediterranean Tuna Salad', 'salad'),
  ('Minestrone Soup', 'soup'),
  ('Miso Ginger Soba with Roasted Vegetables', 'noodles'),
  ('Miso Salmon with Rice', 'seafood'),
  ('Pad Thai with Shrimp', 'noodles'),
  ('Paneer Tikka Salad', 'salad'),
  ('Peanut Noodle Bowl with Edamame', 'noodles'),
  ('Pork Carnitas Bowl', 'bowl'),
  ('Prosciutto Arugula Flatbread', 'pizza'),
  ('Salmon Teriyaki Bowl', 'rice'),
  ('Sesame Chicken Salad', 'salad'),
  ('Shrimp and Vegetable Fried Rice', 'rice'),
  ('Shrimp Tempura Udon', 'noodles'),
  ('Shrimp Tostadas', 'tacos'),
  ('Smoky Tofu Burrito Bowl', 'bowl'),
  ('Soba Noodle Salad with Sesame Dressing', 'noodles'),
  ('Som Tam (Green Papaya Salad) with Shrimp', 'salad'),
  ('Southwest Quinoa Bowl', 'bowl'),
  ('Tabbouleh with Grilled Chicken', 'salad'),
  ('Tandoori Chicken with Cucumber Raita', 'grilled'),
  ('Thai Basil Turkey Lettuce Wraps', 'wrap'),
  ('Tofu Pad See Ew', 'noodles'),
  ('Tofu Poke Bowl', 'bowl'),
  ('Tom Yum Soup with Shrimp', 'soup'),
  ('Tuna Salad Lettuce Wraps', 'wrap'),
  ('Turkey and Avocado Wrap', 'wrap'),
  ('Turkey Club Wrap', 'wrap'),
  ('Tuscan White Bean Salad', 'salad'),
  ('Vegetable Biryani', 'rice'),
  ('Vegetable Lo Mein', 'noodles'),
  ('Vegetarian Fajita Bowl', 'bowl'),
  ('Vegetarian Mapo Tofu Bowl', 'bowl'),
  ('Apple with Almond Butter', 'snack_bite'),
  ('Black Bean Hummus with Veggies', 'dip'),
  ('Black Bean Salsa with Bell Pepper Chips', 'dip'),
  ('Char Siu Pork Bites', 'snack_bite'),
  ('Chicken Taquito Snack Plate', 'snack_bite'),
  ('Chinese Five-Spice Roasted Chickpeas', 'snack_bite'),
  ('Coconut Mango Lassi', 'smoothie'),
  ('Cottage Cheese and Cucumber Bites', 'snack_bite'),
  ('Cottage Cheese with Pineapple', 'bowl'),
  ('Cucumber Jicama Chili-Lime Snack', 'snack_bite'),
  ('Cucumber Raita', 'dip'),
  ('Edamame Hummus with Nori Chips', 'dip'),
  ('Edamame with Sea Salt', 'snack_bite'),
  ('Edamame with Shichimi Togarashi', 'snack_bite'),
  ('Elote-Style Corn Cup', 'snack_bite'),
  ('Fig and Almond Bites', 'snack_bite'),
  ('Fresh Spring Rolls with Peanut Sauce', 'wrap'),
  ('Greek Yogurt Tzatziki with Veggies', 'dip'),
  ('Greek Yogurt with Honey', 'bowl'),
  ('Green Tea Rice Cakes with Red Bean', 'snack_bite'),
  ('Guacamole and Jicama Sticks', 'dip'),
  ('Hard-Boiled Eggs', 'eggs'),
  ('Hummus and Veggies', 'dip'),
  ('Italian Tuna and White Bean Snack Cups', 'snack_bite'),
  ('Mango Lassi', 'smoothie'),
  ('Mango Sticky Rice Bites', 'snack_bite'),
  ('Marinated Mozzarella & Tomato Skewers', 'snack_bite'),
  ('Marinated Olives and Feta', 'snack_bite'),
  ('Masala Roasted Almonds', 'snack_bite'),
  ('Mediterranean Tuna and Chickpea Cups', 'snack_bite'),
  ('Miso-Glazed Eggplant Bites', 'snack_bite'),
  ('Onigiri with Umeboshi', 'rice'),
  ('Paneer Tikka Skewers', 'grilled'),
  ('Parmesan Crisps', 'snack_bite'),
  ('Peanut Butter Banana Rice Cakes', 'snack_bite'),
  ('Pesto White Bean Dip with Veggies', 'dip'),
  ('Prosciutto-Wrapped Melon Bites', 'snack_bite'),
  ('Protein Shake', 'smoothie'),
  ('Queso Fresco and Tomato Skewers', 'snack_bite'),
  ('Roasted Chickpeas with Italian Herbs', 'snack_bite'),
  ('Roasted Coconut Cashews', 'snack_bite'),
  ('Roasted Masala Chickpeas', 'snack_bite'),
  ('Roasted Pepitas with Chili-Lime', 'snack_bite'),
  ('Roasted Red Pepper Hummus with Pita', 'dip'),
  ('Roasted Sesame Almonds', 'snack_bite'),
  ('Roasted Wasabi Peas', 'snack_bite'),
  ('Salmon Nigiri Snack Plate', 'rice'),
  ('Seaweed Rice Crackers with Soy Glaze', 'snack_bite'),
  ('Seaweed Salad', 'salad'),
  ('Shrimp Chips with Scallion Dip', 'dip'),
  ('Spiced Roasted Cashews', 'snack_bite'),
  ('Spiced Roasted Chickpeas Mediterranean-Style', 'snack_bite'),
  ('Sprouted Moong Bean Salad', 'salad'),
  ('Steamed Pork Dumplings', 'snack_bite'),
  ('Stuffed Grape Leaves Snack Plate', 'snack_bite'),
  ('Tamago Egg Bites', 'eggs'),
  ('Thai Chili-Lime Edamame', 'snack_bite'),
  ('Thai Cucumber Salad', 'salad'),
  ('Thai Fish Cakes (Tod Mun Pla)', 'snack_bite'),
  ('Thai Peanut Chicken Satay Skewers', 'grilled'),
  ('Turkey Jerky and Apple Slices', 'snack_bite'),
  ('Vegetable Samosas (Baked)', 'baked'),
  ('White Bean Bruschetta', 'toast')
) as m(name, dish_type)
where r.name = m.name;

-- Fail loudly rather than silently shipping a half-typed library: if any
-- recipe was added between this migration being written and applied, the
-- NOT NULL below would fail with a generic error. This says why.
do $$
declare missing int;
begin
  select count(*) into missing from public.recipes where dish_type is null;
  if missing > 0 then
    raise exception 'dish_type backfill missed % recipe(s) -- add them to this migration''s VALUES list', missing;
  end if;
end $$;

alter table public.recipes
  alter column dish_type set not null;

-- Browsing is always "this meal type, this dish type" (the picker scopes
-- to a slot before anything else), so the composite matches the real
-- query shape rather than dish_type alone.
create index if not exists recipes_meal_type_dish_type_idx
  on public.recipes (meal_type, dish_type);
